package com.jemmmedia.organise.mybatis.db.mybatis.model;

import java.util.Date;

public class Annoucement extends BaseModel {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column announcements.starts_at
     *
     * @mbggenerated Mon Aug 06 10:08:53 BST 2012
     */
    private Date startsAt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column announcements.ends_at
     *
     * @mbggenerated Mon Aug 06 10:08:53 BST 2012
     */
    private Date endsAt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column announcements.creator_id
     *
     * @mbggenerated Mon Aug 06 10:08:53 BST 2012
     */
    private Integer creatorId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column announcements.updater_id
     *
     * @mbggenerated Mon Aug 06 10:08:53 BST 2012
     */
    private Integer updaterId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column announcements.internal
     *
     * @mbggenerated Mon Aug 06 10:08:53 BST 2012
     */
    private Boolean internal;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column announcements.message
     *
     * @mbggenerated Mon Aug 06 10:08:53 BST 2012
     */
    private String message;

        
    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column announcements.starts_at
     *
     * @return the value of announcements.starts_at
     *
     * @mbggenerated Mon Aug 06 10:08:53 BST 2012
     */
    public Date getStartsAt() {
        return startsAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column announcements.starts_at
     *
     * @param startsAt the value for announcements.starts_at
     *
     * @mbggenerated Mon Aug 06 10:08:53 BST 2012
     */
    public void setStartsAt(Date startsAt) {
        this.startsAt = startsAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column announcements.ends_at
     *
     * @return the value of announcements.ends_at
     *
     * @mbggenerated Mon Aug 06 10:08:53 BST 2012
     */
    public Date getEndsAt() {
        return endsAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column announcements.ends_at
     *
     * @param endsAt the value for announcements.ends_at
     *
     * @mbggenerated Mon Aug 06 10:08:53 BST 2012
     */
    public void setEndsAt(Date endsAt) {
        this.endsAt = endsAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column announcements.creator_id
     *
     * @return the value of announcements.creator_id
     *
     * @mbggenerated Mon Aug 06 10:08:53 BST 2012
     */
    public Integer getCreatorId() {
        return creatorId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column announcements.creator_id
     *
     * @param creatorId the value for announcements.creator_id
     *
     * @mbggenerated Mon Aug 06 10:08:53 BST 2012
     */
    public void setCreatorId(Integer creatorId) {
        this.creatorId = creatorId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column announcements.updater_id
     *
     * @return the value of announcements.updater_id
     *
     * @mbggenerated Mon Aug 06 10:08:53 BST 2012
     */
    public Integer getUpdaterId() {
        return updaterId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column announcements.updater_id
     *
     * @param updaterId the value for announcements.updater_id
     *
     * @mbggenerated Mon Aug 06 10:08:53 BST 2012
     */
    public void setUpdaterId(Integer updaterId) {
        this.updaterId = updaterId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column announcements.internal
     *
     * @return the value of announcements.internal
     *
     * @mbggenerated Mon Aug 06 10:08:53 BST 2012
     */
    public Boolean getInternal() {
        return internal;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column announcements.internal
     *
     * @param internal the value for announcements.internal
     *
     * @mbggenerated Mon Aug 06 10:08:53 BST 2012
     */
    public void setInternal(Boolean internal) {
        this.internal = internal;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column announcements.message
     *
     * @return the value of announcements.message
     *
     * @mbggenerated Mon Aug 06 10:08:53 BST 2012
     */
    public String getMessage() {
        return message;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column announcements.message
     *
     * @param message the value for announcements.message
     *
     * @mbggenerated Mon Aug 06 10:08:53 BST 2012
     */
    public void setMessage(String message) {
        this.message = message == null ? null : message.trim();
    }
}