package com.jemmmedia.organise.mybatis.db.mybatis.model;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class AnnouncementsExample {
    /**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table announcements
	 * @mbggenerated  Mon Mar 25 13:45:28 GMT 2013
	 */
	protected String orderByClause;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table announcements
	 * @mbggenerated  Mon Mar 25 13:45:28 GMT 2013
	 */
	protected boolean distinct;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table announcements
	 * @mbggenerated  Mon Mar 25 13:45:28 GMT 2013
	 */
	protected List<Criteria> oredCriteria;

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table announcements
	 * @mbggenerated  Mon Mar 25 13:45:28 GMT 2013
	 */
	public AnnouncementsExample() {
		oredCriteria = new ArrayList<Criteria>();
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table announcements
	 * @mbggenerated  Mon Mar 25 13:45:28 GMT 2013
	 */
	public void setOrderByClause(String orderByClause) {
		this.orderByClause = orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table announcements
	 * @mbggenerated  Mon Mar 25 13:45:28 GMT 2013
	 */
	public String getOrderByClause() {
		return orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table announcements
	 * @mbggenerated  Mon Mar 25 13:45:28 GMT 2013
	 */
	public void setDistinct(boolean distinct) {
		this.distinct = distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table announcements
	 * @mbggenerated  Mon Mar 25 13:45:28 GMT 2013
	 */
	public boolean isDistinct() {
		return distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table announcements
	 * @mbggenerated  Mon Mar 25 13:45:28 GMT 2013
	 */
	public List<Criteria> getOredCriteria() {
		return oredCriteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table announcements
	 * @mbggenerated  Mon Mar 25 13:45:28 GMT 2013
	 */
	public void or(Criteria criteria) {
		oredCriteria.add(criteria);
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table announcements
	 * @mbggenerated  Mon Mar 25 13:45:28 GMT 2013
	 */
	public Criteria or() {
		Criteria criteria = createCriteriaInternal();
		oredCriteria.add(criteria);
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table announcements
	 * @mbggenerated  Mon Mar 25 13:45:28 GMT 2013
	 */
	public Criteria createCriteria() {
		Criteria criteria = createCriteriaInternal();
		if (oredCriteria.size() == 0) {
			oredCriteria.add(criteria);
		}
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table announcements
	 * @mbggenerated  Mon Mar 25 13:45:28 GMT 2013
	 */
	protected Criteria createCriteriaInternal() {
		Criteria criteria = new Criteria();
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table announcements
	 * @mbggenerated  Mon Mar 25 13:45:28 GMT 2013
	 */
	public void clear() {
		oredCriteria.clear();
		orderByClause = null;
		distinct = false;
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table announcements
	 * @mbggenerated  Mon Mar 25 13:45:28 GMT 2013
	 */
	protected abstract static class GeneratedCriteria {
		protected List<Criterion> criteria;

		protected GeneratedCriteria() {
			super();
			criteria = new ArrayList<Criterion>();
		}

		public boolean isValid() {
			return criteria.size() > 0;
		}

		public List<Criterion> getAllCriteria() {
			return criteria;
		}

		public List<Criterion> getCriteria() {
			return criteria;
		}

		protected void addCriterion(String condition) {
			if (condition == null) {
				throw new RuntimeException("Value for condition cannot be null");
			}
			criteria.add(new Criterion(condition));
		}

		protected void addCriterion(String condition, Object value,
				String property) {
			if (value == null) {
				throw new RuntimeException("Value for " + property
						+ " cannot be null");
			}
			criteria.add(new Criterion(condition, value));
		}

		protected void addCriterion(String condition, Object value1,
				Object value2, String property) {
			if (value1 == null || value2 == null) {
				throw new RuntimeException("Between values for " + property
						+ " cannot be null");
			}
			criteria.add(new Criterion(condition, value1, value2));
		}

		public Criteria andIdIsNull() {
			addCriterion("id is null");
			return (Criteria) this;
		}

		public Criteria andIdIsNotNull() {
			addCriterion("id is not null");
			return (Criteria) this;
		}

		public Criteria andIdEqualTo(Long value) {
			addCriterion("id =", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdNotEqualTo(Long value) {
			addCriterion("id <>", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdGreaterThan(Long value) {
			addCriterion("id >", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdGreaterThanOrEqualTo(Long value) {
			addCriterion("id >=", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdLessThan(Long value) {
			addCriterion("id <", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdLessThanOrEqualTo(Long value) {
			addCriterion("id <=", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdIn(List<Long> values) {
			addCriterion("id in", values, "id");
			return (Criteria) this;
		}

		public Criteria andIdNotIn(List<Long> values) {
			addCriterion("id not in", values, "id");
			return (Criteria) this;
		}

		public Criteria andIdBetween(Long value1, Long value2) {
			addCriterion("id between", value1, value2, "id");
			return (Criteria) this;
		}

		public Criteria andIdNotBetween(Long value1, Long value2) {
			addCriterion("id not between", value1, value2, "id");
			return (Criteria) this;
		}

		public Criteria andStartsAtIsNull() {
			addCriterion("starts_at is null");
			return (Criteria) this;
		}

		public Criteria andStartsAtIsNotNull() {
			addCriterion("starts_at is not null");
			return (Criteria) this;
		}

		public Criteria andStartsAtEqualTo(Date value) {
			addCriterion("starts_at =", value, "startsAt");
			return (Criteria) this;
		}

		public Criteria andStartsAtNotEqualTo(Date value) {
			addCriterion("starts_at <>", value, "startsAt");
			return (Criteria) this;
		}

		public Criteria andStartsAtGreaterThan(Date value) {
			addCriterion("starts_at >", value, "startsAt");
			return (Criteria) this;
		}

		public Criteria andStartsAtGreaterThanOrEqualTo(Date value) {
			addCriterion("starts_at >=", value, "startsAt");
			return (Criteria) this;
		}

		public Criteria andStartsAtLessThan(Date value) {
			addCriterion("starts_at <", value, "startsAt");
			return (Criteria) this;
		}

		public Criteria andStartsAtLessThanOrEqualTo(Date value) {
			addCriterion("starts_at <=", value, "startsAt");
			return (Criteria) this;
		}

		public Criteria andStartsAtIn(List<Date> values) {
			addCriterion("starts_at in", values, "startsAt");
			return (Criteria) this;
		}

		public Criteria andStartsAtNotIn(List<Date> values) {
			addCriterion("starts_at not in", values, "startsAt");
			return (Criteria) this;
		}

		public Criteria andStartsAtBetween(Date value1, Date value2) {
			addCriterion("starts_at between", value1, value2, "startsAt");
			return (Criteria) this;
		}

		public Criteria andStartsAtNotBetween(Date value1, Date value2) {
			addCriterion("starts_at not between", value1, value2, "startsAt");
			return (Criteria) this;
		}

		public Criteria andEndsAtIsNull() {
			addCriterion("ends_at is null");
			return (Criteria) this;
		}

		public Criteria andEndsAtIsNotNull() {
			addCriterion("ends_at is not null");
			return (Criteria) this;
		}

		public Criteria andEndsAtEqualTo(Date value) {
			addCriterion("ends_at =", value, "endsAt");
			return (Criteria) this;
		}

		public Criteria andEndsAtNotEqualTo(Date value) {
			addCriterion("ends_at <>", value, "endsAt");
			return (Criteria) this;
		}

		public Criteria andEndsAtGreaterThan(Date value) {
			addCriterion("ends_at >", value, "endsAt");
			return (Criteria) this;
		}

		public Criteria andEndsAtGreaterThanOrEqualTo(Date value) {
			addCriterion("ends_at >=", value, "endsAt");
			return (Criteria) this;
		}

		public Criteria andEndsAtLessThan(Date value) {
			addCriterion("ends_at <", value, "endsAt");
			return (Criteria) this;
		}

		public Criteria andEndsAtLessThanOrEqualTo(Date value) {
			addCriterion("ends_at <=", value, "endsAt");
			return (Criteria) this;
		}

		public Criteria andEndsAtIn(List<Date> values) {
			addCriterion("ends_at in", values, "endsAt");
			return (Criteria) this;
		}

		public Criteria andEndsAtNotIn(List<Date> values) {
			addCriterion("ends_at not in", values, "endsAt");
			return (Criteria) this;
		}

		public Criteria andEndsAtBetween(Date value1, Date value2) {
			addCriterion("ends_at between", value1, value2, "endsAt");
			return (Criteria) this;
		}

		public Criteria andEndsAtNotBetween(Date value1, Date value2) {
			addCriterion("ends_at not between", value1, value2, "endsAt");
			return (Criteria) this;
		}

		public Criteria andCreatedAtIsNull() {
			addCriterion("created_at is null");
			return (Criteria) this;
		}

		public Criteria andCreatedAtIsNotNull() {
			addCriterion("created_at is not null");
			return (Criteria) this;
		}

		public Criteria andCreatedAtEqualTo(Date value) {
			addCriterion("created_at =", value, "createdAt");
			return (Criteria) this;
		}

		public Criteria andCreatedAtNotEqualTo(Date value) {
			addCriterion("created_at <>", value, "createdAt");
			return (Criteria) this;
		}

		public Criteria andCreatedAtGreaterThan(Date value) {
			addCriterion("created_at >", value, "createdAt");
			return (Criteria) this;
		}

		public Criteria andCreatedAtGreaterThanOrEqualTo(Date value) {
			addCriterion("created_at >=", value, "createdAt");
			return (Criteria) this;
		}

		public Criteria andCreatedAtLessThan(Date value) {
			addCriterion("created_at <", value, "createdAt");
			return (Criteria) this;
		}

		public Criteria andCreatedAtLessThanOrEqualTo(Date value) {
			addCriterion("created_at <=", value, "createdAt");
			return (Criteria) this;
		}

		public Criteria andCreatedAtIn(List<Date> values) {
			addCriterion("created_at in", values, "createdAt");
			return (Criteria) this;
		}

		public Criteria andCreatedAtNotIn(List<Date> values) {
			addCriterion("created_at not in", values, "createdAt");
			return (Criteria) this;
		}

		public Criteria andCreatedAtBetween(Date value1, Date value2) {
			addCriterion("created_at between", value1, value2, "createdAt");
			return (Criteria) this;
		}

		public Criteria andCreatedAtNotBetween(Date value1, Date value2) {
			addCriterion("created_at not between", value1, value2, "createdAt");
			return (Criteria) this;
		}

		public Criteria andUpdatedAtIsNull() {
			addCriterion("updated_at is null");
			return (Criteria) this;
		}

		public Criteria andUpdatedAtIsNotNull() {
			addCriterion("updated_at is not null");
			return (Criteria) this;
		}

		public Criteria andUpdatedAtEqualTo(Date value) {
			addCriterion("updated_at =", value, "updatedAt");
			return (Criteria) this;
		}

		public Criteria andUpdatedAtNotEqualTo(Date value) {
			addCriterion("updated_at <>", value, "updatedAt");
			return (Criteria) this;
		}

		public Criteria andUpdatedAtGreaterThan(Date value) {
			addCriterion("updated_at >", value, "updatedAt");
			return (Criteria) this;
		}

		public Criteria andUpdatedAtGreaterThanOrEqualTo(Date value) {
			addCriterion("updated_at >=", value, "updatedAt");
			return (Criteria) this;
		}

		public Criteria andUpdatedAtLessThan(Date value) {
			addCriterion("updated_at <", value, "updatedAt");
			return (Criteria) this;
		}

		public Criteria andUpdatedAtLessThanOrEqualTo(Date value) {
			addCriterion("updated_at <=", value, "updatedAt");
			return (Criteria) this;
		}

		public Criteria andUpdatedAtIn(List<Date> values) {
			addCriterion("updated_at in", values, "updatedAt");
			return (Criteria) this;
		}

		public Criteria andUpdatedAtNotIn(List<Date> values) {
			addCriterion("updated_at not in", values, "updatedAt");
			return (Criteria) this;
		}

		public Criteria andUpdatedAtBetween(Date value1, Date value2) {
			addCriterion("updated_at between", value1, value2, "updatedAt");
			return (Criteria) this;
		}

		public Criteria andUpdatedAtNotBetween(Date value1, Date value2) {
			addCriterion("updated_at not between", value1, value2, "updatedAt");
			return (Criteria) this;
		}

		public Criteria andCreatorIdIsNull() {
			addCriterion("creator_id is null");
			return (Criteria) this;
		}

		public Criteria andCreatorIdIsNotNull() {
			addCriterion("creator_id is not null");
			return (Criteria) this;
		}

		public Criteria andCreatorIdEqualTo(Integer value) {
			addCriterion("creator_id =", value, "creatorId");
			return (Criteria) this;
		}

		public Criteria andCreatorIdNotEqualTo(Integer value) {
			addCriterion("creator_id <>", value, "creatorId");
			return (Criteria) this;
		}

		public Criteria andCreatorIdGreaterThan(Integer value) {
			addCriterion("creator_id >", value, "creatorId");
			return (Criteria) this;
		}

		public Criteria andCreatorIdGreaterThanOrEqualTo(Integer value) {
			addCriterion("creator_id >=", value, "creatorId");
			return (Criteria) this;
		}

		public Criteria andCreatorIdLessThan(Integer value) {
			addCriterion("creator_id <", value, "creatorId");
			return (Criteria) this;
		}

		public Criteria andCreatorIdLessThanOrEqualTo(Integer value) {
			addCriterion("creator_id <=", value, "creatorId");
			return (Criteria) this;
		}

		public Criteria andCreatorIdIn(List<Integer> values) {
			addCriterion("creator_id in", values, "creatorId");
			return (Criteria) this;
		}

		public Criteria andCreatorIdNotIn(List<Integer> values) {
			addCriterion("creator_id not in", values, "creatorId");
			return (Criteria) this;
		}

		public Criteria andCreatorIdBetween(Integer value1, Integer value2) {
			addCriterion("creator_id between", value1, value2, "creatorId");
			return (Criteria) this;
		}

		public Criteria andCreatorIdNotBetween(Integer value1, Integer value2) {
			addCriterion("creator_id not between", value1, value2, "creatorId");
			return (Criteria) this;
		}

		public Criteria andUpdaterIdIsNull() {
			addCriterion("updater_id is null");
			return (Criteria) this;
		}

		public Criteria andUpdaterIdIsNotNull() {
			addCriterion("updater_id is not null");
			return (Criteria) this;
		}

		public Criteria andUpdaterIdEqualTo(Integer value) {
			addCriterion("updater_id =", value, "updaterId");
			return (Criteria) this;
		}

		public Criteria andUpdaterIdNotEqualTo(Integer value) {
			addCriterion("updater_id <>", value, "updaterId");
			return (Criteria) this;
		}

		public Criteria andUpdaterIdGreaterThan(Integer value) {
			addCriterion("updater_id >", value, "updaterId");
			return (Criteria) this;
		}

		public Criteria andUpdaterIdGreaterThanOrEqualTo(Integer value) {
			addCriterion("updater_id >=", value, "updaterId");
			return (Criteria) this;
		}

		public Criteria andUpdaterIdLessThan(Integer value) {
			addCriterion("updater_id <", value, "updaterId");
			return (Criteria) this;
		}

		public Criteria andUpdaterIdLessThanOrEqualTo(Integer value) {
			addCriterion("updater_id <=", value, "updaterId");
			return (Criteria) this;
		}

		public Criteria andUpdaterIdIn(List<Integer> values) {
			addCriterion("updater_id in", values, "updaterId");
			return (Criteria) this;
		}

		public Criteria andUpdaterIdNotIn(List<Integer> values) {
			addCriterion("updater_id not in", values, "updaterId");
			return (Criteria) this;
		}

		public Criteria andUpdaterIdBetween(Integer value1, Integer value2) {
			addCriterion("updater_id between", value1, value2, "updaterId");
			return (Criteria) this;
		}

		public Criteria andUpdaterIdNotBetween(Integer value1, Integer value2) {
			addCriterion("updater_id not between", value1, value2, "updaterId");
			return (Criteria) this;
		}

		public Criteria andInternalIsNull() {
			addCriterion("internal is null");
			return (Criteria) this;
		}

		public Criteria andInternalIsNotNull() {
			addCriterion("internal is not null");
			return (Criteria) this;
		}

		public Criteria andInternalEqualTo(Boolean value) {
			addCriterion("internal =", value, "internal");
			return (Criteria) this;
		}

		public Criteria andInternalNotEqualTo(Boolean value) {
			addCriterion("internal <>", value, "internal");
			return (Criteria) this;
		}

		public Criteria andInternalGreaterThan(Boolean value) {
			addCriterion("internal >", value, "internal");
			return (Criteria) this;
		}

		public Criteria andInternalGreaterThanOrEqualTo(Boolean value) {
			addCriterion("internal >=", value, "internal");
			return (Criteria) this;
		}

		public Criteria andInternalLessThan(Boolean value) {
			addCriterion("internal <", value, "internal");
			return (Criteria) this;
		}

		public Criteria andInternalLessThanOrEqualTo(Boolean value) {
			addCriterion("internal <=", value, "internal");
			return (Criteria) this;
		}

		public Criteria andInternalIn(List<Boolean> values) {
			addCriterion("internal in", values, "internal");
			return (Criteria) this;
		}

		public Criteria andInternalNotIn(List<Boolean> values) {
			addCriterion("internal not in", values, "internal");
			return (Criteria) this;
		}

		public Criteria andInternalBetween(Boolean value1, Boolean value2) {
			addCriterion("internal between", value1, value2, "internal");
			return (Criteria) this;
		}

		public Criteria andInternalNotBetween(Boolean value1, Boolean value2) {
			addCriterion("internal not between", value1, value2, "internal");
			return (Criteria) this;
		}

		public Criteria andGroupIdIsNull() {
			addCriterion("group_id is null");
			return (Criteria) this;
		}

		public Criteria andGroupIdIsNotNull() {
			addCriterion("group_id is not null");
			return (Criteria) this;
		}

		public Criteria andGroupIdEqualTo(Long value) {
			addCriterion("group_id =", value, "groupId");
			return (Criteria) this;
		}

		public Criteria andGroupIdNotEqualTo(Long value) {
			addCriterion("group_id <>", value, "groupId");
			return (Criteria) this;
		}

		public Criteria andGroupIdGreaterThan(Long value) {
			addCriterion("group_id >", value, "groupId");
			return (Criteria) this;
		}

		public Criteria andGroupIdGreaterThanOrEqualTo(Long value) {
			addCriterion("group_id >=", value, "groupId");
			return (Criteria) this;
		}

		public Criteria andGroupIdLessThan(Long value) {
			addCriterion("group_id <", value, "groupId");
			return (Criteria) this;
		}

		public Criteria andGroupIdLessThanOrEqualTo(Long value) {
			addCriterion("group_id <=", value, "groupId");
			return (Criteria) this;
		}

		public Criteria andGroupIdIn(List<Long> values) {
			addCriterion("group_id in", values, "groupId");
			return (Criteria) this;
		}

		public Criteria andGroupIdNotIn(List<Long> values) {
			addCriterion("group_id not in", values, "groupId");
			return (Criteria) this;
		}

		public Criteria andGroupIdBetween(Long value1, Long value2) {
			addCriterion("group_id between", value1, value2, "groupId");
			return (Criteria) this;
		}

		public Criteria andGroupIdNotBetween(Long value1, Long value2) {
			addCriterion("group_id not between", value1, value2, "groupId");
			return (Criteria) this;
		}
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table announcements
	 * @mbggenerated  Mon Mar 25 13:45:28 GMT 2013
	 */
	public static class Criterion {
		private String condition;
		private Object value;
		private Object secondValue;
		private boolean noValue;
		private boolean singleValue;
		private boolean betweenValue;
		private boolean listValue;
		private String typeHandler;

		public String getCondition() {
			return condition;
		}

		public Object getValue() {
			return value;
		}

		public Object getSecondValue() {
			return secondValue;
		}

		public boolean isNoValue() {
			return noValue;
		}

		public boolean isSingleValue() {
			return singleValue;
		}

		public boolean isBetweenValue() {
			return betweenValue;
		}

		public boolean isListValue() {
			return listValue;
		}

		public String getTypeHandler() {
			return typeHandler;
		}

		protected Criterion(String condition) {
			super();
			this.condition = condition;
			this.typeHandler = null;
			this.noValue = true;
		}

		protected Criterion(String condition, Object value, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.typeHandler = typeHandler;
			if (value instanceof List<?>) {
				this.listValue = true;
			} else {
				this.singleValue = true;
			}
		}

		protected Criterion(String condition, Object value) {
			this(condition, value, null);
		}

		protected Criterion(String condition, Object value, Object secondValue,
				String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.secondValue = secondValue;
			this.typeHandler = typeHandler;
			this.betweenValue = true;
		}

		protected Criterion(String condition, Object value, Object secondValue) {
			this(condition, value, secondValue, null);
		}
	}

	/**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table announcements
     *
     * @mbggenerated do_not_delete_during_merge Thu Nov 01 10:40:56 GMT 2012
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }
}