package com.jemmmedia.organise.mybatis.db.mybatis.model;

public class DeptUsersKey {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dept_users.user_id
     *
     * @mbggenerated Wed Aug 21 17:48:42 BST 2013
     */
    private Long userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dept_users.dept_id
     *
     * @mbggenerated Wed Aug 21 17:48:42 BST 2013
     */
    private Long deptId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dept_users.user_id
     *
     * @return the value of dept_users.user_id
     *
     * @mbggenerated Wed Aug 21 17:48:42 BST 2013
     */
    public Long getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dept_users.user_id
     *
     * @param userId the value for dept_users.user_id
     *
     * @mbggenerated Wed Aug 21 17:48:42 BST 2013
     */
    public void setUserId(Long userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dept_users.dept_id
     *
     * @return the value of dept_users.dept_id
     *
     * @mbggenerated Wed Aug 21 17:48:42 BST 2013
     */
    public Long getDeptId() {
        return deptId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dept_users.dept_id
     *
     * @param deptId the value for dept_users.dept_id
     *
     * @mbggenerated Wed Aug 21 17:48:42 BST 2013
     */
    public void setDeptId(Long deptId) {
        this.deptId = deptId;
    }
}