package com.jemmmedia.organise.mybatis.db.mybatis.model;

public class Dept extends BaseModel {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column dept.name
	 * @mbggenerated  Fri Aug 23 12:49:25 BST 2013
	 */
	private String name;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column dept.group_id
	 * @mbggenerated  Fri Aug 23 12:49:25 BST 2013
	 */
	private Long groupId;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column dept.name
	 * @return  the value of dept.name
	 * @mbggenerated  Fri Aug 23 12:49:25 BST 2013
	 */
	public String getName() {
		return name;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column dept.name
	 * @param name  the value for dept.name
	 * @mbggenerated  Fri Aug 23 12:49:25 BST 2013
	 */
	public void setName(String name) {
		this.name = name == null ? null : name.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column dept.group_id
	 * @return  the value of dept.group_id
	 * @mbggenerated  Fri Aug 23 12:49:25 BST 2013
	 */
	public Long getGroupId() {
		return groupId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column dept.group_id
	 * @param groupId  the value for dept.group_id
	 * @mbggenerated  Fri Aug 23 12:49:25 BST 2013
	 */
	public void setGroupId(Long groupId) {
		this.groupId = groupId;
	}
}