package com.jemmmedia.organise.mybatis.db.mybatis.model;

public class Feeds extends BaseModel {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column feeds.name
     *
     * @mbggenerated Fri Sep 21 12:03:33 BST 2012
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column feeds.url
     *
     * @mbggenerated Fri Sep 21 12:03:33 BST 2012
     */
    private String url;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column feeds.colour
     *
     * @mbggenerated Fri Sep 21 12:03:33 BST 2012
     */
    private String colour;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column feeds.source_type
     *
     * @mbggenerated Fri Sep 21 12:03:33 BST 2012
     */
    private String sourceType;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column feeds.name
     *
     * @return the value of feeds.name
     *
     * @mbggenerated Fri Sep 21 12:03:33 BST 2012
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column feeds.name
     *
     * @param name the value for feeds.name
     *
     * @mbggenerated Fri Sep 21 12:03:33 BST 2012
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column feeds.url
     *
     * @return the value of feeds.url
     *
     * @mbggenerated Fri Sep 21 12:03:33 BST 2012
     */
    public String getUrl() {
        return url;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column feeds.url
     *
     * @param url the value for feeds.url
     *
     * @mbggenerated Fri Sep 21 12:03:33 BST 2012
     */
    public void setUrl(String url) {
        this.url = url == null ? null : url.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column feeds.colour
     *
     * @return the value of feeds.colour
     *
     * @mbggenerated Fri Sep 21 12:03:33 BST 2012
     */
    public String getColour() {
        return colour;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column feeds.colour
     *
     * @param colour the value for feeds.colour
     *
     * @mbggenerated Fri Sep 21 12:03:33 BST 2012
     */
    public void setColour(String colour) {
        this.colour = colour == null ? null : colour.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column feeds.source_type
     *
     * @return the value of feeds.source_type
     *
     * @mbggenerated Fri Sep 21 12:03:33 BST 2012
     */
    public String getSourceType() {
        return sourceType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column feeds.source_type
     *
     * @param sourceType the value for feeds.source_type
     *
     * @mbggenerated Fri Sep 21 12:03:33 BST 2012
     */
    public void setSourceType(String sourceType) {
        this.sourceType = sourceType == null ? null : sourceType.trim();
    }
}