package com.jemmmedia.organise.mybatis.db.mybatis.model;

public class FeedSources_UsersKey {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column feed_sources_users.feed_source_id
	 * @mbggenerated  Wed Jul 03 14:38:35 BST 2013
	 */
	private Long feedSourceId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column feed_sources_users.user_id
	 * @mbggenerated  Wed Jul 03 14:38:35 BST 2013
	 */
	private Long userId;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column feed_sources_users.feed_source_id
	 * @return  the value of feed_sources_users.feed_source_id
	 * @mbggenerated  Wed Jul 03 14:38:35 BST 2013
	 */
	public Long getFeedSourceId() {
		return feedSourceId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column feed_sources_users.feed_source_id
	 * @param feedSourceId  the value for feed_sources_users.feed_source_id
	 * @mbggenerated  Wed Jul 03 14:38:35 BST 2013
	 */
	public void setFeedSourceId(Long feedSourceId) {
		this.feedSourceId = feedSourceId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column feed_sources_users.user_id
	 * @return  the value of feed_sources_users.user_id
	 * @mbggenerated  Wed Jul 03 14:38:35 BST 2013
	 */
	public Long getUserId() {
		return userId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column feed_sources_users.user_id
	 * @param userId  the value for feed_sources_users.user_id
	 * @mbggenerated  Wed Jul 03 14:38:35 BST 2013
	 */
	public void setUserId(Long userId) {
		this.userId = userId;
	}
    
}