package com.jemmmedia.organise.mybatis.db.mybatis.model;


public class FeedSource extends BaseModel {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column feed_sources.name
	 * @mbggenerated  Mon Feb 18 22:13:09 GMT 2013
	 */
	private String name;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column feed_sources.url
	 * @mbggenerated  Mon Feb 18 22:13:09 GMT 2013
	 */
	private String url;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column feed_sources.colour
	 * @mbggenerated  Mon Feb 18 22:13:09 GMT 2013
	 */
	private String colour;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column feed_sources.source_type
	 * @mbggenerated  Mon Feb 18 22:13:09 GMT 2013
	 */
	private Integer sourceType;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column feed_sources.token
	 * @mbggenerated  Mon Feb 18 22:13:09 GMT 2013
	 */
	private String token;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column feed_sources.group_id
	 * @mbggenerated  Mon Feb 18 22:13:09 GMT 2013
	 */
	private Long groupId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column feed_sources.parent_id
	 * @mbggenerated  Mon Feb 18 22:13:09 GMT 2013
	 */
	private Long parentId;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column feed_sources.name
	 * @return  the value of feed_sources.name
	 * @mbggenerated  Mon Feb 18 22:13:09 GMT 2013
	 */
	public String getName() {
		return name;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column feed_sources.name
	 * @param name  the value for feed_sources.name
	 * @mbggenerated  Mon Feb 18 22:13:09 GMT 2013
	 */
	public void setName(String name) {
		this.name = name == null ? null : name.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column feed_sources.url
	 * @return  the value of feed_sources.url
	 * @mbggenerated  Mon Feb 18 22:13:09 GMT 2013
	 */
	public String getUrl() {
		return url;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column feed_sources.url
	 * @param url  the value for feed_sources.url
	 * @mbggenerated  Mon Feb 18 22:13:09 GMT 2013
	 */
	public void setUrl(String url) {
		this.url = url == null ? null : url.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column feed_sources.colour
	 * @return  the value of feed_sources.colour
	 * @mbggenerated  Mon Feb 18 22:13:09 GMT 2013
	 */
	public String getColour() {
		return colour;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column feed_sources.colour
	 * @param colour  the value for feed_sources.colour
	 * @mbggenerated  Mon Feb 18 22:13:09 GMT 2013
	 */
	public void setColour(String colour) {
		this.colour = colour == null ? null : colour.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column feed_sources.source_type
	 * @return  the value of feed_sources.source_type
	 * @mbggenerated  Mon Feb 18 22:13:09 GMT 2013
	 */
	public Integer getSourceType() {
		return sourceType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column feed_sources.source_type
	 * @param sourceType  the value for feed_sources.source_type
	 * @mbggenerated  Mon Feb 18 22:13:09 GMT 2013
	 */
	public void setSourceType(Integer sourceType) {
		this.sourceType = sourceType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column feed_sources.token
	 * @return  the value of feed_sources.token
	 * @mbggenerated  Mon Feb 18 22:13:09 GMT 2013
	 */
	public String getToken() {
		return token;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column feed_sources.token
	 * @param token  the value for feed_sources.token
	 * @mbggenerated  Mon Feb 18 22:13:09 GMT 2013
	 */
	public void setToken(String token) {
		this.token = token == null ? null : token.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column feed_sources.group_id
	 * @return  the value of feed_sources.group_id
	 * @mbggenerated  Mon Feb 18 22:13:09 GMT 2013
	 */
	public Long getGroupId() {
		return groupId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column feed_sources.group_id
	 * @param groupId  the value for feed_sources.group_id
	 * @mbggenerated  Mon Feb 18 22:13:09 GMT 2013
	 */
	public void setGroupId(Long groupId) {
		this.groupId = groupId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column feed_sources.parent_id
	 * @return  the value of feed_sources.parent_id
	 * @mbggenerated  Mon Feb 18 22:13:09 GMT 2013
	 */
	public Long getParentId() {
		return parentId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column feed_sources.parent_id
	 * @param parentId  the value for feed_sources.parent_id
	 * @mbggenerated  Mon Feb 18 22:13:09 GMT 2013
	 */
	public void setParentId(Long parentId) {
		this.parentId = parentId;
	}
}