package com.jemmmedia.organise.mybatis.db.mybatis.model;

import java.util.Date;

public class FeedSources_Users extends FeedSources_UsersKey {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column feed_sources_users.created_at
	 * @mbggenerated  Wed Jul 03 14:38:35 BST 2013
	 */
	private Date createdAt;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column feed_sources_users.updated_at
	 * @mbggenerated  Wed Jul 03 14:38:35 BST 2013
	 */
	private Date updatedAt;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column feed_sources_users.created_at
	 * @return  the value of feed_sources_users.created_at
	 * @mbggenerated  Wed Jul 03 14:38:35 BST 2013
	 */
	public Date getCreatedAt() {
		return createdAt;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column feed_sources_users.created_at
	 * @param createdAt  the value for feed_sources_users.created_at
	 * @mbggenerated  Wed Jul 03 14:38:35 BST 2013
	 */
	public void setCreatedAt(Date createdAt) {
		this.createdAt = createdAt;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column feed_sources_users.updated_at
	 * @return  the value of feed_sources_users.updated_at
	 * @mbggenerated  Wed Jul 03 14:38:35 BST 2013
	 */
	public Date getUpdatedAt() {
		return updatedAt;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column feed_sources_users.updated_at
	 * @param updatedAt  the value for feed_sources_users.updated_at
	 * @mbggenerated  Wed Jul 03 14:38:35 BST 2013
	 */
	public void setUpdatedAt(Date updatedAt) {
		this.updatedAt = updatedAt;
	}
}