package com.jemmmedia.organise.mybatis.db.mybatis.model;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class FeedEntryExample {
    /**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table feed_entries
	 * @mbggenerated  Tue Oct 29 13:42:10 GMT 2013
	 */
	protected String orderByClause;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table feed_entries
	 * @mbggenerated  Tue Oct 29 13:42:10 GMT 2013
	 */
	protected boolean distinct;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table feed_entries
	 * @mbggenerated  Tue Oct 29 13:42:10 GMT 2013
	 */
	protected List<Criteria> oredCriteria;

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table feed_entries
	 * @mbggenerated  Tue Oct 29 13:42:10 GMT 2013
	 */
	public FeedEntryExample() {
		oredCriteria = new ArrayList<Criteria>();
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table feed_entries
	 * @mbggenerated  Tue Oct 29 13:42:10 GMT 2013
	 */
	public void setOrderByClause(String orderByClause) {
		this.orderByClause = orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table feed_entries
	 * @mbggenerated  Tue Oct 29 13:42:10 GMT 2013
	 */
	public String getOrderByClause() {
		return orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table feed_entries
	 * @mbggenerated  Tue Oct 29 13:42:10 GMT 2013
	 */
	public void setDistinct(boolean distinct) {
		this.distinct = distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table feed_entries
	 * @mbggenerated  Tue Oct 29 13:42:10 GMT 2013
	 */
	public boolean isDistinct() {
		return distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table feed_entries
	 * @mbggenerated  Tue Oct 29 13:42:10 GMT 2013
	 */
	public List<Criteria> getOredCriteria() {
		return oredCriteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table feed_entries
	 * @mbggenerated  Tue Oct 29 13:42:10 GMT 2013
	 */
	public void or(Criteria criteria) {
		oredCriteria.add(criteria);
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table feed_entries
	 * @mbggenerated  Tue Oct 29 13:42:10 GMT 2013
	 */
	public Criteria or() {
		Criteria criteria = createCriteriaInternal();
		oredCriteria.add(criteria);
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table feed_entries
	 * @mbggenerated  Tue Oct 29 13:42:10 GMT 2013
	 */
	public Criteria createCriteria() {
		Criteria criteria = createCriteriaInternal();
		if (oredCriteria.size() == 0) {
			oredCriteria.add(criteria);
		}
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table feed_entries
	 * @mbggenerated  Tue Oct 29 13:42:10 GMT 2013
	 */
	protected Criteria createCriteriaInternal() {
		Criteria criteria = new Criteria();
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table feed_entries
	 * @mbggenerated  Tue Oct 29 13:42:10 GMT 2013
	 */
	public void clear() {
		oredCriteria.clear();
		orderByClause = null;
		distinct = false;
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table feed_entries
	 * @mbggenerated  Tue Oct 29 13:42:10 GMT 2013
	 */
	protected abstract static class GeneratedCriteria {
		protected List<Criterion> criteria;

		protected GeneratedCriteria() {
			super();
			criteria = new ArrayList<Criterion>();
		}

		public boolean isValid() {
			return criteria.size() > 0;
		}

		public List<Criterion> getAllCriteria() {
			return criteria;
		}

		public List<Criterion> getCriteria() {
			return criteria;
		}

		protected void addCriterion(String condition) {
			if (condition == null) {
				throw new RuntimeException("Value for condition cannot be null");
			}
			criteria.add(new Criterion(condition));
		}

		protected void addCriterion(String condition, Object value,
				String property) {
			if (value == null) {
				throw new RuntimeException("Value for " + property
						+ " cannot be null");
			}
			criteria.add(new Criterion(condition, value));
		}

		protected void addCriterion(String condition, Object value1,
				Object value2, String property) {
			if (value1 == null || value2 == null) {
				throw new RuntimeException("Between values for " + property
						+ " cannot be null");
			}
			criteria.add(new Criterion(condition, value1, value2));
		}

		public Criteria andIdIsNull() {
			addCriterion("id is null");
			return (Criteria) this;
		}

		public Criteria andIdIsNotNull() {
			addCriterion("id is not null");
			return (Criteria) this;
		}

		public Criteria andIdEqualTo(Long value) {
			addCriterion("id =", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdNotEqualTo(Long value) {
			addCriterion("id <>", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdGreaterThan(Long value) {
			addCriterion("id >", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdGreaterThanOrEqualTo(Long value) {
			addCriterion("id >=", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdLessThan(Long value) {
			addCriterion("id <", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdLessThanOrEqualTo(Long value) {
			addCriterion("id <=", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdIn(List<Long> values) {
			addCriterion("id in", values, "id");
			return (Criteria) this;
		}

		public Criteria andIdNotIn(List<Long> values) {
			addCriterion("id not in", values, "id");
			return (Criteria) this;
		}

		public Criteria andIdBetween(Long value1, Long value2) {
			addCriterion("id between", value1, value2, "id");
			return (Criteria) this;
		}

		public Criteria andIdNotBetween(Long value1, Long value2) {
			addCriterion("id not between", value1, value2, "id");
			return (Criteria) this;
		}

		public Criteria andFeedSourceIdIsNull() {
			addCriterion("feed_source_id is null");
			return (Criteria) this;
		}

		public Criteria andFeedSourceIdIsNotNull() {
			addCriterion("feed_source_id is not null");
			return (Criteria) this;
		}

		public Criteria andFeedSourceIdEqualTo(Long value) {
			addCriterion("feed_source_id =", value, "feedSourceId");
			return (Criteria) this;
		}

		public Criteria andFeedSourceIdNotEqualTo(Long value) {
			addCriterion("feed_source_id <>", value, "feedSourceId");
			return (Criteria) this;
		}

		public Criteria andFeedSourceIdGreaterThan(Long value) {
			addCriterion("feed_source_id >", value, "feedSourceId");
			return (Criteria) this;
		}

		public Criteria andFeedSourceIdGreaterThanOrEqualTo(Long value) {
			addCriterion("feed_source_id >=", value, "feedSourceId");
			return (Criteria) this;
		}

		public Criteria andFeedSourceIdLessThan(Long value) {
			addCriterion("feed_source_id <", value, "feedSourceId");
			return (Criteria) this;
		}

		public Criteria andFeedSourceIdLessThanOrEqualTo(Long value) {
			addCriterion("feed_source_id <=", value, "feedSourceId");
			return (Criteria) this;
		}

		public Criteria andFeedSourceIdIn(List<Long> values) {
			addCriterion("feed_source_id in", values, "feedSourceId");
			return (Criteria) this;
		}

		public Criteria andFeedSourceIdNotIn(List<Long> values) {
			addCriterion("feed_source_id not in", values, "feedSourceId");
			return (Criteria) this;
		}

		public Criteria andFeedSourceIdBetween(Long value1, Long value2) {
			addCriterion("feed_source_id between", value1, value2,
					"feedSourceId");
			return (Criteria) this;
		}

		public Criteria andFeedSourceIdNotBetween(Long value1, Long value2) {
			addCriterion("feed_source_id not between", value1, value2,
					"feedSourceId");
			return (Criteria) this;
		}

		public Criteria andParentFeedIsNull() {
			addCriterion("parent_feed is null");
			return (Criteria) this;
		}

		public Criteria andParentFeedIsNotNull() {
			addCriterion("parent_feed is not null");
			return (Criteria) this;
		}

		public Criteria andParentFeedEqualTo(Boolean value) {
			addCriterion("parent_feed =", value, "parentFeed");
			return (Criteria) this;
		}

		public Criteria andParentFeedNotEqualTo(Boolean value) {
			addCriterion("parent_feed <>", value, "parentFeed");
			return (Criteria) this;
		}

		public Criteria andParentFeedGreaterThan(Boolean value) {
			addCriterion("parent_feed >", value, "parentFeed");
			return (Criteria) this;
		}

		public Criteria andParentFeedGreaterThanOrEqualTo(Boolean value) {
			addCriterion("parent_feed >=", value, "parentFeed");
			return (Criteria) this;
		}

		public Criteria andParentFeedLessThan(Boolean value) {
			addCriterion("parent_feed <", value, "parentFeed");
			return (Criteria) this;
		}

		public Criteria andParentFeedLessThanOrEqualTo(Boolean value) {
			addCriterion("parent_feed <=", value, "parentFeed");
			return (Criteria) this;
		}

		public Criteria andParentFeedIn(List<Boolean> values) {
			addCriterion("parent_feed in", values, "parentFeed");
			return (Criteria) this;
		}

		public Criteria andParentFeedNotIn(List<Boolean> values) {
			addCriterion("parent_feed not in", values, "parentFeed");
			return (Criteria) this;
		}

		public Criteria andParentFeedBetween(Boolean value1, Boolean value2) {
			addCriterion("parent_feed between", value1, value2, "parentFeed");
			return (Criteria) this;
		}

		public Criteria andParentFeedNotBetween(Boolean value1, Boolean value2) {
			addCriterion("parent_feed not between", value1, value2,
					"parentFeed");
			return (Criteria) this;
		}

		public Criteria andUserIdIsNull() {
			addCriterion("user_id is null");
			return (Criteria) this;
		}

		public Criteria andUserIdIsNotNull() {
			addCriterion("user_id is not null");
			return (Criteria) this;
		}

		public Criteria andUserIdEqualTo(Long value) {
			addCriterion("user_id =", value, "userId");
			return (Criteria) this;
		}

		public Criteria andUserIdNotEqualTo(Long value) {
			addCriterion("user_id <>", value, "userId");
			return (Criteria) this;
		}

		public Criteria andUserIdGreaterThan(Long value) {
			addCriterion("user_id >", value, "userId");
			return (Criteria) this;
		}

		public Criteria andUserIdGreaterThanOrEqualTo(Long value) {
			addCriterion("user_id >=", value, "userId");
			return (Criteria) this;
		}

		public Criteria andUserIdLessThan(Long value) {
			addCriterion("user_id <", value, "userId");
			return (Criteria) this;
		}

		public Criteria andUserIdLessThanOrEqualTo(Long value) {
			addCriterion("user_id <=", value, "userId");
			return (Criteria) this;
		}

		public Criteria andUserIdIn(List<Long> values) {
			addCriterion("user_id in", values, "userId");
			return (Criteria) this;
		}

		public Criteria andUserIdNotIn(List<Long> values) {
			addCriterion("user_id not in", values, "userId");
			return (Criteria) this;
		}

		public Criteria andUserIdBetween(Long value1, Long value2) {
			addCriterion("user_id between", value1, value2, "userId");
			return (Criteria) this;
		}

		public Criteria andUserIdNotBetween(Long value1, Long value2) {
			addCriterion("user_id not between", value1, value2, "userId");
			return (Criteria) this;
		}

		public Criteria andAuthorIsNull() {
			addCriterion("author is null");
			return (Criteria) this;
		}

		public Criteria andAuthorIsNotNull() {
			addCriterion("author is not null");
			return (Criteria) this;
		}

		public Criteria andAuthorEqualTo(String value) {
			addCriterion("author =", value, "author");
			return (Criteria) this;
		}

		public Criteria andAuthorNotEqualTo(String value) {
			addCriterion("author <>", value, "author");
			return (Criteria) this;
		}

		public Criteria andAuthorGreaterThan(String value) {
			addCriterion("author >", value, "author");
			return (Criteria) this;
		}

		public Criteria andAuthorGreaterThanOrEqualTo(String value) {
			addCriterion("author >=", value, "author");
			return (Criteria) this;
		}

		public Criteria andAuthorLessThan(String value) {
			addCriterion("author <", value, "author");
			return (Criteria) this;
		}

		public Criteria andAuthorLessThanOrEqualTo(String value) {
			addCriterion("author <=", value, "author");
			return (Criteria) this;
		}

		public Criteria andAuthorLike(String value) {
			addCriterion("author like", value, "author");
			return (Criteria) this;
		}

		public Criteria andAuthorNotLike(String value) {
			addCriterion("author not like", value, "author");
			return (Criteria) this;
		}

		public Criteria andAuthorIn(List<String> values) {
			addCriterion("author in", values, "author");
			return (Criteria) this;
		}

		public Criteria andAuthorNotIn(List<String> values) {
			addCriterion("author not in", values, "author");
			return (Criteria) this;
		}

		public Criteria andAuthorBetween(String value1, String value2) {
			addCriterion("author between", value1, value2, "author");
			return (Criteria) this;
		}

		public Criteria andAuthorNotBetween(String value1, String value2) {
			addCriterion("author not between", value1, value2, "author");
			return (Criteria) this;
		}

		public Criteria andNameIsNull() {
			addCriterion("name is null");
			return (Criteria) this;
		}

		public Criteria andNameIsNotNull() {
			addCriterion("name is not null");
			return (Criteria) this;
		}

		public Criteria andNameEqualTo(String value) {
			addCriterion("name =", value, "name");
			return (Criteria) this;
		}

		public Criteria andNameNotEqualTo(String value) {
			addCriterion("name <>", value, "name");
			return (Criteria) this;
		}

		public Criteria andNameGreaterThan(String value) {
			addCriterion("name >", value, "name");
			return (Criteria) this;
		}

		public Criteria andNameGreaterThanOrEqualTo(String value) {
			addCriterion("name >=", value, "name");
			return (Criteria) this;
		}

		public Criteria andNameLessThan(String value) {
			addCriterion("name <", value, "name");
			return (Criteria) this;
		}

		public Criteria andNameLessThanOrEqualTo(String value) {
			addCriterion("name <=", value, "name");
			return (Criteria) this;
		}

		public Criteria andNameLike(String value) {
			addCriterion("name like", value, "name");
			return (Criteria) this;
		}

		public Criteria andNameNotLike(String value) {
			addCriterion("name not like", value, "name");
			return (Criteria) this;
		}

		public Criteria andNameIn(List<String> values) {
			addCriterion("name in", values, "name");
			return (Criteria) this;
		}

		public Criteria andNameNotIn(List<String> values) {
			addCriterion("name not in", values, "name");
			return (Criteria) this;
		}

		public Criteria andNameBetween(String value1, String value2) {
			addCriterion("name between", value1, value2, "name");
			return (Criteria) this;
		}

		public Criteria andNameNotBetween(String value1, String value2) {
			addCriterion("name not between", value1, value2, "name");
			return (Criteria) this;
		}

		public Criteria andUrlIsNull() {
			addCriterion("url is null");
			return (Criteria) this;
		}

		public Criteria andUrlIsNotNull() {
			addCriterion("url is not null");
			return (Criteria) this;
		}

		public Criteria andUrlEqualTo(String value) {
			addCriterion("url =", value, "url");
			return (Criteria) this;
		}

		public Criteria andUrlNotEqualTo(String value) {
			addCriterion("url <>", value, "url");
			return (Criteria) this;
		}

		public Criteria andUrlGreaterThan(String value) {
			addCriterion("url >", value, "url");
			return (Criteria) this;
		}

		public Criteria andUrlGreaterThanOrEqualTo(String value) {
			addCriterion("url >=", value, "url");
			return (Criteria) this;
		}

		public Criteria andUrlLessThan(String value) {
			addCriterion("url <", value, "url");
			return (Criteria) this;
		}

		public Criteria andUrlLessThanOrEqualTo(String value) {
			addCriterion("url <=", value, "url");
			return (Criteria) this;
		}

		public Criteria andUrlLike(String value) {
			addCriterion("url like", value, "url");
			return (Criteria) this;
		}

		public Criteria andUrlNotLike(String value) {
			addCriterion("url not like", value, "url");
			return (Criteria) this;
		}

		public Criteria andUrlIn(List<String> values) {
			addCriterion("url in", values, "url");
			return (Criteria) this;
		}

		public Criteria andUrlNotIn(List<String> values) {
			addCriterion("url not in", values, "url");
			return (Criteria) this;
		}

		public Criteria andUrlBetween(String value1, String value2) {
			addCriterion("url between", value1, value2, "url");
			return (Criteria) this;
		}

		public Criteria andUrlNotBetween(String value1, String value2) {
			addCriterion("url not between", value1, value2, "url");
			return (Criteria) this;
		}

		public Criteria andPublishedAtIsNull() {
			addCriterion("published_at is null");
			return (Criteria) this;
		}

		public Criteria andPublishedAtIsNotNull() {
			addCriterion("published_at is not null");
			return (Criteria) this;
		}

		public Criteria andPublishedAtEqualTo(Date value) {
			addCriterion("published_at =", value, "publishedAt");
			return (Criteria) this;
		}

		public Criteria andPublishedAtNotEqualTo(Date value) {
			addCriterion("published_at <>", value, "publishedAt");
			return (Criteria) this;
		}

		public Criteria andPublishedAtGreaterThan(Date value) {
			addCriterion("published_at >", value, "publishedAt");
			return (Criteria) this;
		}

		public Criteria andPublishedAtGreaterThanOrEqualTo(Date value) {
			addCriterion("published_at >=", value, "publishedAt");
			return (Criteria) this;
		}

		public Criteria andPublishedAtLessThan(Date value) {
			addCriterion("published_at <", value, "publishedAt");
			return (Criteria) this;
		}

		public Criteria andPublishedAtLessThanOrEqualTo(Date value) {
			addCriterion("published_at <=", value, "publishedAt");
			return (Criteria) this;
		}

		public Criteria andPublishedAtIn(List<Date> values) {
			addCriterion("published_at in", values, "publishedAt");
			return (Criteria) this;
		}

		public Criteria andPublishedAtNotIn(List<Date> values) {
			addCriterion("published_at not in", values, "publishedAt");
			return (Criteria) this;
		}

		public Criteria andPublishedAtBetween(Date value1, Date value2) {
			addCriterion("published_at between", value1, value2, "publishedAt");
			return (Criteria) this;
		}

		public Criteria andPublishedAtNotBetween(Date value1, Date value2) {
			addCriterion("published_at not between", value1, value2,
					"publishedAt");
			return (Criteria) this;
		}

		public Criteria andGuidIsNull() {
			addCriterion("guid is null");
			return (Criteria) this;
		}

		public Criteria andGuidIsNotNull() {
			addCriterion("guid is not null");
			return (Criteria) this;
		}

		public Criteria andGuidEqualTo(String value) {
			addCriterion("guid =", value, "guid");
			return (Criteria) this;
		}

		public Criteria andGuidNotEqualTo(String value) {
			addCriterion("guid <>", value, "guid");
			return (Criteria) this;
		}

		public Criteria andGuidGreaterThan(String value) {
			addCriterion("guid >", value, "guid");
			return (Criteria) this;
		}

		public Criteria andGuidGreaterThanOrEqualTo(String value) {
			addCriterion("guid >=", value, "guid");
			return (Criteria) this;
		}

		public Criteria andGuidLessThan(String value) {
			addCriterion("guid <", value, "guid");
			return (Criteria) this;
		}

		public Criteria andGuidLessThanOrEqualTo(String value) {
			addCriterion("guid <=", value, "guid");
			return (Criteria) this;
		}

		public Criteria andGuidLike(String value) {
			addCriterion("guid like", value, "guid");
			return (Criteria) this;
		}

		public Criteria andGuidNotLike(String value) {
			addCriterion("guid not like", value, "guid");
			return (Criteria) this;
		}

		public Criteria andGuidIn(List<String> values) {
			addCriterion("guid in", values, "guid");
			return (Criteria) this;
		}

		public Criteria andGuidNotIn(List<String> values) {
			addCriterion("guid not in", values, "guid");
			return (Criteria) this;
		}

		public Criteria andGuidBetween(String value1, String value2) {
			addCriterion("guid between", value1, value2, "guid");
			return (Criteria) this;
		}

		public Criteria andGuidNotBetween(String value1, String value2) {
			addCriterion("guid not between", value1, value2, "guid");
			return (Criteria) this;
		}

		public Criteria andCreatedAtIsNull() {
			addCriterion("created_at is null");
			return (Criteria) this;
		}

		public Criteria andCreatedAtIsNotNull() {
			addCriterion("created_at is not null");
			return (Criteria) this;
		}

		public Criteria andCreatedAtEqualTo(Date value) {
			addCriterion("created_at =", value, "createdAt");
			return (Criteria) this;
		}

		public Criteria andCreatedAtNotEqualTo(Date value) {
			addCriterion("created_at <>", value, "createdAt");
			return (Criteria) this;
		}

		public Criteria andCreatedAtGreaterThan(Date value) {
			addCriterion("created_at >", value, "createdAt");
			return (Criteria) this;
		}

		public Criteria andCreatedAtGreaterThanOrEqualTo(Date value) {
			addCriterion("created_at >=", value, "createdAt");
			return (Criteria) this;
		}

		public Criteria andCreatedAtLessThan(Date value) {
			addCriterion("created_at <", value, "createdAt");
			return (Criteria) this;
		}

		public Criteria andCreatedAtLessThanOrEqualTo(Date value) {
			addCriterion("created_at <=", value, "createdAt");
			return (Criteria) this;
		}

		public Criteria andCreatedAtIn(List<Date> values) {
			addCriterion("created_at in", values, "createdAt");
			return (Criteria) this;
		}

		public Criteria andCreatedAtNotIn(List<Date> values) {
			addCriterion("created_at not in", values, "createdAt");
			return (Criteria) this;
		}

		public Criteria andCreatedAtBetween(Date value1, Date value2) {
			addCriterion("created_at between", value1, value2, "createdAt");
			return (Criteria) this;
		}

		public Criteria andCreatedAtNotBetween(Date value1, Date value2) {
			addCriterion("created_at not between", value1, value2, "createdAt");
			return (Criteria) this;
		}

		public Criteria andUpdatedAtIsNull() {
			addCriterion("updated_at is null");
			return (Criteria) this;
		}

		public Criteria andUpdatedAtIsNotNull() {
			addCriterion("updated_at is not null");
			return (Criteria) this;
		}

		public Criteria andUpdatedAtEqualTo(Date value) {
			addCriterion("updated_at =", value, "updatedAt");
			return (Criteria) this;
		}

		public Criteria andUpdatedAtNotEqualTo(Date value) {
			addCriterion("updated_at <>", value, "updatedAt");
			return (Criteria) this;
		}

		public Criteria andUpdatedAtGreaterThan(Date value) {
			addCriterion("updated_at >", value, "updatedAt");
			return (Criteria) this;
		}

		public Criteria andUpdatedAtGreaterThanOrEqualTo(Date value) {
			addCriterion("updated_at >=", value, "updatedAt");
			return (Criteria) this;
		}

		public Criteria andUpdatedAtLessThan(Date value) {
			addCriterion("updated_at <", value, "updatedAt");
			return (Criteria) this;
		}

		public Criteria andUpdatedAtLessThanOrEqualTo(Date value) {
			addCriterion("updated_at <=", value, "updatedAt");
			return (Criteria) this;
		}

		public Criteria andUpdatedAtIn(List<Date> values) {
			addCriterion("updated_at in", values, "updatedAt");
			return (Criteria) this;
		}

		public Criteria andUpdatedAtNotIn(List<Date> values) {
			addCriterion("updated_at not in", values, "updatedAt");
			return (Criteria) this;
		}

		public Criteria andUpdatedAtBetween(Date value1, Date value2) {
			addCriterion("updated_at between", value1, value2, "updatedAt");
			return (Criteria) this;
		}

		public Criteria andUpdatedAtNotBetween(Date value1, Date value2) {
			addCriterion("updated_at not between", value1, value2, "updatedAt");
			return (Criteria) this;
		}

		public Criteria andMainStatusIsNull() {
			addCriterion("main_status is null");
			return (Criteria) this;
		}

		public Criteria andMainStatusIsNotNull() {
			addCriterion("main_status is not null");
			return (Criteria) this;
		}

		public Criteria andMainStatusEqualTo(Boolean value) {
			addCriterion("main_status =", value, "mainStatus");
			return (Criteria) this;
		}

		public Criteria andMainStatusNotEqualTo(Boolean value) {
			addCriterion("main_status <>", value, "mainStatus");
			return (Criteria) this;
		}

		public Criteria andMainStatusGreaterThan(Boolean value) {
			addCriterion("main_status >", value, "mainStatus");
			return (Criteria) this;
		}

		public Criteria andMainStatusGreaterThanOrEqualTo(Boolean value) {
			addCriterion("main_status >=", value, "mainStatus");
			return (Criteria) this;
		}

		public Criteria andMainStatusLessThan(Boolean value) {
			addCriterion("main_status <", value, "mainStatus");
			return (Criteria) this;
		}

		public Criteria andMainStatusLessThanOrEqualTo(Boolean value) {
			addCriterion("main_status <=", value, "mainStatus");
			return (Criteria) this;
		}

		public Criteria andMainStatusIn(List<Boolean> values) {
			addCriterion("main_status in", values, "mainStatus");
			return (Criteria) this;
		}

		public Criteria andMainStatusNotIn(List<Boolean> values) {
			addCriterion("main_status not in", values, "mainStatus");
			return (Criteria) this;
		}

		public Criteria andMainStatusBetween(Boolean value1, Boolean value2) {
			addCriterion("main_status between", value1, value2, "mainStatus");
			return (Criteria) this;
		}

		public Criteria andMainStatusNotBetween(Boolean value1, Boolean value2) {
			addCriterion("main_status not between", value1, value2,
					"mainStatus");
			return (Criteria) this;
		}

		public Criteria andStatusIsNull() {
			addCriterion("status is null");
			return (Criteria) this;
		}

		public Criteria andStatusIsNotNull() {
			addCriterion("status is not null");
			return (Criteria) this;
		}

		public Criteria andStatusEqualTo(Integer value) {
			addCriterion("status =", value, "status");
			return (Criteria) this;
		}

		public Criteria andStatusNotEqualTo(Integer value) {
			addCriterion("status <>", value, "status");
			return (Criteria) this;
		}

		public Criteria andStatusGreaterThan(Integer value) {
			addCriterion("status >", value, "status");
			return (Criteria) this;
		}

		public Criteria andStatusGreaterThanOrEqualTo(Integer value) {
			addCriterion("status >=", value, "status");
			return (Criteria) this;
		}

		public Criteria andStatusLessThan(Integer value) {
			addCriterion("status <", value, "status");
			return (Criteria) this;
		}

		public Criteria andStatusLessThanOrEqualTo(Integer value) {
			addCriterion("status <=", value, "status");
			return (Criteria) this;
		}

		public Criteria andStatusIn(List<Integer> values) {
			addCriterion("status in", values, "status");
			return (Criteria) this;
		}

		public Criteria andStatusNotIn(List<Integer> values) {
			addCriterion("status not in", values, "status");
			return (Criteria) this;
		}

		public Criteria andStatusBetween(Integer value1, Integer value2) {
			addCriterion("status between", value1, value2, "status");
			return (Criteria) this;
		}

		public Criteria andStatusNotBetween(Integer value1, Integer value2) {
			addCriterion("status not between", value1, value2, "status");
			return (Criteria) this;
		}

		public Criteria andReplyIdIsNull() {
			addCriterion("reply_id is null");
			return (Criteria) this;
		}

		public Criteria andReplyIdIsNotNull() {
			addCriterion("reply_id is not null");
			return (Criteria) this;
		}

		public Criteria andReplyIdEqualTo(Long value) {
			addCriterion("reply_id =", value, "replyId");
			return (Criteria) this;
		}

		public Criteria andReplyIdNotEqualTo(Long value) {
			addCriterion("reply_id <>", value, "replyId");
			return (Criteria) this;
		}

		public Criteria andReplyIdGreaterThan(Long value) {
			addCriterion("reply_id >", value, "replyId");
			return (Criteria) this;
		}

		public Criteria andReplyIdGreaterThanOrEqualTo(Long value) {
			addCriterion("reply_id >=", value, "replyId");
			return (Criteria) this;
		}

		public Criteria andReplyIdLessThan(Long value) {
			addCriterion("reply_id <", value, "replyId");
			return (Criteria) this;
		}

		public Criteria andReplyIdLessThanOrEqualTo(Long value) {
			addCriterion("reply_id <=", value, "replyId");
			return (Criteria) this;
		}

		public Criteria andReplyIdIn(List<Long> values) {
			addCriterion("reply_id in", values, "replyId");
			return (Criteria) this;
		}

		public Criteria andReplyIdNotIn(List<Long> values) {
			addCriterion("reply_id not in", values, "replyId");
			return (Criteria) this;
		}

		public Criteria andReplyIdBetween(Long value1, Long value2) {
			addCriterion("reply_id between", value1, value2, "replyId");
			return (Criteria) this;
		}

		public Criteria andReplyIdNotBetween(Long value1, Long value2) {
			addCriterion("reply_id not between", value1, value2, "replyId");
			return (Criteria) this;
		}

		public Criteria andAssignToIsNull() {
			addCriterion("assign_to is null");
			return (Criteria) this;
		}

		public Criteria andAssignToIsNotNull() {
			addCriterion("assign_to is not null");
			return (Criteria) this;
		}

		public Criteria andAssignToEqualTo(Long value) {
			addCriterion("assign_to =", value, "assignTo");
			return (Criteria) this;
		}

		public Criteria andAssignToNotEqualTo(Long value) {
			addCriterion("assign_to <>", value, "assignTo");
			return (Criteria) this;
		}

		public Criteria andAssignToGreaterThan(Long value) {
			addCriterion("assign_to >", value, "assignTo");
			return (Criteria) this;
		}

		public Criteria andAssignToGreaterThanOrEqualTo(Long value) {
			addCriterion("assign_to >=", value, "assignTo");
			return (Criteria) this;
		}

		public Criteria andAssignToLessThan(Long value) {
			addCriterion("assign_to <", value, "assignTo");
			return (Criteria) this;
		}

		public Criteria andAssignToLessThanOrEqualTo(Long value) {
			addCriterion("assign_to <=", value, "assignTo");
			return (Criteria) this;
		}

		public Criteria andAssignToIn(List<Long> values) {
			addCriterion("assign_to in", values, "assignTo");
			return (Criteria) this;
		}

		public Criteria andAssignToNotIn(List<Long> values) {
			addCriterion("assign_to not in", values, "assignTo");
			return (Criteria) this;
		}

		public Criteria andAssignToBetween(Long value1, Long value2) {
			addCriterion("assign_to between", value1, value2, "assignTo");
			return (Criteria) this;
		}

		public Criteria andAssignToNotBetween(Long value1, Long value2) {
			addCriterion("assign_to not between", value1, value2, "assignTo");
			return (Criteria) this;
		}

		public Criteria andAssignToDeptIsNull() {
			addCriterion("assign_to_dept is null");
			return (Criteria) this;
		}

		public Criteria andAssignToDeptIsNotNull() {
			addCriterion("assign_to_dept is not null");
			return (Criteria) this;
		}

		public Criteria andAssignToDeptEqualTo(Long value) {
			addCriterion("assign_to_dept =", value, "assignToDept");
			return (Criteria) this;
		}

		public Criteria andAssignToDeptNotEqualTo(Long value) {
			addCriterion("assign_to_dept <>", value, "assignToDept");
			return (Criteria) this;
		}

		public Criteria andAssignToDeptGreaterThan(Long value) {
			addCriterion("assign_to_dept >", value, "assignToDept");
			return (Criteria) this;
		}

		public Criteria andAssignToDeptGreaterThanOrEqualTo(Long value) {
			addCriterion("assign_to_dept >=", value, "assignToDept");
			return (Criteria) this;
		}

		public Criteria andAssignToDeptLessThan(Long value) {
			addCriterion("assign_to_dept <", value, "assignToDept");
			return (Criteria) this;
		}

		public Criteria andAssignToDeptLessThanOrEqualTo(Long value) {
			addCriterion("assign_to_dept <=", value, "assignToDept");
			return (Criteria) this;
		}

		public Criteria andAssignToDeptIn(List<Long> values) {
			addCriterion("assign_to_dept in", values, "assignToDept");
			return (Criteria) this;
		}

		public Criteria andAssignToDeptNotIn(List<Long> values) {
			addCriterion("assign_to_dept not in", values, "assignToDept");
			return (Criteria) this;
		}

		public Criteria andAssignToDeptBetween(Long value1, Long value2) {
			addCriterion("assign_to_dept between", value1, value2,
					"assignToDept");
			return (Criteria) this;
		}

		public Criteria andAssignToDeptNotBetween(Long value1, Long value2) {
			addCriterion("assign_to_dept not between", value1, value2,
					"assignToDept");
			return (Criteria) this;
		}

		public Criteria andLastViewDateIsNull() {
			addCriterion("last_view_date is null");
			return (Criteria) this;
		}

		public Criteria andLastViewDateIsNotNull() {
			addCriterion("last_view_date is not null");
			return (Criteria) this;
		}

		public Criteria andLastViewDateEqualTo(Date value) {
			addCriterion("last_view_date =", value, "lastViewDate");
			return (Criteria) this;
		}

		public Criteria andLastViewDateNotEqualTo(Date value) {
			addCriterion("last_view_date <>", value, "lastViewDate");
			return (Criteria) this;
		}

		public Criteria andLastViewDateGreaterThan(Date value) {
			addCriterion("last_view_date >", value, "lastViewDate");
			return (Criteria) this;
		}

		public Criteria andLastViewDateGreaterThanOrEqualTo(Date value) {
			addCriterion("last_view_date >=", value, "lastViewDate");
			return (Criteria) this;
		}

		public Criteria andLastViewDateLessThan(Date value) {
			addCriterion("last_view_date <", value, "lastViewDate");
			return (Criteria) this;
		}

		public Criteria andLastViewDateLessThanOrEqualTo(Date value) {
			addCriterion("last_view_date <=", value, "lastViewDate");
			return (Criteria) this;
		}

		public Criteria andLastViewDateIn(List<Date> values) {
			addCriterion("last_view_date in", values, "lastViewDate");
			return (Criteria) this;
		}

		public Criteria andLastViewDateNotIn(List<Date> values) {
			addCriterion("last_view_date not in", values, "lastViewDate");
			return (Criteria) this;
		}

		public Criteria andLastViewDateBetween(Date value1, Date value2) {
			addCriterion("last_view_date between", value1, value2,
					"lastViewDate");
			return (Criteria) this;
		}

		public Criteria andLastViewDateNotBetween(Date value1, Date value2) {
			addCriterion("last_view_date not between", value1, value2,
					"lastViewDate");
			return (Criteria) this;
		}

		public Criteria andDeadlineIsNull() {
			addCriterion("deadline is null");
			return (Criteria) this;
		}

		public Criteria andDeadlineIsNotNull() {
			addCriterion("deadline is not null");
			return (Criteria) this;
		}

		public Criteria andDeadlineEqualTo(Date value) {
			addCriterion("deadline =", value, "deadline");
			return (Criteria) this;
		}

		public Criteria andDeadlineNotEqualTo(Date value) {
			addCriterion("deadline <>", value, "deadline");
			return (Criteria) this;
		}

		public Criteria andDeadlineGreaterThan(Date value) {
			addCriterion("deadline >", value, "deadline");
			return (Criteria) this;
		}

		public Criteria andDeadlineGreaterThanOrEqualTo(Date value) {
			addCriterion("deadline >=", value, "deadline");
			return (Criteria) this;
		}

		public Criteria andDeadlineLessThan(Date value) {
			addCriterion("deadline <", value, "deadline");
			return (Criteria) this;
		}

		public Criteria andDeadlineLessThanOrEqualTo(Date value) {
			addCriterion("deadline <=", value, "deadline");
			return (Criteria) this;
		}

		public Criteria andDeadlineIn(List<Date> values) {
			addCriterion("deadline in", values, "deadline");
			return (Criteria) this;
		}

		public Criteria andDeadlineNotIn(List<Date> values) {
			addCriterion("deadline not in", values, "deadline");
			return (Criteria) this;
		}

		public Criteria andDeadlineBetween(Date value1, Date value2) {
			addCriterion("deadline between", value1, value2, "deadline");
			return (Criteria) this;
		}

		public Criteria andDeadlineNotBetween(Date value1, Date value2) {
			addCriterion("deadline not between", value1, value2, "deadline");
			return (Criteria) this;
		}

		public Criteria andFollowerIsNull() {
			addCriterion("follower is null");
			return (Criteria) this;
		}

		public Criteria andFollowerIsNotNull() {
			addCriterion("follower is not null");
			return (Criteria) this;
		}

		public Criteria andFollowerEqualTo(Integer value) {
			addCriterion("follower =", value, "follower");
			return (Criteria) this;
		}

		public Criteria andFollowerNotEqualTo(Integer value) {
			addCriterion("follower <>", value, "follower");
			return (Criteria) this;
		}

		public Criteria andFollowerGreaterThan(Integer value) {
			addCriterion("follower >", value, "follower");
			return (Criteria) this;
		}

		public Criteria andFollowerGreaterThanOrEqualTo(Integer value) {
			addCriterion("follower >=", value, "follower");
			return (Criteria) this;
		}

		public Criteria andFollowerLessThan(Integer value) {
			addCriterion("follower <", value, "follower");
			return (Criteria) this;
		}

		public Criteria andFollowerLessThanOrEqualTo(Integer value) {
			addCriterion("follower <=", value, "follower");
			return (Criteria) this;
		}

		public Criteria andFollowerIn(List<Integer> values) {
			addCriterion("follower in", values, "follower");
			return (Criteria) this;
		}

		public Criteria andFollowerNotIn(List<Integer> values) {
			addCriterion("follower not in", values, "follower");
			return (Criteria) this;
		}

		public Criteria andFollowerBetween(Integer value1, Integer value2) {
			addCriterion("follower between", value1, value2, "follower");
			return (Criteria) this;
		}

		public Criteria andFollowerNotBetween(Integer value1, Integer value2) {
			addCriterion("follower not between", value1, value2, "follower");
			return (Criteria) this;
		}

		public Criteria andUrgentStatusIsNull() {
			addCriterion("urgent_status is null");
			return (Criteria) this;
		}

		public Criteria andUrgentStatusIsNotNull() {
			addCriterion("urgent_status is not null");
			return (Criteria) this;
		}

		public Criteria andUrgentStatusEqualTo(Boolean value) {
			addCriterion("urgent_status =", value, "urgentStatus");
			return (Criteria) this;
		}

		public Criteria andUrgentStatusNotEqualTo(Boolean value) {
			addCriterion("urgent_status <>", value, "urgentStatus");
			return (Criteria) this;
		}

		public Criteria andUrgentStatusGreaterThan(Boolean value) {
			addCriterion("urgent_status >", value, "urgentStatus");
			return (Criteria) this;
		}

		public Criteria andUrgentStatusGreaterThanOrEqualTo(Boolean value) {
			addCriterion("urgent_status >=", value, "urgentStatus");
			return (Criteria) this;
		}

		public Criteria andUrgentStatusLessThan(Boolean value) {
			addCriterion("urgent_status <", value, "urgentStatus");
			return (Criteria) this;
		}

		public Criteria andUrgentStatusLessThanOrEqualTo(Boolean value) {
			addCriterion("urgent_status <=", value, "urgentStatus");
			return (Criteria) this;
		}

		public Criteria andUrgentStatusIn(List<Boolean> values) {
			addCriterion("urgent_status in", values, "urgentStatus");
			return (Criteria) this;
		}

		public Criteria andUrgentStatusNotIn(List<Boolean> values) {
			addCriterion("urgent_status not in", values, "urgentStatus");
			return (Criteria) this;
		}

		public Criteria andUrgentStatusBetween(Boolean value1, Boolean value2) {
			addCriterion("urgent_status between", value1, value2,
					"urgentStatus");
			return (Criteria) this;
		}

		public Criteria andUrgentStatusNotBetween(Boolean value1, Boolean value2) {
			addCriterion("urgent_status not between", value1, value2,
					"urgentStatus");
			return (Criteria) this;
		}

		public Criteria andViewerIsNull() {
			addCriterion("viewer is null");
			return (Criteria) this;
		}

		public Criteria andViewerIsNotNull() {
			addCriterion("viewer is not null");
			return (Criteria) this;
		}

		public Criteria andViewerEqualTo(Integer value) {
			addCriterion("viewer =", value, "viewer");
			return (Criteria) this;
		}

		public Criteria andViewerNotEqualTo(Integer value) {
			addCriterion("viewer <>", value, "viewer");
			return (Criteria) this;
		}

		public Criteria andViewerGreaterThan(Integer value) {
			addCriterion("viewer >", value, "viewer");
			return (Criteria) this;
		}

		public Criteria andViewerGreaterThanOrEqualTo(Integer value) {
			addCriterion("viewer >=", value, "viewer");
			return (Criteria) this;
		}

		public Criteria andViewerLessThan(Integer value) {
			addCriterion("viewer <", value, "viewer");
			return (Criteria) this;
		}

		public Criteria andViewerLessThanOrEqualTo(Integer value) {
			addCriterion("viewer <=", value, "viewer");
			return (Criteria) this;
		}

		public Criteria andViewerIn(List<Integer> values) {
			addCriterion("viewer in", values, "viewer");
			return (Criteria) this;
		}

		public Criteria andViewerNotIn(List<Integer> values) {
			addCriterion("viewer not in", values, "viewer");
			return (Criteria) this;
		}

		public Criteria andViewerBetween(Integer value1, Integer value2) {
			addCriterion("viewer between", value1, value2, "viewer");
			return (Criteria) this;
		}

		public Criteria andViewerNotBetween(Integer value1, Integer value2) {
			addCriterion("viewer not between", value1, value2, "viewer");
			return (Criteria) this;
		}

		public Criteria andFeedTypeIsNull() {
			addCriterion("feed_type is null");
			return (Criteria) this;
		}

		public Criteria andFeedTypeIsNotNull() {
			addCriterion("feed_type is not null");
			return (Criteria) this;
		}

		public Criteria andFeedTypeEqualTo(Integer value) {
			addCriterion("feed_type =", value, "feedType");
			return (Criteria) this;
		}

		public Criteria andFeedTypeNotEqualTo(Integer value) {
			addCriterion("feed_type <>", value, "feedType");
			return (Criteria) this;
		}

		public Criteria andFeedTypeGreaterThan(Integer value) {
			addCriterion("feed_type >", value, "feedType");
			return (Criteria) this;
		}

		public Criteria andFeedTypeGreaterThanOrEqualTo(Integer value) {
			addCriterion("feed_type >=", value, "feedType");
			return (Criteria) this;
		}

		public Criteria andFeedTypeLessThan(Integer value) {
			addCriterion("feed_type <", value, "feedType");
			return (Criteria) this;
		}

		public Criteria andFeedTypeLessThanOrEqualTo(Integer value) {
			addCriterion("feed_type <=", value, "feedType");
			return (Criteria) this;
		}

		public Criteria andFeedTypeIn(List<Integer> values) {
			addCriterion("feed_type in", values, "feedType");
			return (Criteria) this;
		}

		public Criteria andFeedTypeNotIn(List<Integer> values) {
			addCriterion("feed_type not in", values, "feedType");
			return (Criteria) this;
		}

		public Criteria andFeedTypeBetween(Integer value1, Integer value2) {
			addCriterion("feed_type between", value1, value2, "feedType");
			return (Criteria) this;
		}

		public Criteria andFeedTypeNotBetween(Integer value1, Integer value2) {
			addCriterion("feed_type not between", value1, value2, "feedType");
			return (Criteria) this;
		}

		public Criteria andUpdatedByIsNull() {
			addCriterion("updated_by is null");
			return (Criteria) this;
		}

		public Criteria andUpdatedByIsNotNull() {
			addCriterion("updated_by is not null");
			return (Criteria) this;
		}

		public Criteria andUpdatedByEqualTo(Long value) {
			addCriterion("updated_by =", value, "updatedBy");
			return (Criteria) this;
		}

		public Criteria andUpdatedByNotEqualTo(Long value) {
			addCriterion("updated_by <>", value, "updatedBy");
			return (Criteria) this;
		}

		public Criteria andUpdatedByGreaterThan(Long value) {
			addCriterion("updated_by >", value, "updatedBy");
			return (Criteria) this;
		}

		public Criteria andUpdatedByGreaterThanOrEqualTo(Long value) {
			addCriterion("updated_by >=", value, "updatedBy");
			return (Criteria) this;
		}

		public Criteria andUpdatedByLessThan(Long value) {
			addCriterion("updated_by <", value, "updatedBy");
			return (Criteria) this;
		}

		public Criteria andUpdatedByLessThanOrEqualTo(Long value) {
			addCriterion("updated_by <=", value, "updatedBy");
			return (Criteria) this;
		}

		public Criteria andUpdatedByIn(List<Long> values) {
			addCriterion("updated_by in", values, "updatedBy");
			return (Criteria) this;
		}

		public Criteria andUpdatedByNotIn(List<Long> values) {
			addCriterion("updated_by not in", values, "updatedBy");
			return (Criteria) this;
		}

		public Criteria andUpdatedByBetween(Long value1, Long value2) {
			addCriterion("updated_by between", value1, value2, "updatedBy");
			return (Criteria) this;
		}

		public Criteria andUpdatedByNotBetween(Long value1, Long value2) {
			addCriterion("updated_by not between", value1, value2, "updatedBy");
			return (Criteria) this;
		}
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table feed_entries
	 * @mbggenerated  Tue Oct 29 13:42:10 GMT 2013
	 */
	public static class Criterion {
		private String condition;
		private Object value;
		private Object secondValue;
		private boolean noValue;
		private boolean singleValue;
		private boolean betweenValue;
		private boolean listValue;
		private String typeHandler;

		public String getCondition() {
			return condition;
		}

		public Object getValue() {
			return value;
		}

		public Object getSecondValue() {
			return secondValue;
		}

		public boolean isNoValue() {
			return noValue;
		}

		public boolean isSingleValue() {
			return singleValue;
		}

		public boolean isBetweenValue() {
			return betweenValue;
		}

		public boolean isListValue() {
			return listValue;
		}

		public String getTypeHandler() {
			return typeHandler;
		}

		protected Criterion(String condition) {
			super();
			this.condition = condition;
			this.typeHandler = null;
			this.noValue = true;
		}

		protected Criterion(String condition, Object value, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.typeHandler = typeHandler;
			if (value instanceof List<?>) {
				this.listValue = true;
			} else {
				this.singleValue = true;
			}
		}

		protected Criterion(String condition, Object value) {
			this(condition, value, null);
		}

		protected Criterion(String condition, Object value, Object secondValue,
				String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.secondValue = secondValue;
			this.typeHandler = typeHandler;
			this.betweenValue = true;
		}

		protected Criterion(String condition, Object value, Object secondValue) {
			this(condition, value, secondValue, null);
		}
	}

	/**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table feed_entries
     *
     * @mbggenerated do_not_delete_during_merge Fri Aug 24 15:07:42 BST 2012
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }
}