package com.jemmmedia.organise.mybatis.db.mybatis.model;

public class FeedTypes {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column feed_types.id
     *
     * @mbggenerated Fri Sep 21 12:06:28 BST 2012
     */
    private Byte id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column feed_types.name
     *
     * @mbggenerated Fri Sep 21 12:06:28 BST 2012
     */
    private String name;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column feed_types.id
     *
     * @return the value of feed_types.id
     *
     * @mbggenerated Fri Sep 21 12:06:28 BST 2012
     */
    public Byte getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column feed_types.id
     *
     * @param id the value for feed_types.id
     *
     * @mbggenerated Fri Sep 21 12:06:28 BST 2012
     */
    public void setId(Byte id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column feed_types.name
     *
     * @return the value of feed_types.name
     *
     * @mbggenerated Fri Sep 21 12:06:28 BST 2012
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column feed_types.name
     *
     * @param name the value for feed_types.name
     *
     * @mbggenerated Fri Sep 21 12:06:28 BST 2012
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }
}