package com.jemmmedia.organise.mybatis.db.mybatis.model;

public class FeedEntryWithChild {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column feed_entry_child.parent_id
     *
     * @mbggenerated Mon Aug 27 07:55:02 BST 2012
     */
    private Long parentId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column feed_entry_child.feed_id
     *
     * @mbggenerated Mon Aug 27 07:55:02 BST 2012
     */
    private Long feedId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column feed_entry_child.parent_id
     *
     * @return the value of feed_entry_child.parent_id
     *
     * @mbggenerated Mon Aug 27 07:55:02 BST 2012
     */
    public Long getParentId() {
        return parentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column feed_entry_child.parent_id
     *
     * @param parentId the value for feed_entry_child.parent_id
     *
     * @mbggenerated Mon Aug 27 07:55:02 BST 2012
     */
    public void setParentId(Long parentId) {
        this.parentId = parentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column feed_entry_child.feed_id
     *
     * @return the value of feed_entry_child.feed_id
     *
     * @mbggenerated Mon Aug 27 07:55:02 BST 2012
     */
    public Long getFeedId() {
        return feedId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column feed_entry_child.feed_id
     *
     * @param feedId the value for feed_entry_child.feed_id
     *
     * @mbggenerated Mon Aug 27 07:55:02 BST 2012
     */
    public void setFeedId(Long feedId) {
        this.feedId = feedId;
    }
}