package com.jemmmedia.organise.mybatis.db.mybatis.model;

import java.util.Date;

public class FeedEntry extends BaseModel {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column feed_entries.feed_source_id
	 * @mbggenerated  Tue Oct 29 13:42:10 GMT 2013
	 */
	private Long feedSourceId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column feed_entries.parent_feed
	 * @mbggenerated  Tue Oct 29 13:42:10 GMT 2013
	 */
	private Boolean parentFeed;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column feed_entries.user_id
	 * @mbggenerated  Tue Oct 29 13:42:10 GMT 2013
	 */
	private Long userId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column feed_entries.author
	 * @mbggenerated  Tue Oct 29 13:42:10 GMT 2013
	 */
	private String author;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column feed_entries.name
	 * @mbggenerated  Tue Oct 29 13:42:10 GMT 2013
	 */
	private String name;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column feed_entries.url
	 * @mbggenerated  Tue Oct 29 13:42:10 GMT 2013
	 */
	private String url;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column feed_entries.published_at
	 * @mbggenerated  Tue Oct 29 13:42:10 GMT 2013
	 */
	private Date publishedAt;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column feed_entries.guid
	 * @mbggenerated  Tue Oct 29 13:42:10 GMT 2013
	 */
	private String guid;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column feed_entries.main_status
	 * @mbggenerated  Tue Oct 29 13:42:10 GMT 2013
	 */
	private Boolean mainStatus;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column feed_entries.status
	 * @mbggenerated  Tue Oct 29 13:42:10 GMT 2013
	 */
	private Integer status;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column feed_entries.reply_id
	 * @mbggenerated  Tue Oct 29 13:42:10 GMT 2013
	 */
	private Long replyId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column feed_entries.assign_to
	 * @mbggenerated  Tue Oct 29 13:42:10 GMT 2013
	 */
	private Long assignTo;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column feed_entries.assign_to_dept
	 * @mbggenerated  Tue Oct 29 13:42:10 GMT 2013
	 */
	private Long assignToDept;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column feed_entries.last_view_date
	 * @mbggenerated  Tue Oct 29 13:42:10 GMT 2013
	 */
	private Date lastViewDate;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column feed_entries.deadline
	 * @mbggenerated  Tue Oct 29 13:42:10 GMT 2013
	 */
	private Date deadline;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column feed_entries.follower
	 * @mbggenerated  Tue Oct 29 13:42:10 GMT 2013
	 */
	private Integer follower;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column feed_entries.urgent_status
	 * @mbggenerated  Tue Oct 29 13:42:10 GMT 2013
	 */
	private Boolean urgentStatus;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column feed_entries.viewer
	 * @mbggenerated  Tue Oct 29 13:42:10 GMT 2013
	 */
	private Integer viewer;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column feed_entries.feed_type
	 * @mbggenerated  Tue Oct 29 13:42:10 GMT 2013
	 */
	private Integer feedType;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column feed_entries.updated_by
	 * @mbggenerated  Tue Oct 29 13:42:10 GMT 2013
	 */
	private Long updatedBy;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column feed_entries.summary
	 * @mbggenerated  Tue Oct 29 13:42:10 GMT 2013
	 */
	private String summary;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column feed_entries.feed_source_id
	 * @return  the value of feed_entries.feed_source_id
	 * @mbggenerated  Tue Oct 29 13:42:10 GMT 2013
	 */
	public Long getFeedSourceId() {
		return feedSourceId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column feed_entries.feed_source_id
	 * @param feedSourceId  the value for feed_entries.feed_source_id
	 * @mbggenerated  Tue Oct 29 13:42:10 GMT 2013
	 */
	public void setFeedSourceId(Long feedSourceId) {
		this.feedSourceId = feedSourceId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column feed_entries.parent_feed
	 * @return  the value of feed_entries.parent_feed
	 * @mbggenerated  Tue Oct 29 13:42:10 GMT 2013
	 */
	public Boolean getParentFeed() {
		return parentFeed;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column feed_entries.parent_feed
	 * @param parentFeed  the value for feed_entries.parent_feed
	 * @mbggenerated  Tue Oct 29 13:42:10 GMT 2013
	 */
	public void setParentFeed(Boolean parentFeed) {
		this.parentFeed = parentFeed;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column feed_entries.user_id
	 * @return  the value of feed_entries.user_id
	 * @mbggenerated  Tue Oct 29 13:42:10 GMT 2013
	 */
	public Long getUserId() {
		return userId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column feed_entries.user_id
	 * @param userId  the value for feed_entries.user_id
	 * @mbggenerated  Tue Oct 29 13:42:10 GMT 2013
	 */
	public void setUserId(Long userId) {
		this.userId = userId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column feed_entries.author
	 * @return  the value of feed_entries.author
	 * @mbggenerated  Tue Oct 29 13:42:10 GMT 2013
	 */
	public String getAuthor() {
		return author;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column feed_entries.author
	 * @param author  the value for feed_entries.author
	 * @mbggenerated  Tue Oct 29 13:42:10 GMT 2013
	 */
	public void setAuthor(String author) {
		this.author = author == null ? null : author.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column feed_entries.name
	 * @return  the value of feed_entries.name
	 * @mbggenerated  Tue Oct 29 13:42:10 GMT 2013
	 */
	public String getName() {
		return name;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column feed_entries.name
	 * @param name  the value for feed_entries.name
	 * @mbggenerated  Tue Oct 29 13:42:10 GMT 2013
	 */
	public void setName(String name) {
		this.name = name == null ? null : name.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column feed_entries.url
	 * @return  the value of feed_entries.url
	 * @mbggenerated  Tue Oct 29 13:42:10 GMT 2013
	 */
	public String getUrl() {
		return url;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column feed_entries.url
	 * @param url  the value for feed_entries.url
	 * @mbggenerated  Tue Oct 29 13:42:10 GMT 2013
	 */
	public void setUrl(String url) {
		this.url = url == null ? null : url.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column feed_entries.published_at
	 * @return  the value of feed_entries.published_at
	 * @mbggenerated  Tue Oct 29 13:42:10 GMT 2013
	 */
	public Date getPublishedAt() {
		return publishedAt;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column feed_entries.published_at
	 * @param publishedAt  the value for feed_entries.published_at
	 * @mbggenerated  Tue Oct 29 13:42:10 GMT 2013
	 */
	public void setPublishedAt(Date publishedAt) {
		this.publishedAt = publishedAt;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column feed_entries.guid
	 * @return  the value of feed_entries.guid
	 * @mbggenerated  Tue Oct 29 13:42:10 GMT 2013
	 */
	public String getGuid() {
		return guid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column feed_entries.guid
	 * @param guid  the value for feed_entries.guid
	 * @mbggenerated  Tue Oct 29 13:42:10 GMT 2013
	 */
	public void setGuid(String guid) {
		this.guid = guid == null ? null : guid.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column feed_entries.main_status
	 * @return  the value of feed_entries.main_status
	 * @mbggenerated  Tue Oct 29 13:42:10 GMT 2013
	 */
	public Boolean getMainStatus() {
		return mainStatus;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column feed_entries.main_status
	 * @param mainStatus  the value for feed_entries.main_status
	 * @mbggenerated  Tue Oct 29 13:42:10 GMT 2013
	 */
	public void setMainStatus(Boolean mainStatus) {
		this.mainStatus = mainStatus;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column feed_entries.status
	 * @return  the value of feed_entries.status
	 * @mbggenerated  Tue Oct 29 13:42:10 GMT 2013
	 */
	public Integer getStatus() {
		return status;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column feed_entries.status
	 * @param status  the value for feed_entries.status
	 * @mbggenerated  Tue Oct 29 13:42:10 GMT 2013
	 */
	public void setStatus(Integer status) {
		this.status = status;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column feed_entries.reply_id
	 * @return  the value of feed_entries.reply_id
	 * @mbggenerated  Tue Oct 29 13:42:10 GMT 2013
	 */
	public Long getReplyId() {
		return replyId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column feed_entries.reply_id
	 * @param replyId  the value for feed_entries.reply_id
	 * @mbggenerated  Tue Oct 29 13:42:10 GMT 2013
	 */
	public void setReplyId(Long replyId) {
		this.replyId = replyId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column feed_entries.assign_to
	 * @return  the value of feed_entries.assign_to
	 * @mbggenerated  Tue Oct 29 13:42:10 GMT 2013
	 */
	public Long getAssignTo() {
		return assignTo;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column feed_entries.assign_to
	 * @param assignTo  the value for feed_entries.assign_to
	 * @mbggenerated  Tue Oct 29 13:42:10 GMT 2013
	 */
	public void setAssignTo(Long assignTo) {
		this.assignTo = assignTo;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column feed_entries.assign_to_dept
	 * @return  the value of feed_entries.assign_to_dept
	 * @mbggenerated  Tue Oct 29 13:42:10 GMT 2013
	 */
	public Long getAssignToDept() {
		return assignToDept;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column feed_entries.assign_to_dept
	 * @param assignToDept  the value for feed_entries.assign_to_dept
	 * @mbggenerated  Tue Oct 29 13:42:10 GMT 2013
	 */
	public void setAssignToDept(Long assignToDept) {
		this.assignToDept = assignToDept;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column feed_entries.last_view_date
	 * @return  the value of feed_entries.last_view_date
	 * @mbggenerated  Tue Oct 29 13:42:10 GMT 2013
	 */
	public Date getLastViewDate() {
		return lastViewDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column feed_entries.last_view_date
	 * @param lastViewDate  the value for feed_entries.last_view_date
	 * @mbggenerated  Tue Oct 29 13:42:10 GMT 2013
	 */
	public void setLastViewDate(Date lastViewDate) {
		this.lastViewDate = lastViewDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column feed_entries.deadline
	 * @return  the value of feed_entries.deadline
	 * @mbggenerated  Tue Oct 29 13:42:10 GMT 2013
	 */
	public Date getDeadline() {
		return deadline;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column feed_entries.deadline
	 * @param deadline  the value for feed_entries.deadline
	 * @mbggenerated  Tue Oct 29 13:42:10 GMT 2013
	 */
	public void setDeadline(Date deadline) {
		this.deadline = deadline;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column feed_entries.follower
	 * @return  the value of feed_entries.follower
	 * @mbggenerated  Tue Oct 29 13:42:10 GMT 2013
	 */
	public Integer getFollower() {
		return follower;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column feed_entries.follower
	 * @param follower  the value for feed_entries.follower
	 * @mbggenerated  Tue Oct 29 13:42:10 GMT 2013
	 */
	public void setFollower(Integer follower) {
		this.follower = follower;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column feed_entries.urgent_status
	 * @return  the value of feed_entries.urgent_status
	 * @mbggenerated  Tue Oct 29 13:42:10 GMT 2013
	 */
	public Boolean getUrgentStatus() {
		return urgentStatus;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column feed_entries.urgent_status
	 * @param urgentStatus  the value for feed_entries.urgent_status
	 * @mbggenerated  Tue Oct 29 13:42:10 GMT 2013
	 */
	public void setUrgentStatus(Boolean urgentStatus) {
		this.urgentStatus = urgentStatus;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column feed_entries.viewer
	 * @return  the value of feed_entries.viewer
	 * @mbggenerated  Tue Oct 29 13:42:10 GMT 2013
	 */
	public Integer getViewer() {
		return viewer;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column feed_entries.viewer
	 * @param viewer  the value for feed_entries.viewer
	 * @mbggenerated  Tue Oct 29 13:42:10 GMT 2013
	 */
	public void setViewer(Integer viewer) {
		this.viewer = viewer;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column feed_entries.feed_type
	 * @return  the value of feed_entries.feed_type
	 * @mbggenerated  Tue Oct 29 13:42:10 GMT 2013
	 */
	public Integer getFeedType() {
		return feedType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column feed_entries.feed_type
	 * @param feedType  the value for feed_entries.feed_type
	 * @mbggenerated  Tue Oct 29 13:42:10 GMT 2013
	 */
	public void setFeedType(Integer feedType) {
		this.feedType = feedType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column feed_entries.updated_by
	 * @return  the value of feed_entries.updated_by
	 * @mbggenerated  Tue Oct 29 13:42:10 GMT 2013
	 */
	public Long getUpdatedBy() {
		return updatedBy;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column feed_entries.updated_by
	 * @param updatedBy  the value for feed_entries.updated_by
	 * @mbggenerated  Tue Oct 29 13:42:10 GMT 2013
	 */
	public void setUpdatedBy(Long updatedBy) {
		this.updatedBy = updatedBy;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column feed_entries.summary
	 * @return  the value of feed_entries.summary
	 * @mbggenerated  Tue Oct 29 13:42:10 GMT 2013
	 */
	public String getSummary() {
		return summary;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column feed_entries.summary
	 * @param summary  the value for feed_entries.summary
	 * @mbggenerated  Tue Oct 29 13:42:10 GMT 2013
	 */
	public void setSummary(String summary) {
		this.summary = summary == null ? null : summary.trim();
	}

}