package com.jemmmedia.organise.mybatis.db.mybatis.model;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class FileAttachmentExample {
    /**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table file_attachments
	 * @mbggenerated  Fri Sep 14 06:32:16 BST 2012
	 */
	protected String orderByClause;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table file_attachments
	 * @mbggenerated  Fri Sep 14 06:32:16 BST 2012
	 */
	protected boolean distinct;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table file_attachments
	 * @mbggenerated  Fri Sep 14 06:32:16 BST 2012
	 */
	protected List<Criteria> oredCriteria;

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table file_attachments
	 * @mbggenerated  Fri Sep 14 06:32:16 BST 2012
	 */
	public FileAttachmentExample() {
		oredCriteria = new ArrayList<Criteria>();
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table file_attachments
	 * @mbggenerated  Fri Sep 14 06:32:16 BST 2012
	 */
	public void setOrderByClause(String orderByClause) {
		this.orderByClause = orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table file_attachments
	 * @mbggenerated  Fri Sep 14 06:32:16 BST 2012
	 */
	public String getOrderByClause() {
		return orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table file_attachments
	 * @mbggenerated  Fri Sep 14 06:32:16 BST 2012
	 */
	public void setDistinct(boolean distinct) {
		this.distinct = distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table file_attachments
	 * @mbggenerated  Fri Sep 14 06:32:16 BST 2012
	 */
	public boolean isDistinct() {
		return distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table file_attachments
	 * @mbggenerated  Fri Sep 14 06:32:16 BST 2012
	 */
	public List<Criteria> getOredCriteria() {
		return oredCriteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table file_attachments
	 * @mbggenerated  Fri Sep 14 06:32:16 BST 2012
	 */
	public void or(Criteria criteria) {
		oredCriteria.add(criteria);
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table file_attachments
	 * @mbggenerated  Fri Sep 14 06:32:16 BST 2012
	 */
	public Criteria or() {
		Criteria criteria = createCriteriaInternal();
		oredCriteria.add(criteria);
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table file_attachments
	 * @mbggenerated  Fri Sep 14 06:32:16 BST 2012
	 */
	public Criteria createCriteria() {
		Criteria criteria = createCriteriaInternal();
		if (oredCriteria.size() == 0) {
			oredCriteria.add(criteria);
		}
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table file_attachments
	 * @mbggenerated  Fri Sep 14 06:32:16 BST 2012
	 */
	protected Criteria createCriteriaInternal() {
		Criteria criteria = new Criteria();
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table file_attachments
	 * @mbggenerated  Fri Sep 14 06:32:16 BST 2012
	 */
	public void clear() {
		oredCriteria.clear();
		orderByClause = null;
		distinct = false;
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table file_attachments
	 * @mbggenerated  Fri Sep 14 06:32:16 BST 2012
	 */
	protected abstract static class GeneratedCriteria {
		protected List<Criterion> criteria;

		protected GeneratedCriteria() {
			super();
			criteria = new ArrayList<Criterion>();
		}

		public boolean isValid() {
			return criteria.size() > 0;
		}

		public List<Criterion> getAllCriteria() {
			return criteria;
		}

		public List<Criterion> getCriteria() {
			return criteria;
		}

		protected void addCriterion(String condition) {
			if (condition == null) {
				throw new RuntimeException("Value for condition cannot be null");
			}
			criteria.add(new Criterion(condition));
		}

		protected void addCriterion(String condition, Object value,
				String property) {
			if (value == null) {
				throw new RuntimeException("Value for " + property
						+ " cannot be null");
			}
			criteria.add(new Criterion(condition, value));
		}

		protected void addCriterion(String condition, Object value1,
				Object value2, String property) {
			if (value1 == null || value2 == null) {
				throw new RuntimeException("Between values for " + property
						+ " cannot be null");
			}
			criteria.add(new Criterion(condition, value1, value2));
		}

		public Criteria andIdIsNull() {
			addCriterion("id is null");
			return (Criteria) this;
		}

		public Criteria andIdIsNotNull() {
			addCriterion("id is not null");
			return (Criteria) this;
		}

		public Criteria andIdEqualTo(Long value) {
			addCriterion("id =", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdNotEqualTo(Long value) {
			addCriterion("id <>", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdGreaterThan(Long value) {
			addCriterion("id >", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdGreaterThanOrEqualTo(Long value) {
			addCriterion("id >=", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdLessThan(Long value) {
			addCriterion("id <", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdLessThanOrEqualTo(Long value) {
			addCriterion("id <=", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdIn(List<Long> values) {
			addCriterion("id in", values, "id");
			return (Criteria) this;
		}

		public Criteria andIdNotIn(List<Long> values) {
			addCriterion("id not in", values, "id");
			return (Criteria) this;
		}

		public Criteria andIdBetween(Long value1, Long value2) {
			addCriterion("id between", value1, value2, "id");
			return (Criteria) this;
		}

		public Criteria andIdNotBetween(Long value1, Long value2) {
			addCriterion("id not between", value1, value2, "id");
			return (Criteria) this;
		}

		public Criteria andNameIsNull() {
			addCriterion("name is null");
			return (Criteria) this;
		}

		public Criteria andNameIsNotNull() {
			addCriterion("name is not null");
			return (Criteria) this;
		}

		public Criteria andNameEqualTo(String value) {
			addCriterion("name =", value, "name");
			return (Criteria) this;
		}

		public Criteria andNameNotEqualTo(String value) {
			addCriterion("name <>", value, "name");
			return (Criteria) this;
		}

		public Criteria andNameGreaterThan(String value) {
			addCriterion("name >", value, "name");
			return (Criteria) this;
		}

		public Criteria andNameGreaterThanOrEqualTo(String value) {
			addCriterion("name >=", value, "name");
			return (Criteria) this;
		}

		public Criteria andNameLessThan(String value) {
			addCriterion("name <", value, "name");
			return (Criteria) this;
		}

		public Criteria andNameLessThanOrEqualTo(String value) {
			addCriterion("name <=", value, "name");
			return (Criteria) this;
		}

		public Criteria andNameLike(String value) {
			addCriterion("name like", value, "name");
			return (Criteria) this;
		}

		public Criteria andNameNotLike(String value) {
			addCriterion("name not like", value, "name");
			return (Criteria) this;
		}

		public Criteria andNameIn(List<String> values) {
			addCriterion("name in", values, "name");
			return (Criteria) this;
		}

		public Criteria andNameNotIn(List<String> values) {
			addCriterion("name not in", values, "name");
			return (Criteria) this;
		}

		public Criteria andNameBetween(String value1, String value2) {
			addCriterion("name between", value1, value2, "name");
			return (Criteria) this;
		}

		public Criteria andNameNotBetween(String value1, String value2) {
			addCriterion("name not between", value1, value2, "name");
			return (Criteria) this;
		}

		public Criteria andFileExtensionIsNull() {
			addCriterion("file_extension is null");
			return (Criteria) this;
		}

		public Criteria andFileExtensionIsNotNull() {
			addCriterion("file_extension is not null");
			return (Criteria) this;
		}

		public Criteria andFileExtensionEqualTo(String value) {
			addCriterion("file_extension =", value, "fileExtension");
			return (Criteria) this;
		}

		public Criteria andFileExtensionNotEqualTo(String value) {
			addCriterion("file_extension <>", value, "fileExtension");
			return (Criteria) this;
		}

		public Criteria andFileExtensionGreaterThan(String value) {
			addCriterion("file_extension >", value, "fileExtension");
			return (Criteria) this;
		}

		public Criteria andFileExtensionGreaterThanOrEqualTo(String value) {
			addCriterion("file_extension >=", value, "fileExtension");
			return (Criteria) this;
		}

		public Criteria andFileExtensionLessThan(String value) {
			addCriterion("file_extension <", value, "fileExtension");
			return (Criteria) this;
		}

		public Criteria andFileExtensionLessThanOrEqualTo(String value) {
			addCriterion("file_extension <=", value, "fileExtension");
			return (Criteria) this;
		}

		public Criteria andFileExtensionLike(String value) {
			addCriterion("file_extension like", value, "fileExtension");
			return (Criteria) this;
		}

		public Criteria andFileExtensionNotLike(String value) {
			addCriterion("file_extension not like", value, "fileExtension");
			return (Criteria) this;
		}

		public Criteria andFileExtensionIn(List<String> values) {
			addCriterion("file_extension in", values, "fileExtension");
			return (Criteria) this;
		}

		public Criteria andFileExtensionNotIn(List<String> values) {
			addCriterion("file_extension not in", values, "fileExtension");
			return (Criteria) this;
		}

		public Criteria andFileExtensionBetween(String value1, String value2) {
			addCriterion("file_extension between", value1, value2,
					"fileExtension");
			return (Criteria) this;
		}

		public Criteria andFileExtensionNotBetween(String value1, String value2) {
			addCriterion("file_extension not between", value1, value2,
					"fileExtension");
			return (Criteria) this;
		}

		public Criteria andAttachableIdIsNull() {
			addCriterion("attachable_id is null");
			return (Criteria) this;
		}

		public Criteria andAttachableIdIsNotNull() {
			addCriterion("attachable_id is not null");
			return (Criteria) this;
		}

		public Criteria andAttachableIdEqualTo(Long value) {
			addCriterion("attachable_id =", value, "attachableId");
			return (Criteria) this;
		}

		public Criteria andAttachableIdNotEqualTo(Long value) {
			addCriterion("attachable_id <>", value, "attachableId");
			return (Criteria) this;
		}

		public Criteria andAttachableIdGreaterThan(Long value) {
			addCriterion("attachable_id >", value, "attachableId");
			return (Criteria) this;
		}

		public Criteria andAttachableIdGreaterThanOrEqualTo(Long value) {
			addCriterion("attachable_id >=", value, "attachableId");
			return (Criteria) this;
		}

		public Criteria andAttachableIdLessThan(Long value) {
			addCriterion("attachable_id <", value, "attachableId");
			return (Criteria) this;
		}

		public Criteria andAttachableIdLessThanOrEqualTo(Long value) {
			addCriterion("attachable_id <=", value, "attachableId");
			return (Criteria) this;
		}

		public Criteria andAttachableIdIn(List<Long> values) {
			addCriterion("attachable_id in", values, "attachableId");
			return (Criteria) this;
		}

		public Criteria andAttachableIdNotIn(List<Long> values) {
			addCriterion("attachable_id not in", values, "attachableId");
			return (Criteria) this;
		}

		public Criteria andAttachableIdBetween(Long value1, Long value2) {
			addCriterion("attachable_id between", value1, value2,
					"attachableId");
			return (Criteria) this;
		}

		public Criteria andAttachableIdNotBetween(Long value1, Long value2) {
			addCriterion("attachable_id not between", value1, value2,
					"attachableId");
			return (Criteria) this;
		}

		public Criteria andAttachableTypeIsNull() {
			addCriterion("attachable_type is null");
			return (Criteria) this;
		}

		public Criteria andAttachableTypeIsNotNull() {
			addCriterion("attachable_type is not null");
			return (Criteria) this;
		}

		public Criteria andAttachableTypeEqualTo(String value) {
			addCriterion("attachable_type =", value, "attachableType");
			return (Criteria) this;
		}

		public Criteria andAttachableTypeNotEqualTo(String value) {
			addCriterion("attachable_type <>", value, "attachableType");
			return (Criteria) this;
		}

		public Criteria andAttachableTypeGreaterThan(String value) {
			addCriterion("attachable_type >", value, "attachableType");
			return (Criteria) this;
		}

		public Criteria andAttachableTypeGreaterThanOrEqualTo(String value) {
			addCriterion("attachable_type >=", value, "attachableType");
			return (Criteria) this;
		}

		public Criteria andAttachableTypeLessThan(String value) {
			addCriterion("attachable_type <", value, "attachableType");
			return (Criteria) this;
		}

		public Criteria andAttachableTypeLessThanOrEqualTo(String value) {
			addCriterion("attachable_type <=", value, "attachableType");
			return (Criteria) this;
		}

		public Criteria andAttachableTypeLike(String value) {
			addCriterion("attachable_type like", value, "attachableType");
			return (Criteria) this;
		}

		public Criteria andAttachableTypeNotLike(String value) {
			addCriterion("attachable_type not like", value, "attachableType");
			return (Criteria) this;
		}

		public Criteria andAttachableTypeIn(List<String> values) {
			addCriterion("attachable_type in", values, "attachableType");
			return (Criteria) this;
		}

		public Criteria andAttachableTypeNotIn(List<String> values) {
			addCriterion("attachable_type not in", values, "attachableType");
			return (Criteria) this;
		}

		public Criteria andAttachableTypeBetween(String value1, String value2) {
			addCriterion("attachable_type between", value1, value2,
					"attachableType");
			return (Criteria) this;
		}

		public Criteria andAttachableTypeNotBetween(String value1, String value2) {
			addCriterion("attachable_type not between", value1, value2,
					"attachableType");
			return (Criteria) this;
		}

		public Criteria andAttachmentFileNameIsNull() {
			addCriterion("attachment_file_name is null");
			return (Criteria) this;
		}

		public Criteria andAttachmentFileNameIsNotNull() {
			addCriterion("attachment_file_name is not null");
			return (Criteria) this;
		}

		public Criteria andAttachmentFileNameEqualTo(String value) {
			addCriterion("attachment_file_name =", value, "attachmentFileName");
			return (Criteria) this;
		}

		public Criteria andAttachmentFileNameNotEqualTo(String value) {
			addCriterion("attachment_file_name <>", value, "attachmentFileName");
			return (Criteria) this;
		}

		public Criteria andAttachmentFileNameGreaterThan(String value) {
			addCriterion("attachment_file_name >", value, "attachmentFileName");
			return (Criteria) this;
		}

		public Criteria andAttachmentFileNameGreaterThanOrEqualTo(String value) {
			addCriterion("attachment_file_name >=", value, "attachmentFileName");
			return (Criteria) this;
		}

		public Criteria andAttachmentFileNameLessThan(String value) {
			addCriterion("attachment_file_name <", value, "attachmentFileName");
			return (Criteria) this;
		}

		public Criteria andAttachmentFileNameLessThanOrEqualTo(String value) {
			addCriterion("attachment_file_name <=", value, "attachmentFileName");
			return (Criteria) this;
		}

		public Criteria andAttachmentFileNameLike(String value) {
			addCriterion("attachment_file_name like", value,
					"attachmentFileName");
			return (Criteria) this;
		}

		public Criteria andAttachmentFileNameNotLike(String value) {
			addCriterion("attachment_file_name not like", value,
					"attachmentFileName");
			return (Criteria) this;
		}

		public Criteria andAttachmentFileNameIn(List<String> values) {
			addCriterion("attachment_file_name in", values,
					"attachmentFileName");
			return (Criteria) this;
		}

		public Criteria andAttachmentFileNameNotIn(List<String> values) {
			addCriterion("attachment_file_name not in", values,
					"attachmentFileName");
			return (Criteria) this;
		}

		public Criteria andAttachmentFileNameBetween(String value1,
				String value2) {
			addCriterion("attachment_file_name between", value1, value2,
					"attachmentFileName");
			return (Criteria) this;
		}

		public Criteria andAttachmentFileNameNotBetween(String value1,
				String value2) {
			addCriterion("attachment_file_name not between", value1, value2,
					"attachmentFileName");
			return (Criteria) this;
		}

		public Criteria andAttachmentContentTypeIsNull() {
			addCriterion("attachment_content_type is null");
			return (Criteria) this;
		}

		public Criteria andAttachmentContentTypeIsNotNull() {
			addCriterion("attachment_content_type is not null");
			return (Criteria) this;
		}

		public Criteria andAttachmentContentTypeEqualTo(String value) {
			addCriterion("attachment_content_type =", value,
					"attachmentContentType");
			return (Criteria) this;
		}

		public Criteria andAttachmentContentTypeNotEqualTo(String value) {
			addCriterion("attachment_content_type <>", value,
					"attachmentContentType");
			return (Criteria) this;
		}

		public Criteria andAttachmentContentTypeGreaterThan(String value) {
			addCriterion("attachment_content_type >", value,
					"attachmentContentType");
			return (Criteria) this;
		}

		public Criteria andAttachmentContentTypeGreaterThanOrEqualTo(
				String value) {
			addCriterion("attachment_content_type >=", value,
					"attachmentContentType");
			return (Criteria) this;
		}

		public Criteria andAttachmentContentTypeLessThan(String value) {
			addCriterion("attachment_content_type <", value,
					"attachmentContentType");
			return (Criteria) this;
		}

		public Criteria andAttachmentContentTypeLessThanOrEqualTo(String value) {
			addCriterion("attachment_content_type <=", value,
					"attachmentContentType");
			return (Criteria) this;
		}

		public Criteria andAttachmentContentTypeLike(String value) {
			addCriterion("attachment_content_type like", value,
					"attachmentContentType");
			return (Criteria) this;
		}

		public Criteria andAttachmentContentTypeNotLike(String value) {
			addCriterion("attachment_content_type not like", value,
					"attachmentContentType");
			return (Criteria) this;
		}

		public Criteria andAttachmentContentTypeIn(List<String> values) {
			addCriterion("attachment_content_type in", values,
					"attachmentContentType");
			return (Criteria) this;
		}

		public Criteria andAttachmentContentTypeNotIn(List<String> values) {
			addCriterion("attachment_content_type not in", values,
					"attachmentContentType");
			return (Criteria) this;
		}

		public Criteria andAttachmentContentTypeBetween(String value1,
				String value2) {
			addCriterion("attachment_content_type between", value1, value2,
					"attachmentContentType");
			return (Criteria) this;
		}

		public Criteria andAttachmentContentTypeNotBetween(String value1,
				String value2) {
			addCriterion("attachment_content_type not between", value1, value2,
					"attachmentContentType");
			return (Criteria) this;
		}

		public Criteria andAttachmentFileSizeIsNull() {
			addCriterion("attachment_file_size is null");
			return (Criteria) this;
		}

		public Criteria andAttachmentFileSizeIsNotNull() {
			addCriterion("attachment_file_size is not null");
			return (Criteria) this;
		}

		public Criteria andAttachmentFileSizeEqualTo(Integer value) {
			addCriterion("attachment_file_size =", value, "attachmentFileSize");
			return (Criteria) this;
		}

		public Criteria andAttachmentFileSizeNotEqualTo(Integer value) {
			addCriterion("attachment_file_size <>", value, "attachmentFileSize");
			return (Criteria) this;
		}

		public Criteria andAttachmentFileSizeGreaterThan(Integer value) {
			addCriterion("attachment_file_size >", value, "attachmentFileSize");
			return (Criteria) this;
		}

		public Criteria andAttachmentFileSizeGreaterThanOrEqualTo(Integer value) {
			addCriterion("attachment_file_size >=", value, "attachmentFileSize");
			return (Criteria) this;
		}

		public Criteria andAttachmentFileSizeLessThan(Integer value) {
			addCriterion("attachment_file_size <", value, "attachmentFileSize");
			return (Criteria) this;
		}

		public Criteria andAttachmentFileSizeLessThanOrEqualTo(Integer value) {
			addCriterion("attachment_file_size <=", value, "attachmentFileSize");
			return (Criteria) this;
		}

		public Criteria andAttachmentFileSizeIn(List<Integer> values) {
			addCriterion("attachment_file_size in", values,
					"attachmentFileSize");
			return (Criteria) this;
		}

		public Criteria andAttachmentFileSizeNotIn(List<Integer> values) {
			addCriterion("attachment_file_size not in", values,
					"attachmentFileSize");
			return (Criteria) this;
		}

		public Criteria andAttachmentFileSizeBetween(Integer value1,
				Integer value2) {
			addCriterion("attachment_file_size between", value1, value2,
					"attachmentFileSize");
			return (Criteria) this;
		}

		public Criteria andAttachmentFileSizeNotBetween(Integer value1,
				Integer value2) {
			addCriterion("attachment_file_size not between", value1, value2,
					"attachmentFileSize");
			return (Criteria) this;
		}

		public Criteria andAttachmentUpdatedAtIsNull() {
			addCriterion("attachment_updated_at is null");
			return (Criteria) this;
		}

		public Criteria andAttachmentUpdatedAtIsNotNull() {
			addCriterion("attachment_updated_at is not null");
			return (Criteria) this;
		}

		public Criteria andAttachmentUpdatedAtEqualTo(Date value) {
			addCriterion("attachment_updated_at =", value,
					"attachmentUpdatedAt");
			return (Criteria) this;
		}

		public Criteria andAttachmentUpdatedAtNotEqualTo(Date value) {
			addCriterion("attachment_updated_at <>", value,
					"attachmentUpdatedAt");
			return (Criteria) this;
		}

		public Criteria andAttachmentUpdatedAtGreaterThan(Date value) {
			addCriterion("attachment_updated_at >", value,
					"attachmentUpdatedAt");
			return (Criteria) this;
		}

		public Criteria andAttachmentUpdatedAtGreaterThanOrEqualTo(Date value) {
			addCriterion("attachment_updated_at >=", value,
					"attachmentUpdatedAt");
			return (Criteria) this;
		}

		public Criteria andAttachmentUpdatedAtLessThan(Date value) {
			addCriterion("attachment_updated_at <", value,
					"attachmentUpdatedAt");
			return (Criteria) this;
		}

		public Criteria andAttachmentUpdatedAtLessThanOrEqualTo(Date value) {
			addCriterion("attachment_updated_at <=", value,
					"attachmentUpdatedAt");
			return (Criteria) this;
		}

		public Criteria andAttachmentUpdatedAtIn(List<Date> values) {
			addCriterion("attachment_updated_at in", values,
					"attachmentUpdatedAt");
			return (Criteria) this;
		}

		public Criteria andAttachmentUpdatedAtNotIn(List<Date> values) {
			addCriterion("attachment_updated_at not in", values,
					"attachmentUpdatedAt");
			return (Criteria) this;
		}

		public Criteria andAttachmentUpdatedAtBetween(Date value1, Date value2) {
			addCriterion("attachment_updated_at between", value1, value2,
					"attachmentUpdatedAt");
			return (Criteria) this;
		}

		public Criteria andAttachmentUpdatedAtNotBetween(Date value1,
				Date value2) {
			addCriterion("attachment_updated_at not between", value1, value2,
					"attachmentUpdatedAt");
			return (Criteria) this;
		}

		public Criteria andCreatorIdIsNull() {
			addCriterion("creator_id is null");
			return (Criteria) this;
		}

		public Criteria andCreatorIdIsNotNull() {
			addCriterion("creator_id is not null");
			return (Criteria) this;
		}

		public Criteria andCreatorIdEqualTo(Long value) {
			addCriterion("creator_id =", value, "creatorId");
			return (Criteria) this;
		}

		public Criteria andCreatorIdNotEqualTo(Long value) {
			addCriterion("creator_id <>", value, "creatorId");
			return (Criteria) this;
		}

		public Criteria andCreatorIdGreaterThan(Long value) {
			addCriterion("creator_id >", value, "creatorId");
			return (Criteria) this;
		}

		public Criteria andCreatorIdGreaterThanOrEqualTo(Long value) {
			addCriterion("creator_id >=", value, "creatorId");
			return (Criteria) this;
		}

		public Criteria andCreatorIdLessThan(Long value) {
			addCriterion("creator_id <", value, "creatorId");
			return (Criteria) this;
		}

		public Criteria andCreatorIdLessThanOrEqualTo(Long value) {
			addCriterion("creator_id <=", value, "creatorId");
			return (Criteria) this;
		}

		public Criteria andCreatorIdIn(List<Long> values) {
			addCriterion("creator_id in", values, "creatorId");
			return (Criteria) this;
		}

		public Criteria andCreatorIdNotIn(List<Long> values) {
			addCriterion("creator_id not in", values, "creatorId");
			return (Criteria) this;
		}

		public Criteria andCreatorIdBetween(Long value1, Long value2) {
			addCriterion("creator_id between", value1, value2, "creatorId");
			return (Criteria) this;
		}

		public Criteria andCreatorIdNotBetween(Long value1, Long value2) {
			addCriterion("creator_id not between", value1, value2, "creatorId");
			return (Criteria) this;
		}

		public Criteria andUpdaterIdIsNull() {
			addCriterion("updater_id is null");
			return (Criteria) this;
		}

		public Criteria andUpdaterIdIsNotNull() {
			addCriterion("updater_id is not null");
			return (Criteria) this;
		}

		public Criteria andUpdaterIdEqualTo(Long value) {
			addCriterion("updater_id =", value, "updaterId");
			return (Criteria) this;
		}

		public Criteria andUpdaterIdNotEqualTo(Long value) {
			addCriterion("updater_id <>", value, "updaterId");
			return (Criteria) this;
		}

		public Criteria andUpdaterIdGreaterThan(Long value) {
			addCriterion("updater_id >", value, "updaterId");
			return (Criteria) this;
		}

		public Criteria andUpdaterIdGreaterThanOrEqualTo(Long value) {
			addCriterion("updater_id >=", value, "updaterId");
			return (Criteria) this;
		}

		public Criteria andUpdaterIdLessThan(Long value) {
			addCriterion("updater_id <", value, "updaterId");
			return (Criteria) this;
		}

		public Criteria andUpdaterIdLessThanOrEqualTo(Long value) {
			addCriterion("updater_id <=", value, "updaterId");
			return (Criteria) this;
		}

		public Criteria andUpdaterIdIn(List<Long> values) {
			addCriterion("updater_id in", values, "updaterId");
			return (Criteria) this;
		}

		public Criteria andUpdaterIdNotIn(List<Long> values) {
			addCriterion("updater_id not in", values, "updaterId");
			return (Criteria) this;
		}

		public Criteria andUpdaterIdBetween(Long value1, Long value2) {
			addCriterion("updater_id between", value1, value2, "updaterId");
			return (Criteria) this;
		}

		public Criteria andUpdaterIdNotBetween(Long value1, Long value2) {
			addCriterion("updater_id not between", value1, value2, "updaterId");
			return (Criteria) this;
		}

		public Criteria andCreatedAtIsNull() {
			addCriterion("created_at is null");
			return (Criteria) this;
		}

		public Criteria andCreatedAtIsNotNull() {
			addCriterion("created_at is not null");
			return (Criteria) this;
		}

		public Criteria andCreatedAtEqualTo(Date value) {
			addCriterion("created_at =", value, "createdAt");
			return (Criteria) this;
		}

		public Criteria andCreatedAtNotEqualTo(Date value) {
			addCriterion("created_at <>", value, "createdAt");
			return (Criteria) this;
		}

		public Criteria andCreatedAtGreaterThan(Date value) {
			addCriterion("created_at >", value, "createdAt");
			return (Criteria) this;
		}

		public Criteria andCreatedAtGreaterThanOrEqualTo(Date value) {
			addCriterion("created_at >=", value, "createdAt");
			return (Criteria) this;
		}

		public Criteria andCreatedAtLessThan(Date value) {
			addCriterion("created_at <", value, "createdAt");
			return (Criteria) this;
		}

		public Criteria andCreatedAtLessThanOrEqualTo(Date value) {
			addCriterion("created_at <=", value, "createdAt");
			return (Criteria) this;
		}

		public Criteria andCreatedAtIn(List<Date> values) {
			addCriterion("created_at in", values, "createdAt");
			return (Criteria) this;
		}

		public Criteria andCreatedAtNotIn(List<Date> values) {
			addCriterion("created_at not in", values, "createdAt");
			return (Criteria) this;
		}

		public Criteria andCreatedAtBetween(Date value1, Date value2) {
			addCriterion("created_at between", value1, value2, "createdAt");
			return (Criteria) this;
		}

		public Criteria andCreatedAtNotBetween(Date value1, Date value2) {
			addCriterion("created_at not between", value1, value2, "createdAt");
			return (Criteria) this;
		}

		public Criteria andUpdatedAtIsNull() {
			addCriterion("updated_at is null");
			return (Criteria) this;
		}

		public Criteria andUpdatedAtIsNotNull() {
			addCriterion("updated_at is not null");
			return (Criteria) this;
		}

		public Criteria andUpdatedAtEqualTo(Date value) {
			addCriterion("updated_at =", value, "updatedAt");
			return (Criteria) this;
		}

		public Criteria andUpdatedAtNotEqualTo(Date value) {
			addCriterion("updated_at <>", value, "updatedAt");
			return (Criteria) this;
		}

		public Criteria andUpdatedAtGreaterThan(Date value) {
			addCriterion("updated_at >", value, "updatedAt");
			return (Criteria) this;
		}

		public Criteria andUpdatedAtGreaterThanOrEqualTo(Date value) {
			addCriterion("updated_at >=", value, "updatedAt");
			return (Criteria) this;
		}

		public Criteria andUpdatedAtLessThan(Date value) {
			addCriterion("updated_at <", value, "updatedAt");
			return (Criteria) this;
		}

		public Criteria andUpdatedAtLessThanOrEqualTo(Date value) {
			addCriterion("updated_at <=", value, "updatedAt");
			return (Criteria) this;
		}

		public Criteria andUpdatedAtIn(List<Date> values) {
			addCriterion("updated_at in", values, "updatedAt");
			return (Criteria) this;
		}

		public Criteria andUpdatedAtNotIn(List<Date> values) {
			addCriterion("updated_at not in", values, "updatedAt");
			return (Criteria) this;
		}

		public Criteria andUpdatedAtBetween(Date value1, Date value2) {
			addCriterion("updated_at between", value1, value2, "updatedAt");
			return (Criteria) this;
		}

		public Criteria andUpdatedAtNotBetween(Date value1, Date value2) {
			addCriterion("updated_at not between", value1, value2, "updatedAt");
			return (Criteria) this;
		}
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table file_attachments
	 * @mbggenerated  Fri Sep 14 06:32:16 BST 2012
	 */
	public static class Criterion {
		private String condition;
		private Object value;
		private Object secondValue;
		private boolean noValue;
		private boolean singleValue;
		private boolean betweenValue;
		private boolean listValue;
		private String typeHandler;

		public String getCondition() {
			return condition;
		}

		public Object getValue() {
			return value;
		}

		public Object getSecondValue() {
			return secondValue;
		}

		public boolean isNoValue() {
			return noValue;
		}

		public boolean isSingleValue() {
			return singleValue;
		}

		public boolean isBetweenValue() {
			return betweenValue;
		}

		public boolean isListValue() {
			return listValue;
		}

		public String getTypeHandler() {
			return typeHandler;
		}

		protected Criterion(String condition) {
			super();
			this.condition = condition;
			this.typeHandler = null;
			this.noValue = true;
		}

		protected Criterion(String condition, Object value, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.typeHandler = typeHandler;
			if (value instanceof List<?>) {
				this.listValue = true;
			} else {
				this.singleValue = true;
			}
		}

		protected Criterion(String condition, Object value) {
			this(condition, value, null);
		}

		protected Criterion(String condition, Object value, Object secondValue,
				String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.secondValue = secondValue;
			this.typeHandler = typeHandler;
			this.betweenValue = true;
		}

		protected Criterion(String condition, Object value, Object secondValue) {
			this(condition, value, secondValue, null);
		}
	}

	/**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table file_attachments
     *
     * @mbggenerated do_not_delete_during_merge Mon Aug 06 10:08:53 BST 2012
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }
}