package com.jemmmedia.organise.mybatis.db.mybatis.model;

public class FollowersKey {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column followers.feed_entry_id
	 * @mbggenerated  Mon Jul 29 13:57:53 BST 2013
	 */
	private Long feedEntryId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column followers.follower_id
	 * @mbggenerated  Mon Jul 29 13:57:53 BST 2013
	 */
	private Long followerId;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column followers.feed_entry_id
	 * @return  the value of followers.feed_entry_id
	 * @mbggenerated  Mon Jul 29 13:57:53 BST 2013
	 */
	public Long getFeedEntryId() {
		return feedEntryId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column followers.feed_entry_id
	 * @param feedEntryId  the value for followers.feed_entry_id
	 * @mbggenerated  Mon Jul 29 13:57:53 BST 2013
	 */
	public void setFeedEntryId(Long feedEntryId) {
		this.feedEntryId = feedEntryId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column followers.follower_id
	 * @return  the value of followers.follower_id
	 * @mbggenerated  Mon Jul 29 13:57:53 BST 2013
	 */
	public Long getFollowerId() {
		return followerId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column followers.follower_id
	 * @param followerId  the value for followers.follower_id
	 * @mbggenerated  Mon Jul 29 13:57:53 BST 2013
	 */
	public void setFollowerId(Long followerId) {
		this.followerId = followerId;
	}
}