package com.jemmmedia.organise.mybatis.db.mybatis.model;

import java.util.Date;

public class Followers extends FollowersKey {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column followers.created_at
	 * @mbggenerated  Mon Jul 29 13:57:53 BST 2013
	 */
	private Date createdAt;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column followers.created_at
	 * @return  the value of followers.created_at
	 * @mbggenerated  Mon Jul 29 13:57:53 BST 2013
	 */
	public Date getCreatedAt() {
		return createdAt;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column followers.created_at
	 * @param createdAt  the value for followers.created_at
	 * @mbggenerated  Mon Jul 29 13:57:53 BST 2013
	 */
	public void setCreatedAt(Date createdAt) {
		this.createdAt = createdAt;
	}
}