package com.jemmmedia.organise.mybatis.db.mybatis.model;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class HighriseDealsExample {
    /**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table highrise_deals
	 * @mbggenerated  Tue Oct 29 13:42:10 GMT 2013
	 */
	protected String orderByClause;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table highrise_deals
	 * @mbggenerated  Tue Oct 29 13:42:10 GMT 2013
	 */
	protected boolean distinct;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table highrise_deals
	 * @mbggenerated  Tue Oct 29 13:42:10 GMT 2013
	 */
	protected List<Criteria> oredCriteria;

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table highrise_deals
	 * @mbggenerated  Tue Oct 29 13:42:10 GMT 2013
	 */
	public HighriseDealsExample() {
		oredCriteria = new ArrayList<Criteria>();
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table highrise_deals
	 * @mbggenerated  Tue Oct 29 13:42:10 GMT 2013
	 */
	public void setOrderByClause(String orderByClause) {
		this.orderByClause = orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table highrise_deals
	 * @mbggenerated  Tue Oct 29 13:42:10 GMT 2013
	 */
	public String getOrderByClause() {
		return orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table highrise_deals
	 * @mbggenerated  Tue Oct 29 13:42:10 GMT 2013
	 */
	public void setDistinct(boolean distinct) {
		this.distinct = distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table highrise_deals
	 * @mbggenerated  Tue Oct 29 13:42:10 GMT 2013
	 */
	public boolean isDistinct() {
		return distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table highrise_deals
	 * @mbggenerated  Tue Oct 29 13:42:10 GMT 2013
	 */
	public List<Criteria> getOredCriteria() {
		return oredCriteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table highrise_deals
	 * @mbggenerated  Tue Oct 29 13:42:10 GMT 2013
	 */
	public void or(Criteria criteria) {
		oredCriteria.add(criteria);
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table highrise_deals
	 * @mbggenerated  Tue Oct 29 13:42:10 GMT 2013
	 */
	public Criteria or() {
		Criteria criteria = createCriteriaInternal();
		oredCriteria.add(criteria);
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table highrise_deals
	 * @mbggenerated  Tue Oct 29 13:42:10 GMT 2013
	 */
	public Criteria createCriteria() {
		Criteria criteria = createCriteriaInternal();
		if (oredCriteria.size() == 0) {
			oredCriteria.add(criteria);
		}
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table highrise_deals
	 * @mbggenerated  Tue Oct 29 13:42:10 GMT 2013
	 */
	protected Criteria createCriteriaInternal() {
		Criteria criteria = new Criteria();
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table highrise_deals
	 * @mbggenerated  Tue Oct 29 13:42:10 GMT 2013
	 */
	public void clear() {
		oredCriteria.clear();
		orderByClause = null;
		distinct = false;
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table highrise_deals
	 * @mbggenerated  Tue Oct 29 13:42:10 GMT 2013
	 */
	protected abstract static class GeneratedCriteria {
		protected List<Criterion> criteria;

		protected GeneratedCriteria() {
			super();
			criteria = new ArrayList<Criterion>();
		}

		public boolean isValid() {
			return criteria.size() > 0;
		}

		public List<Criterion> getAllCriteria() {
			return criteria;
		}

		public List<Criterion> getCriteria() {
			return criteria;
		}

		protected void addCriterion(String condition) {
			if (condition == null) {
				throw new RuntimeException("Value for condition cannot be null");
			}
			criteria.add(new Criterion(condition));
		}

		protected void addCriterion(String condition, Object value,
				String property) {
			if (value == null) {
				throw new RuntimeException("Value for " + property
						+ " cannot be null");
			}
			criteria.add(new Criterion(condition, value));
		}

		protected void addCriterion(String condition, Object value1,
				Object value2, String property) {
			if (value1 == null || value2 == null) {
				throw new RuntimeException("Between values for " + property
						+ " cannot be null");
			}
			criteria.add(new Criterion(condition, value1, value2));
		}

		public Criteria andIdIsNull() {
			addCriterion("id is null");
			return (Criteria) this;
		}

		public Criteria andIdIsNotNull() {
			addCriterion("id is not null");
			return (Criteria) this;
		}

		public Criteria andIdEqualTo(Long value) {
			addCriterion("id =", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdNotEqualTo(Long value) {
			addCriterion("id <>", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdGreaterThan(Long value) {
			addCriterion("id >", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdGreaterThanOrEqualTo(Long value) {
			addCriterion("id >=", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdLessThan(Long value) {
			addCriterion("id <", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdLessThanOrEqualTo(Long value) {
			addCriterion("id <=", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdIn(List<Long> values) {
			addCriterion("id in", values, "id");
			return (Criteria) this;
		}

		public Criteria andIdNotIn(List<Long> values) {
			addCriterion("id not in", values, "id");
			return (Criteria) this;
		}

		public Criteria andIdBetween(Long value1, Long value2) {
			addCriterion("id between", value1, value2, "id");
			return (Criteria) this;
		}

		public Criteria andIdNotBetween(Long value1, Long value2) {
			addCriterion("id not between", value1, value2, "id");
			return (Criteria) this;
		}

		public Criteria andDealIdIsNull() {
			addCriterion("deal_id is null");
			return (Criteria) this;
		}

		public Criteria andDealIdIsNotNull() {
			addCriterion("deal_id is not null");
			return (Criteria) this;
		}

		public Criteria andDealIdEqualTo(Long value) {
			addCriterion("deal_id =", value, "dealId");
			return (Criteria) this;
		}

		public Criteria andDealIdNotEqualTo(Long value) {
			addCriterion("deal_id <>", value, "dealId");
			return (Criteria) this;
		}

		public Criteria andDealIdGreaterThan(Long value) {
			addCriterion("deal_id >", value, "dealId");
			return (Criteria) this;
		}

		public Criteria andDealIdGreaterThanOrEqualTo(Long value) {
			addCriterion("deal_id >=", value, "dealId");
			return (Criteria) this;
		}

		public Criteria andDealIdLessThan(Long value) {
			addCriterion("deal_id <", value, "dealId");
			return (Criteria) this;
		}

		public Criteria andDealIdLessThanOrEqualTo(Long value) {
			addCriterion("deal_id <=", value, "dealId");
			return (Criteria) this;
		}

		public Criteria andDealIdIn(List<Long> values) {
			addCriterion("deal_id in", values, "dealId");
			return (Criteria) this;
		}

		public Criteria andDealIdNotIn(List<Long> values) {
			addCriterion("deal_id not in", values, "dealId");
			return (Criteria) this;
		}

		public Criteria andDealIdBetween(Long value1, Long value2) {
			addCriterion("deal_id between", value1, value2, "dealId");
			return (Criteria) this;
		}

		public Criteria andDealIdNotBetween(Long value1, Long value2) {
			addCriterion("deal_id not between", value1, value2, "dealId");
			return (Criteria) this;
		}

		public Criteria andAccountIdIsNull() {
			addCriterion("account_id is null");
			return (Criteria) this;
		}

		public Criteria andAccountIdIsNotNull() {
			addCriterion("account_id is not null");
			return (Criteria) this;
		}

		public Criteria andAccountIdEqualTo(Long value) {
			addCriterion("account_id =", value, "accountId");
			return (Criteria) this;
		}

		public Criteria andAccountIdNotEqualTo(Long value) {
			addCriterion("account_id <>", value, "accountId");
			return (Criteria) this;
		}

		public Criteria andAccountIdGreaterThan(Long value) {
			addCriterion("account_id >", value, "accountId");
			return (Criteria) this;
		}

		public Criteria andAccountIdGreaterThanOrEqualTo(Long value) {
			addCriterion("account_id >=", value, "accountId");
			return (Criteria) this;
		}

		public Criteria andAccountIdLessThan(Long value) {
			addCriterion("account_id <", value, "accountId");
			return (Criteria) this;
		}

		public Criteria andAccountIdLessThanOrEqualTo(Long value) {
			addCriterion("account_id <=", value, "accountId");
			return (Criteria) this;
		}

		public Criteria andAccountIdIn(List<Long> values) {
			addCriterion("account_id in", values, "accountId");
			return (Criteria) this;
		}

		public Criteria andAccountIdNotIn(List<Long> values) {
			addCriterion("account_id not in", values, "accountId");
			return (Criteria) this;
		}

		public Criteria andAccountIdBetween(Long value1, Long value2) {
			addCriterion("account_id between", value1, value2, "accountId");
			return (Criteria) this;
		}

		public Criteria andAccountIdNotBetween(Long value1, Long value2) {
			addCriterion("account_id not between", value1, value2, "accountId");
			return (Criteria) this;
		}

		public Criteria andAuthorIdIsNull() {
			addCriterion("author_id is null");
			return (Criteria) this;
		}

		public Criteria andAuthorIdIsNotNull() {
			addCriterion("author_id is not null");
			return (Criteria) this;
		}

		public Criteria andAuthorIdEqualTo(Long value) {
			addCriterion("author_id =", value, "authorId");
			return (Criteria) this;
		}

		public Criteria andAuthorIdNotEqualTo(Long value) {
			addCriterion("author_id <>", value, "authorId");
			return (Criteria) this;
		}

		public Criteria andAuthorIdGreaterThan(Long value) {
			addCriterion("author_id >", value, "authorId");
			return (Criteria) this;
		}

		public Criteria andAuthorIdGreaterThanOrEqualTo(Long value) {
			addCriterion("author_id >=", value, "authorId");
			return (Criteria) this;
		}

		public Criteria andAuthorIdLessThan(Long value) {
			addCriterion("author_id <", value, "authorId");
			return (Criteria) this;
		}

		public Criteria andAuthorIdLessThanOrEqualTo(Long value) {
			addCriterion("author_id <=", value, "authorId");
			return (Criteria) this;
		}

		public Criteria andAuthorIdIn(List<Long> values) {
			addCriterion("author_id in", values, "authorId");
			return (Criteria) this;
		}

		public Criteria andAuthorIdNotIn(List<Long> values) {
			addCriterion("author_id not in", values, "authorId");
			return (Criteria) this;
		}

		public Criteria andAuthorIdBetween(Long value1, Long value2) {
			addCriterion("author_id between", value1, value2, "authorId");
			return (Criteria) this;
		}

		public Criteria andAuthorIdNotBetween(Long value1, Long value2) {
			addCriterion("author_id not between", value1, value2, "authorId");
			return (Criteria) this;
		}

		public Criteria andCategoryIdIsNull() {
			addCriterion("category_id is null");
			return (Criteria) this;
		}

		public Criteria andCategoryIdIsNotNull() {
			addCriterion("category_id is not null");
			return (Criteria) this;
		}

		public Criteria andCategoryIdEqualTo(Long value) {
			addCriterion("category_id =", value, "categoryId");
			return (Criteria) this;
		}

		public Criteria andCategoryIdNotEqualTo(Long value) {
			addCriterion("category_id <>", value, "categoryId");
			return (Criteria) this;
		}

		public Criteria andCategoryIdGreaterThan(Long value) {
			addCriterion("category_id >", value, "categoryId");
			return (Criteria) this;
		}

		public Criteria andCategoryIdGreaterThanOrEqualTo(Long value) {
			addCriterion("category_id >=", value, "categoryId");
			return (Criteria) this;
		}

		public Criteria andCategoryIdLessThan(Long value) {
			addCriterion("category_id <", value, "categoryId");
			return (Criteria) this;
		}

		public Criteria andCategoryIdLessThanOrEqualTo(Long value) {
			addCriterion("category_id <=", value, "categoryId");
			return (Criteria) this;
		}

		public Criteria andCategoryIdIn(List<Long> values) {
			addCriterion("category_id in", values, "categoryId");
			return (Criteria) this;
		}

		public Criteria andCategoryIdNotIn(List<Long> values) {
			addCriterion("category_id not in", values, "categoryId");
			return (Criteria) this;
		}

		public Criteria andCategoryIdBetween(Long value1, Long value2) {
			addCriterion("category_id between", value1, value2, "categoryId");
			return (Criteria) this;
		}

		public Criteria andCategoryIdNotBetween(Long value1, Long value2) {
			addCriterion("category_id not between", value1, value2,
					"categoryId");
			return (Criteria) this;
		}

		public Criteria andCurrencyIsNull() {
			addCriterion("currency is null");
			return (Criteria) this;
		}

		public Criteria andCurrencyIsNotNull() {
			addCriterion("currency is not null");
			return (Criteria) this;
		}

		public Criteria andCurrencyEqualTo(String value) {
			addCriterion("currency =", value, "currency");
			return (Criteria) this;
		}

		public Criteria andCurrencyNotEqualTo(String value) {
			addCriterion("currency <>", value, "currency");
			return (Criteria) this;
		}

		public Criteria andCurrencyGreaterThan(String value) {
			addCriterion("currency >", value, "currency");
			return (Criteria) this;
		}

		public Criteria andCurrencyGreaterThanOrEqualTo(String value) {
			addCriterion("currency >=", value, "currency");
			return (Criteria) this;
		}

		public Criteria andCurrencyLessThan(String value) {
			addCriterion("currency <", value, "currency");
			return (Criteria) this;
		}

		public Criteria andCurrencyLessThanOrEqualTo(String value) {
			addCriterion("currency <=", value, "currency");
			return (Criteria) this;
		}

		public Criteria andCurrencyLike(String value) {
			addCriterion("currency like", value, "currency");
			return (Criteria) this;
		}

		public Criteria andCurrencyNotLike(String value) {
			addCriterion("currency not like", value, "currency");
			return (Criteria) this;
		}

		public Criteria andCurrencyIn(List<String> values) {
			addCriterion("currency in", values, "currency");
			return (Criteria) this;
		}

		public Criteria andCurrencyNotIn(List<String> values) {
			addCriterion("currency not in", values, "currency");
			return (Criteria) this;
		}

		public Criteria andCurrencyBetween(String value1, String value2) {
			addCriterion("currency between", value1, value2, "currency");
			return (Criteria) this;
		}

		public Criteria andCurrencyNotBetween(String value1, String value2) {
			addCriterion("currency not between", value1, value2, "currency");
			return (Criteria) this;
		}

		public Criteria andDurationIsNull() {
			addCriterion("duration is null");
			return (Criteria) this;
		}

		public Criteria andDurationIsNotNull() {
			addCriterion("duration is not null");
			return (Criteria) this;
		}

		public Criteria andDurationEqualTo(String value) {
			addCriterion("duration =", value, "duration");
			return (Criteria) this;
		}

		public Criteria andDurationNotEqualTo(String value) {
			addCriterion("duration <>", value, "duration");
			return (Criteria) this;
		}

		public Criteria andDurationGreaterThan(String value) {
			addCriterion("duration >", value, "duration");
			return (Criteria) this;
		}

		public Criteria andDurationGreaterThanOrEqualTo(String value) {
			addCriterion("duration >=", value, "duration");
			return (Criteria) this;
		}

		public Criteria andDurationLessThan(String value) {
			addCriterion("duration <", value, "duration");
			return (Criteria) this;
		}

		public Criteria andDurationLessThanOrEqualTo(String value) {
			addCriterion("duration <=", value, "duration");
			return (Criteria) this;
		}

		public Criteria andDurationLike(String value) {
			addCriterion("duration like", value, "duration");
			return (Criteria) this;
		}

		public Criteria andDurationNotLike(String value) {
			addCriterion("duration not like", value, "duration");
			return (Criteria) this;
		}

		public Criteria andDurationIn(List<String> values) {
			addCriterion("duration in", values, "duration");
			return (Criteria) this;
		}

		public Criteria andDurationNotIn(List<String> values) {
			addCriterion("duration not in", values, "duration");
			return (Criteria) this;
		}

		public Criteria andDurationBetween(String value1, String value2) {
			addCriterion("duration between", value1, value2, "duration");
			return (Criteria) this;
		}

		public Criteria andDurationNotBetween(String value1, String value2) {
			addCriterion("duration not between", value1, value2, "duration");
			return (Criteria) this;
		}

		public Criteria andNameIsNull() {
			addCriterion("name is null");
			return (Criteria) this;
		}

		public Criteria andNameIsNotNull() {
			addCriterion("name is not null");
			return (Criteria) this;
		}

		public Criteria andNameEqualTo(String value) {
			addCriterion("name =", value, "name");
			return (Criteria) this;
		}

		public Criteria andNameNotEqualTo(String value) {
			addCriterion("name <>", value, "name");
			return (Criteria) this;
		}

		public Criteria andNameGreaterThan(String value) {
			addCriterion("name >", value, "name");
			return (Criteria) this;
		}

		public Criteria andNameGreaterThanOrEqualTo(String value) {
			addCriterion("name >=", value, "name");
			return (Criteria) this;
		}

		public Criteria andNameLessThan(String value) {
			addCriterion("name <", value, "name");
			return (Criteria) this;
		}

		public Criteria andNameLessThanOrEqualTo(String value) {
			addCriterion("name <=", value, "name");
			return (Criteria) this;
		}

		public Criteria andNameLike(String value) {
			addCriterion("name like", value, "name");
			return (Criteria) this;
		}

		public Criteria andNameNotLike(String value) {
			addCriterion("name not like", value, "name");
			return (Criteria) this;
		}

		public Criteria andNameIn(List<String> values) {
			addCriterion("name in", values, "name");
			return (Criteria) this;
		}

		public Criteria andNameNotIn(List<String> values) {
			addCriterion("name not in", values, "name");
			return (Criteria) this;
		}

		public Criteria andNameBetween(String value1, String value2) {
			addCriterion("name between", value1, value2, "name");
			return (Criteria) this;
		}

		public Criteria andNameNotBetween(String value1, String value2) {
			addCriterion("name not between", value1, value2, "name");
			return (Criteria) this;
		}

		public Criteria andPartyIdIsNull() {
			addCriterion("party_id is null");
			return (Criteria) this;
		}

		public Criteria andPartyIdIsNotNull() {
			addCriterion("party_id is not null");
			return (Criteria) this;
		}

		public Criteria andPartyIdEqualTo(Long value) {
			addCriterion("party_id =", value, "partyId");
			return (Criteria) this;
		}

		public Criteria andPartyIdNotEqualTo(Long value) {
			addCriterion("party_id <>", value, "partyId");
			return (Criteria) this;
		}

		public Criteria andPartyIdGreaterThan(Long value) {
			addCriterion("party_id >", value, "partyId");
			return (Criteria) this;
		}

		public Criteria andPartyIdGreaterThanOrEqualTo(Long value) {
			addCriterion("party_id >=", value, "partyId");
			return (Criteria) this;
		}

		public Criteria andPartyIdLessThan(Long value) {
			addCriterion("party_id <", value, "partyId");
			return (Criteria) this;
		}

		public Criteria andPartyIdLessThanOrEqualTo(Long value) {
			addCriterion("party_id <=", value, "partyId");
			return (Criteria) this;
		}

		public Criteria andPartyIdIn(List<Long> values) {
			addCriterion("party_id in", values, "partyId");
			return (Criteria) this;
		}

		public Criteria andPartyIdNotIn(List<Long> values) {
			addCriterion("party_id not in", values, "partyId");
			return (Criteria) this;
		}

		public Criteria andPartyIdBetween(Long value1, Long value2) {
			addCriterion("party_id between", value1, value2, "partyId");
			return (Criteria) this;
		}

		public Criteria andPartyIdNotBetween(Long value1, Long value2) {
			addCriterion("party_id not between", value1, value2, "partyId");
			return (Criteria) this;
		}

		public Criteria andPriceIsNull() {
			addCriterion("price is null");
			return (Criteria) this;
		}

		public Criteria andPriceIsNotNull() {
			addCriterion("price is not null");
			return (Criteria) this;
		}

		public Criteria andPriceEqualTo(Integer value) {
			addCriterion("price =", value, "price");
			return (Criteria) this;
		}

		public Criteria andPriceNotEqualTo(Integer value) {
			addCriterion("price <>", value, "price");
			return (Criteria) this;
		}

		public Criteria andPriceGreaterThan(Integer value) {
			addCriterion("price >", value, "price");
			return (Criteria) this;
		}

		public Criteria andPriceGreaterThanOrEqualTo(Integer value) {
			addCriterion("price >=", value, "price");
			return (Criteria) this;
		}

		public Criteria andPriceLessThan(Integer value) {
			addCriterion("price <", value, "price");
			return (Criteria) this;
		}

		public Criteria andPriceLessThanOrEqualTo(Integer value) {
			addCriterion("price <=", value, "price");
			return (Criteria) this;
		}

		public Criteria andPriceIn(List<Integer> values) {
			addCriterion("price in", values, "price");
			return (Criteria) this;
		}

		public Criteria andPriceNotIn(List<Integer> values) {
			addCriterion("price not in", values, "price");
			return (Criteria) this;
		}

		public Criteria andPriceBetween(Integer value1, Integer value2) {
			addCriterion("price between", value1, value2, "price");
			return (Criteria) this;
		}

		public Criteria andPriceNotBetween(Integer value1, Integer value2) {
			addCriterion("price not between", value1, value2, "price");
			return (Criteria) this;
		}

		public Criteria andPriceTypeIsNull() {
			addCriterion("price_type is null");
			return (Criteria) this;
		}

		public Criteria andPriceTypeIsNotNull() {
			addCriterion("price_type is not null");
			return (Criteria) this;
		}

		public Criteria andPriceTypeEqualTo(String value) {
			addCriterion("price_type =", value, "priceType");
			return (Criteria) this;
		}

		public Criteria andPriceTypeNotEqualTo(String value) {
			addCriterion("price_type <>", value, "priceType");
			return (Criteria) this;
		}

		public Criteria andPriceTypeGreaterThan(String value) {
			addCriterion("price_type >", value, "priceType");
			return (Criteria) this;
		}

		public Criteria andPriceTypeGreaterThanOrEqualTo(String value) {
			addCriterion("price_type >=", value, "priceType");
			return (Criteria) this;
		}

		public Criteria andPriceTypeLessThan(String value) {
			addCriterion("price_type <", value, "priceType");
			return (Criteria) this;
		}

		public Criteria andPriceTypeLessThanOrEqualTo(String value) {
			addCriterion("price_type <=", value, "priceType");
			return (Criteria) this;
		}

		public Criteria andPriceTypeLike(String value) {
			addCriterion("price_type like", value, "priceType");
			return (Criteria) this;
		}

		public Criteria andPriceTypeNotLike(String value) {
			addCriterion("price_type not like", value, "priceType");
			return (Criteria) this;
		}

		public Criteria andPriceTypeIn(List<String> values) {
			addCriterion("price_type in", values, "priceType");
			return (Criteria) this;
		}

		public Criteria andPriceTypeNotIn(List<String> values) {
			addCriterion("price_type not in", values, "priceType");
			return (Criteria) this;
		}

		public Criteria andPriceTypeBetween(String value1, String value2) {
			addCriterion("price_type between", value1, value2, "priceType");
			return (Criteria) this;
		}

		public Criteria andPriceTypeNotBetween(String value1, String value2) {
			addCriterion("price_type not between", value1, value2, "priceType");
			return (Criteria) this;
		}

		public Criteria andResponsiblePartyIdIsNull() {
			addCriterion("responsible_party_id is null");
			return (Criteria) this;
		}

		public Criteria andResponsiblePartyIdIsNotNull() {
			addCriterion("responsible_party_id is not null");
			return (Criteria) this;
		}

		public Criteria andResponsiblePartyIdEqualTo(Long value) {
			addCriterion("responsible_party_id =", value, "responsiblePartyId");
			return (Criteria) this;
		}

		public Criteria andResponsiblePartyIdNotEqualTo(Long value) {
			addCriterion("responsible_party_id <>", value, "responsiblePartyId");
			return (Criteria) this;
		}

		public Criteria andResponsiblePartyIdGreaterThan(Long value) {
			addCriterion("responsible_party_id >", value, "responsiblePartyId");
			return (Criteria) this;
		}

		public Criteria andResponsiblePartyIdGreaterThanOrEqualTo(Long value) {
			addCriterion("responsible_party_id >=", value, "responsiblePartyId");
			return (Criteria) this;
		}

		public Criteria andResponsiblePartyIdLessThan(Long value) {
			addCriterion("responsible_party_id <", value, "responsiblePartyId");
			return (Criteria) this;
		}

		public Criteria andResponsiblePartyIdLessThanOrEqualTo(Long value) {
			addCriterion("responsible_party_id <=", value, "responsiblePartyId");
			return (Criteria) this;
		}

		public Criteria andResponsiblePartyIdIn(List<Long> values) {
			addCriterion("responsible_party_id in", values,
					"responsiblePartyId");
			return (Criteria) this;
		}

		public Criteria andResponsiblePartyIdNotIn(List<Long> values) {
			addCriterion("responsible_party_id not in", values,
					"responsiblePartyId");
			return (Criteria) this;
		}

		public Criteria andResponsiblePartyIdBetween(Long value1, Long value2) {
			addCriterion("responsible_party_id between", value1, value2,
					"responsiblePartyId");
			return (Criteria) this;
		}

		public Criteria andResponsiblePartyIdNotBetween(Long value1, Long value2) {
			addCriterion("responsible_party_id not between", value1, value2,
					"responsiblePartyId");
			return (Criteria) this;
		}

		public Criteria andStatusIsNull() {
			addCriterion("status is null");
			return (Criteria) this;
		}

		public Criteria andStatusIsNotNull() {
			addCriterion("status is not null");
			return (Criteria) this;
		}

		public Criteria andStatusEqualTo(String value) {
			addCriterion("status =", value, "status");
			return (Criteria) this;
		}

		public Criteria andStatusNotEqualTo(String value) {
			addCriterion("status <>", value, "status");
			return (Criteria) this;
		}

		public Criteria andStatusGreaterThan(String value) {
			addCriterion("status >", value, "status");
			return (Criteria) this;
		}

		public Criteria andStatusGreaterThanOrEqualTo(String value) {
			addCriterion("status >=", value, "status");
			return (Criteria) this;
		}

		public Criteria andStatusLessThan(String value) {
			addCriterion("status <", value, "status");
			return (Criteria) this;
		}

		public Criteria andStatusLessThanOrEqualTo(String value) {
			addCriterion("status <=", value, "status");
			return (Criteria) this;
		}

		public Criteria andStatusLike(String value) {
			addCriterion("status like", value, "status");
			return (Criteria) this;
		}

		public Criteria andStatusNotLike(String value) {
			addCriterion("status not like", value, "status");
			return (Criteria) this;
		}

		public Criteria andStatusIn(List<String> values) {
			addCriterion("status in", values, "status");
			return (Criteria) this;
		}

		public Criteria andStatusNotIn(List<String> values) {
			addCriterion("status not in", values, "status");
			return (Criteria) this;
		}

		public Criteria andStatusBetween(String value1, String value2) {
			addCriterion("status between", value1, value2, "status");
			return (Criteria) this;
		}

		public Criteria andStatusNotBetween(String value1, String value2) {
			addCriterion("status not between", value1, value2, "status");
			return (Criteria) this;
		}

		public Criteria andStatusChangedOnIsNull() {
			addCriterion("status_changed_on is null");
			return (Criteria) this;
		}

		public Criteria andStatusChangedOnIsNotNull() {
			addCriterion("status_changed_on is not null");
			return (Criteria) this;
		}

		public Criteria andStatusChangedOnEqualTo(String value) {
			addCriterion("status_changed_on =", value, "statusChangedOn");
			return (Criteria) this;
		}

		public Criteria andStatusChangedOnNotEqualTo(String value) {
			addCriterion("status_changed_on <>", value, "statusChangedOn");
			return (Criteria) this;
		}

		public Criteria andStatusChangedOnGreaterThan(String value) {
			addCriterion("status_changed_on >", value, "statusChangedOn");
			return (Criteria) this;
		}

		public Criteria andStatusChangedOnGreaterThanOrEqualTo(String value) {
			addCriterion("status_changed_on >=", value, "statusChangedOn");
			return (Criteria) this;
		}

		public Criteria andStatusChangedOnLessThan(String value) {
			addCriterion("status_changed_on <", value, "statusChangedOn");
			return (Criteria) this;
		}

		public Criteria andStatusChangedOnLessThanOrEqualTo(String value) {
			addCriterion("status_changed_on <=", value, "statusChangedOn");
			return (Criteria) this;
		}

		public Criteria andStatusChangedOnLike(String value) {
			addCriterion("status_changed_on like", value, "statusChangedOn");
			return (Criteria) this;
		}

		public Criteria andStatusChangedOnNotLike(String value) {
			addCriterion("status_changed_on not like", value, "statusChangedOn");
			return (Criteria) this;
		}

		public Criteria andStatusChangedOnIn(List<String> values) {
			addCriterion("status_changed_on in", values, "statusChangedOn");
			return (Criteria) this;
		}

		public Criteria andStatusChangedOnNotIn(List<String> values) {
			addCriterion("status_changed_on not in", values, "statusChangedOn");
			return (Criteria) this;
		}

		public Criteria andStatusChangedOnBetween(String value1, String value2) {
			addCriterion("status_changed_on between", value1, value2,
					"statusChangedOn");
			return (Criteria) this;
		}

		public Criteria andStatusChangedOnNotBetween(String value1,
				String value2) {
			addCriterion("status_changed_on not between", value1, value2,
					"statusChangedOn");
			return (Criteria) this;
		}

		public Criteria andCreatedAtIsNull() {
			addCriterion("created_at is null");
			return (Criteria) this;
		}

		public Criteria andCreatedAtIsNotNull() {
			addCriterion("created_at is not null");
			return (Criteria) this;
		}

		public Criteria andCreatedAtEqualTo(Date value) {
			addCriterion("created_at =", value, "createdAt");
			return (Criteria) this;
		}

		public Criteria andCreatedAtNotEqualTo(Date value) {
			addCriterion("created_at <>", value, "createdAt");
			return (Criteria) this;
		}

		public Criteria andCreatedAtGreaterThan(Date value) {
			addCriterion("created_at >", value, "createdAt");
			return (Criteria) this;
		}

		public Criteria andCreatedAtGreaterThanOrEqualTo(Date value) {
			addCriterion("created_at >=", value, "createdAt");
			return (Criteria) this;
		}

		public Criteria andCreatedAtLessThan(Date value) {
			addCriterion("created_at <", value, "createdAt");
			return (Criteria) this;
		}

		public Criteria andCreatedAtLessThanOrEqualTo(Date value) {
			addCriterion("created_at <=", value, "createdAt");
			return (Criteria) this;
		}

		public Criteria andCreatedAtIn(List<Date> values) {
			addCriterion("created_at in", values, "createdAt");
			return (Criteria) this;
		}

		public Criteria andCreatedAtNotIn(List<Date> values) {
			addCriterion("created_at not in", values, "createdAt");
			return (Criteria) this;
		}

		public Criteria andCreatedAtBetween(Date value1, Date value2) {
			addCriterion("created_at between", value1, value2, "createdAt");
			return (Criteria) this;
		}

		public Criteria andCreatedAtNotBetween(Date value1, Date value2) {
			addCriterion("created_at not between", value1, value2, "createdAt");
			return (Criteria) this;
		}

		public Criteria andUpdatedAtIsNull() {
			addCriterion("updated_at is null");
			return (Criteria) this;
		}

		public Criteria andUpdatedAtIsNotNull() {
			addCriterion("updated_at is not null");
			return (Criteria) this;
		}

		public Criteria andUpdatedAtEqualTo(Date value) {
			addCriterion("updated_at =", value, "updatedAt");
			return (Criteria) this;
		}

		public Criteria andUpdatedAtNotEqualTo(Date value) {
			addCriterion("updated_at <>", value, "updatedAt");
			return (Criteria) this;
		}

		public Criteria andUpdatedAtGreaterThan(Date value) {
			addCriterion("updated_at >", value, "updatedAt");
			return (Criteria) this;
		}

		public Criteria andUpdatedAtGreaterThanOrEqualTo(Date value) {
			addCriterion("updated_at >=", value, "updatedAt");
			return (Criteria) this;
		}

		public Criteria andUpdatedAtLessThan(Date value) {
			addCriterion("updated_at <", value, "updatedAt");
			return (Criteria) this;
		}

		public Criteria andUpdatedAtLessThanOrEqualTo(Date value) {
			addCriterion("updated_at <=", value, "updatedAt");
			return (Criteria) this;
		}

		public Criteria andUpdatedAtIn(List<Date> values) {
			addCriterion("updated_at in", values, "updatedAt");
			return (Criteria) this;
		}

		public Criteria andUpdatedAtNotIn(List<Date> values) {
			addCriterion("updated_at not in", values, "updatedAt");
			return (Criteria) this;
		}

		public Criteria andUpdatedAtBetween(Date value1, Date value2) {
			addCriterion("updated_at between", value1, value2, "updatedAt");
			return (Criteria) this;
		}

		public Criteria andUpdatedAtNotBetween(Date value1, Date value2) {
			addCriterion("updated_at not between", value1, value2, "updatedAt");
			return (Criteria) this;
		}
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table highrise_deals
	 * @mbggenerated  Tue Oct 29 13:42:10 GMT 2013
	 */
	public static class Criterion {
		private String condition;
		private Object value;
		private Object secondValue;
		private boolean noValue;
		private boolean singleValue;
		private boolean betweenValue;
		private boolean listValue;
		private String typeHandler;

		public String getCondition() {
			return condition;
		}

		public Object getValue() {
			return value;
		}

		public Object getSecondValue() {
			return secondValue;
		}

		public boolean isNoValue() {
			return noValue;
		}

		public boolean isSingleValue() {
			return singleValue;
		}

		public boolean isBetweenValue() {
			return betweenValue;
		}

		public boolean isListValue() {
			return listValue;
		}

		public String getTypeHandler() {
			return typeHandler;
		}

		protected Criterion(String condition) {
			super();
			this.condition = condition;
			this.typeHandler = null;
			this.noValue = true;
		}

		protected Criterion(String condition, Object value, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.typeHandler = typeHandler;
			if (value instanceof List<?>) {
				this.listValue = true;
			} else {
				this.singleValue = true;
			}
		}

		protected Criterion(String condition, Object value) {
			this(condition, value, null);
		}

		protected Criterion(String condition, Object value, Object secondValue,
				String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.secondValue = secondValue;
			this.typeHandler = typeHandler;
			this.betweenValue = true;
		}

		protected Criterion(String condition, Object value, Object secondValue) {
			this(condition, value, secondValue, null);
		}
	}

	/**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table highrise_deals
     *
     * @mbggenerated do_not_delete_during_merge Tue Oct 22 17:01:18 BST 2013
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }
}