package com.jemmmedia.organise.mybatis.db.mybatis.model;

public class HighriseDeals extends BaseModel {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column highrise_deals.deal_id
	 * @mbggenerated  Tue Oct 29 13:42:10 GMT 2013
	 */
	private Long dealId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column highrise_deals.account_id
	 * @mbggenerated  Tue Oct 29 13:42:10 GMT 2013
	 */
	private Long accountId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column highrise_deals.author_id
	 * @mbggenerated  Tue Oct 29 13:42:10 GMT 2013
	 */
	private Long authorId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column highrise_deals.category_id
	 * @mbggenerated  Tue Oct 29 13:42:10 GMT 2013
	 */
	private Long categoryId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column highrise_deals.currency
	 * @mbggenerated  Tue Oct 29 13:42:10 GMT 2013
	 */
	private String currency;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column highrise_deals.duration
	 * @mbggenerated  Tue Oct 29 13:42:10 GMT 2013
	 */
	private String duration;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column highrise_deals.name
	 * @mbggenerated  Tue Oct 29 13:42:10 GMT 2013
	 */
	private String name;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column highrise_deals.party_id
	 * @mbggenerated  Tue Oct 29 13:42:10 GMT 2013
	 */
	private Long partyId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column highrise_deals.price
	 * @mbggenerated  Tue Oct 29 13:42:10 GMT 2013
	 */
	private Integer price;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column highrise_deals.price_type
	 * @mbggenerated  Tue Oct 29 13:42:10 GMT 2013
	 */
	private String priceType;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column highrise_deals.responsible_party_id
	 * @mbggenerated  Tue Oct 29 13:42:10 GMT 2013
	 */
	private Long responsiblePartyId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column highrise_deals.status
	 * @mbggenerated  Tue Oct 29 13:42:10 GMT 2013
	 */
	private String status;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column highrise_deals.status_changed_on
	 * @mbggenerated  Tue Oct 29 13:42:10 GMT 2013
	 */
	private String statusChangedOn;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column highrise_deals.background
	 * @mbggenerated  Tue Oct 29 13:42:10 GMT 2013
	 */
	private String background;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column highrise_deals.deal_id
	 * @return  the value of highrise_deals.deal_id
	 * @mbggenerated  Tue Oct 29 13:42:10 GMT 2013
	 */
	public Long getDealId() {
		return dealId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column highrise_deals.deal_id
	 * @param dealId  the value for highrise_deals.deal_id
	 * @mbggenerated  Tue Oct 29 13:42:10 GMT 2013
	 */
	public void setDealId(Long dealId) {
		this.dealId = dealId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column highrise_deals.account_id
	 * @return  the value of highrise_deals.account_id
	 * @mbggenerated  Tue Oct 29 13:42:10 GMT 2013
	 */
	public Long getAccountId() {
		return accountId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column highrise_deals.account_id
	 * @param accountId  the value for highrise_deals.account_id
	 * @mbggenerated  Tue Oct 29 13:42:10 GMT 2013
	 */
	public void setAccountId(Long accountId) {
		this.accountId = accountId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column highrise_deals.author_id
	 * @return  the value of highrise_deals.author_id
	 * @mbggenerated  Tue Oct 29 13:42:10 GMT 2013
	 */
	public Long getAuthorId() {
		return authorId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column highrise_deals.author_id
	 * @param authorId  the value for highrise_deals.author_id
	 * @mbggenerated  Tue Oct 29 13:42:10 GMT 2013
	 */
	public void setAuthorId(Long authorId) {
		this.authorId = authorId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column highrise_deals.category_id
	 * @return  the value of highrise_deals.category_id
	 * @mbggenerated  Tue Oct 29 13:42:10 GMT 2013
	 */
	public Long getCategoryId() {
		return categoryId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column highrise_deals.category_id
	 * @param categoryId  the value for highrise_deals.category_id
	 * @mbggenerated  Tue Oct 29 13:42:10 GMT 2013
	 */
	public void setCategoryId(Long categoryId) {
		this.categoryId = categoryId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column highrise_deals.currency
	 * @return  the value of highrise_deals.currency
	 * @mbggenerated  Tue Oct 29 13:42:10 GMT 2013
	 */
	public String getCurrency() {
		return currency;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column highrise_deals.currency
	 * @param currency  the value for highrise_deals.currency
	 * @mbggenerated  Tue Oct 29 13:42:10 GMT 2013
	 */
	public void setCurrency(String currency) {
		this.currency = currency == null ? null : currency.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column highrise_deals.duration
	 * @return  the value of highrise_deals.duration
	 * @mbggenerated  Tue Oct 29 13:42:10 GMT 2013
	 */
	public String getDuration() {
		return duration;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column highrise_deals.duration
	 * @param duration  the value for highrise_deals.duration
	 * @mbggenerated  Tue Oct 29 13:42:10 GMT 2013
	 */
	public void setDuration(String duration) {
		this.duration = duration == null ? null : duration.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column highrise_deals.name
	 * @return  the value of highrise_deals.name
	 * @mbggenerated  Tue Oct 29 13:42:10 GMT 2013
	 */
	public String getName() {
		return name;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column highrise_deals.name
	 * @param name  the value for highrise_deals.name
	 * @mbggenerated  Tue Oct 29 13:42:10 GMT 2013
	 */
	public void setName(String name) {
		this.name = name == null ? null : name.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column highrise_deals.party_id
	 * @return  the value of highrise_deals.party_id
	 * @mbggenerated  Tue Oct 29 13:42:10 GMT 2013
	 */
	public Long getPartyId() {
		return partyId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column highrise_deals.party_id
	 * @param partyId  the value for highrise_deals.party_id
	 * @mbggenerated  Tue Oct 29 13:42:10 GMT 2013
	 */
	public void setPartyId(Long partyId) {
		this.partyId = partyId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column highrise_deals.price
	 * @return  the value of highrise_deals.price
	 * @mbggenerated  Tue Oct 29 13:42:10 GMT 2013
	 */
	public Integer getPrice() {
		return price;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column highrise_deals.price
	 * @param price  the value for highrise_deals.price
	 * @mbggenerated  Tue Oct 29 13:42:10 GMT 2013
	 */
	public void setPrice(Integer price) {
		this.price = price;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column highrise_deals.price_type
	 * @return  the value of highrise_deals.price_type
	 * @mbggenerated  Tue Oct 29 13:42:10 GMT 2013
	 */
	public String getPriceType() {
		return priceType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column highrise_deals.price_type
	 * @param priceType  the value for highrise_deals.price_type
	 * @mbggenerated  Tue Oct 29 13:42:10 GMT 2013
	 */
	public void setPriceType(String priceType) {
		this.priceType = priceType == null ? null : priceType.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column highrise_deals.responsible_party_id
	 * @return  the value of highrise_deals.responsible_party_id
	 * @mbggenerated  Tue Oct 29 13:42:10 GMT 2013
	 */
	public Long getResponsiblePartyId() {
		return responsiblePartyId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column highrise_deals.responsible_party_id
	 * @param responsiblePartyId  the value for highrise_deals.responsible_party_id
	 * @mbggenerated  Tue Oct 29 13:42:10 GMT 2013
	 */
	public void setResponsiblePartyId(Long responsiblePartyId) {
		this.responsiblePartyId = responsiblePartyId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column highrise_deals.status
	 * @return  the value of highrise_deals.status
	 * @mbggenerated  Tue Oct 29 13:42:10 GMT 2013
	 */
	public String getStatus() {
		return status;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column highrise_deals.status
	 * @param status  the value for highrise_deals.status
	 * @mbggenerated  Tue Oct 29 13:42:10 GMT 2013
	 */
	public void setStatus(String status) {
		this.status = status == null ? null : status.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column highrise_deals.status_changed_on
	 * @return  the value of highrise_deals.status_changed_on
	 * @mbggenerated  Tue Oct 29 13:42:10 GMT 2013
	 */
	public String getStatusChangedOn() {
		return statusChangedOn;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column highrise_deals.status_changed_on
	 * @param statusChangedOn  the value for highrise_deals.status_changed_on
	 * @mbggenerated  Tue Oct 29 13:42:10 GMT 2013
	 */
	public void setStatusChangedOn(String statusChangedOn) {
		this.statusChangedOn = statusChangedOn == null ? null : statusChangedOn
				.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column highrise_deals.background
	 * @return  the value of highrise_deals.background
	 * @mbggenerated  Tue Oct 29 13:42:10 GMT 2013
	 */
	public String getBackground() {
		return background;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column highrise_deals.background
	 * @param background  the value for highrise_deals.background
	 * @mbggenerated  Tue Oct 29 13:42:10 GMT 2013
	 */
	public void setBackground(String background) {
		this.background = background == null ? null : background.trim();
	}
}