package com.jemmmedia.organise.mybatis.db.mybatis.model;

public class HighriseParty extends BaseModel {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column highrise_party.party_id
	 * @mbggenerated  Tue Oct 29 13:42:10 GMT 2013
	 */
	private Long partyId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column highrise_party.avatar_url
	 * @mbggenerated  Tue Oct 29 13:42:10 GMT 2013
	 */
	private String avatarUrl;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column highrise_party.type
	 * @mbggenerated  Tue Oct 29 13:42:10 GMT 2013
	 */
	private String type;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column highrise_party.name
	 * @mbggenerated  Tue Oct 29 13:42:10 GMT 2013
	 */
	private String name;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column highrise_party.background
	 * @mbggenerated  Tue Oct 29 13:42:10 GMT 2013
	 */
	private String background;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column highrise_party.party_id
	 * @return  the value of highrise_party.party_id
	 * @mbggenerated  Tue Oct 29 13:42:10 GMT 2013
	 */
	public Long getPartyId() {
		return partyId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column highrise_party.party_id
	 * @param partyId  the value for highrise_party.party_id
	 * @mbggenerated  Tue Oct 29 13:42:10 GMT 2013
	 */
	public void setPartyId(Long partyId) {
		this.partyId = partyId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column highrise_party.avatar_url
	 * @return  the value of highrise_party.avatar_url
	 * @mbggenerated  Tue Oct 29 13:42:10 GMT 2013
	 */
	public String getAvatarUrl() {
		return avatarUrl;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column highrise_party.avatar_url
	 * @param avatarUrl  the value for highrise_party.avatar_url
	 * @mbggenerated  Tue Oct 29 13:42:10 GMT 2013
	 */
	public void setAvatarUrl(String avatarUrl) {
		this.avatarUrl = avatarUrl == null ? null : avatarUrl.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column highrise_party.type
	 * @return  the value of highrise_party.type
	 * @mbggenerated  Tue Oct 29 13:42:10 GMT 2013
	 */
	public String getType() {
		return type;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column highrise_party.type
	 * @param type  the value for highrise_party.type
	 * @mbggenerated  Tue Oct 29 13:42:10 GMT 2013
	 */
	public void setType(String type) {
		this.type = type == null ? null : type.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column highrise_party.name
	 * @return  the value of highrise_party.name
	 * @mbggenerated  Tue Oct 29 13:42:10 GMT 2013
	 */
	public String getName() {
		return name;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column highrise_party.name
	 * @param name  the value for highrise_party.name
	 * @mbggenerated  Tue Oct 29 13:42:10 GMT 2013
	 */
	public void setName(String name) {
		this.name = name == null ? null : name.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column highrise_party.background
	 * @return  the value of highrise_party.background
	 * @mbggenerated  Tue Oct 29 13:42:10 GMT 2013
	 */
	public String getBackground() {
		return background;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column highrise_party.background
	 * @param background  the value for highrise_party.background
	 * @mbggenerated  Tue Oct 29 13:42:10 GMT 2013
	 */
	public void setBackground(String background) {
		this.background = background == null ? null : background.trim();
	}
}