package com.jemmmedia.organise.mybatis.db.mybatis.model;

public class HighriseUsers extends BaseModel {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column highrise_users.user_id
	 * @mbggenerated  Tue Oct 29 13:42:10 GMT 2013
	 */
	private Long userId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column highrise_users.name
	 * @mbggenerated  Tue Oct 29 13:42:10 GMT 2013
	 */
	private String name;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column highrise_users.email
	 * @mbggenerated  Tue Oct 29 13:42:10 GMT 2013
	 */
	private String email;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column highrise_users.user_id
	 * @return  the value of highrise_users.user_id
	 * @mbggenerated  Tue Oct 29 13:42:10 GMT 2013
	 */
	public Long getUserId() {
		return userId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column highrise_users.user_id
	 * @param userId  the value for highrise_users.user_id
	 * @mbggenerated  Tue Oct 29 13:42:10 GMT 2013
	 */
	public void setUserId(Long userId) {
		this.userId = userId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column highrise_users.name
	 * @return  the value of highrise_users.name
	 * @mbggenerated  Tue Oct 29 13:42:10 GMT 2013
	 */
	public String getName() {
		return name;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column highrise_users.name
	 * @param name  the value for highrise_users.name
	 * @mbggenerated  Tue Oct 29 13:42:10 GMT 2013
	 */
	public void setName(String name) {
		this.name = name == null ? null : name.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column highrise_users.email
	 * @return  the value of highrise_users.email
	 * @mbggenerated  Tue Oct 29 13:42:10 GMT 2013
	 */
	public String getEmail() {
		return email;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column highrise_users.email
	 * @param email  the value for highrise_users.email
	 * @mbggenerated  Tue Oct 29 13:42:10 GMT 2013
	 */
	public void setEmail(String email) {
		this.email = email == null ? null : email.trim();
	}
}