package com.jemmmedia.organise.mybatis.db.mybatis.model;

import java.util.Date;

public class Note extends BaseModel {
   
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column notes.date
     *
     * @mbggenerated Mon Aug 06 10:08:53 BST 2012
     */
    private Date date;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column notes.publisher_id
     *
     * @mbggenerated Mon Aug 06 10:08:53 BST 2012
     */
    private Integer publisherId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column notes.advertiser_id
     *
     * @mbggenerated Mon Aug 06 10:08:53 BST 2012
     */
    private Integer advertiserId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column notes.creator_id
     *
     * @mbggenerated Mon Aug 06 10:08:53 BST 2012
     */
    private Integer creatorId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column notes.updater_id
     *
     * @mbggenerated Mon Aug 06 10:08:53 BST 2012
     */
    private Integer updaterId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column notes.campaign_id
     *
     * @mbggenerated Mon Aug 06 10:08:53 BST 2012
     */
    private Integer campaignId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column notes.invoice_id
     *
     * @mbggenerated Mon Aug 06 10:08:53 BST 2012
     */
    private Integer invoiceId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column notes.category_id
     *
     * @mbggenerated Mon Aug 06 10:08:53 BST 2012
     */
    private Integer categoryId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column notes.parent_id
     *
     * @mbggenerated Mon Aug 06 10:08:53 BST 2012
     */
    private Integer parentId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column notes.noticeable_id
     *
     * @mbggenerated Mon Aug 06 10:08:53 BST 2012
     */
    private Integer noticeableId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column notes.noticeable_type
     *
     * @mbggenerated Mon Aug 06 10:08:53 BST 2012
     */
    private String noticeableType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column notes.note
     *
     * @mbggenerated Mon Aug 06 10:08:53 BST 2012
     */
    private String note;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column notes.date
     *
     * @return the value of notes.date
     *
     * @mbggenerated Mon Aug 06 10:08:53 BST 2012
     */
    public Date getDate() {
        return date;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column notes.date
     *
     * @param date the value for notes.date
     *
     * @mbggenerated Mon Aug 06 10:08:53 BST 2012
     */
    public void setDate(Date date) {
        this.date = date;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column notes.publisher_id
     *
     * @return the value of notes.publisher_id
     *
     * @mbggenerated Mon Aug 06 10:08:53 BST 2012
     */
    public Integer getPublisherId() {
        return publisherId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column notes.publisher_id
     *
     * @param publisherId the value for notes.publisher_id
     *
     * @mbggenerated Mon Aug 06 10:08:53 BST 2012
     */
    public void setPublisherId(Integer publisherId) {
        this.publisherId = publisherId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column notes.advertiser_id
     *
     * @return the value of notes.advertiser_id
     *
     * @mbggenerated Mon Aug 06 10:08:53 BST 2012
     */
    public Integer getAdvertiserId() {
        return advertiserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column notes.advertiser_id
     *
     * @param advertiserId the value for notes.advertiser_id
     *
     * @mbggenerated Mon Aug 06 10:08:53 BST 2012
     */
    public void setAdvertiserId(Integer advertiserId) {
        this.advertiserId = advertiserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column notes.creator_id
     *
     * @return the value of notes.creator_id
     *
     * @mbggenerated Mon Aug 06 10:08:53 BST 2012
     */
    public Integer getCreatorId() {
        return creatorId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column notes.creator_id
     *
     * @param creatorId the value for notes.creator_id
     *
     * @mbggenerated Mon Aug 06 10:08:53 BST 2012
     */
    public void setCreatorId(Integer creatorId) {
        this.creatorId = creatorId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column notes.updater_id
     *
     * @return the value of notes.updater_id
     *
     * @mbggenerated Mon Aug 06 10:08:53 BST 2012
     */
    public Integer getUpdaterId() {
        return updaterId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column notes.updater_id
     *
     * @param updaterId the value for notes.updater_id
     *
     * @mbggenerated Mon Aug 06 10:08:53 BST 2012
     */
    public void setUpdaterId(Integer updaterId) {
        this.updaterId = updaterId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column notes.campaign_id
     *
     * @return the value of notes.campaign_id
     *
     * @mbggenerated Mon Aug 06 10:08:53 BST 2012
     */
    public Integer getCampaignId() {
        return campaignId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column notes.campaign_id
     *
     * @param campaignId the value for notes.campaign_id
     *
     * @mbggenerated Mon Aug 06 10:08:53 BST 2012
     */
    public void setCampaignId(Integer campaignId) {
        this.campaignId = campaignId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column notes.invoice_id
     *
     * @return the value of notes.invoice_id
     *
     * @mbggenerated Mon Aug 06 10:08:53 BST 2012
     */
    public Integer getInvoiceId() {
        return invoiceId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column notes.invoice_id
     *
     * @param invoiceId the value for notes.invoice_id
     *
     * @mbggenerated Mon Aug 06 10:08:53 BST 2012
     */
    public void setInvoiceId(Integer invoiceId) {
        this.invoiceId = invoiceId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column notes.category_id
     *
     * @return the value of notes.category_id
     *
     * @mbggenerated Mon Aug 06 10:08:53 BST 2012
     */
    public Integer getCategoryId() {
        return categoryId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column notes.category_id
     *
     * @param categoryId the value for notes.category_id
     *
     * @mbggenerated Mon Aug 06 10:08:53 BST 2012
     */
    public void setCategoryId(Integer categoryId) {
        this.categoryId = categoryId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column notes.parent_id
     *
     * @return the value of notes.parent_id
     *
     * @mbggenerated Mon Aug 06 10:08:53 BST 2012
     */
    public Integer getParentId() {
        return parentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column notes.parent_id
     *
     * @param parentId the value for notes.parent_id
     *
     * @mbggenerated Mon Aug 06 10:08:53 BST 2012
     */
    public void setParentId(Integer parentId) {
        this.parentId = parentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column notes.noticeable_id
     *
     * @return the value of notes.noticeable_id
     *
     * @mbggenerated Mon Aug 06 10:08:53 BST 2012
     */
    public Integer getNoticeableId() {
        return noticeableId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column notes.noticeable_id
     *
     * @param noticeableId the value for notes.noticeable_id
     *
     * @mbggenerated Mon Aug 06 10:08:53 BST 2012
     */
    public void setNoticeableId(Integer noticeableId) {
        this.noticeableId = noticeableId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column notes.noticeable_type
     *
     * @return the value of notes.noticeable_type
     *
     * @mbggenerated Mon Aug 06 10:08:53 BST 2012
     */
    public String getNoticeableType() {
        return noticeableType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column notes.noticeable_type
     *
     * @param noticeableType the value for notes.noticeable_type
     *
     * @mbggenerated Mon Aug 06 10:08:53 BST 2012
     */
    public void setNoticeableType(String noticeableType) {
        this.noticeableType = noticeableType == null ? null : noticeableType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column notes.note
     *
     * @return the value of notes.note
     *
     * @mbggenerated Mon Aug 06 10:08:53 BST 2012
     */
    public String getNote() {
        return note;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column notes.note
     *
     * @param note the value for notes.note
     *
     * @mbggenerated Mon Aug 06 10:08:53 BST 2012
     */
    public void setNote(String note) {
        this.note = note == null ? null : note.trim();
    }
}