package com.jemmmedia.organise.mybatis.db.mybatis.model;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class OrdersExample {
    /**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table orders
	 * @mbggenerated  Thu May 30 11:43:05 BST 2013
	 */
	protected String orderByClause;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table orders
	 * @mbggenerated  Thu May 30 11:43:05 BST 2013
	 */
	protected boolean distinct;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table orders
	 * @mbggenerated  Thu May 30 11:43:05 BST 2013
	 */
	protected List<Criteria> oredCriteria;

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table orders
	 * @mbggenerated  Thu May 30 11:43:05 BST 2013
	 */
	public OrdersExample() {
		oredCriteria = new ArrayList<Criteria>();
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table orders
	 * @mbggenerated  Thu May 30 11:43:05 BST 2013
	 */
	public void setOrderByClause(String orderByClause) {
		this.orderByClause = orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table orders
	 * @mbggenerated  Thu May 30 11:43:05 BST 2013
	 */
	public String getOrderByClause() {
		return orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table orders
	 * @mbggenerated  Thu May 30 11:43:05 BST 2013
	 */
	public void setDistinct(boolean distinct) {
		this.distinct = distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table orders
	 * @mbggenerated  Thu May 30 11:43:05 BST 2013
	 */
	public boolean isDistinct() {
		return distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table orders
	 * @mbggenerated  Thu May 30 11:43:05 BST 2013
	 */
	public List<Criteria> getOredCriteria() {
		return oredCriteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table orders
	 * @mbggenerated  Thu May 30 11:43:05 BST 2013
	 */
	public void or(Criteria criteria) {
		oredCriteria.add(criteria);
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table orders
	 * @mbggenerated  Thu May 30 11:43:05 BST 2013
	 */
	public Criteria or() {
		Criteria criteria = createCriteriaInternal();
		oredCriteria.add(criteria);
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table orders
	 * @mbggenerated  Thu May 30 11:43:05 BST 2013
	 */
	public Criteria createCriteria() {
		Criteria criteria = createCriteriaInternal();
		if (oredCriteria.size() == 0) {
			oredCriteria.add(criteria);
		}
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table orders
	 * @mbggenerated  Thu May 30 11:43:05 BST 2013
	 */
	protected Criteria createCriteriaInternal() {
		Criteria criteria = new Criteria();
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table orders
	 * @mbggenerated  Thu May 30 11:43:05 BST 2013
	 */
	public void clear() {
		oredCriteria.clear();
		orderByClause = null;
		distinct = false;
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table orders
	 * @mbggenerated  Thu May 30 11:43:05 BST 2013
	 */
	protected abstract static class GeneratedCriteria {
		protected List<Criterion> criteria;

		protected GeneratedCriteria() {
			super();
			criteria = new ArrayList<Criterion>();
		}

		public boolean isValid() {
			return criteria.size() > 0;
		}

		public List<Criterion> getAllCriteria() {
			return criteria;
		}

		public List<Criterion> getCriteria() {
			return criteria;
		}

		protected void addCriterion(String condition) {
			if (condition == null) {
				throw new RuntimeException("Value for condition cannot be null");
			}
			criteria.add(new Criterion(condition));
		}

		protected void addCriterion(String condition, Object value,
				String property) {
			if (value == null) {
				throw new RuntimeException("Value for " + property
						+ " cannot be null");
			}
			criteria.add(new Criterion(condition, value));
		}

		protected void addCriterion(String condition, Object value1,
				Object value2, String property) {
			if (value1 == null || value2 == null) {
				throw new RuntimeException("Between values for " + property
						+ " cannot be null");
			}
			criteria.add(new Criterion(condition, value1, value2));
		}

		public Criteria andIdIsNull() {
			addCriterion("id is null");
			return (Criteria) this;
		}

		public Criteria andIdIsNotNull() {
			addCriterion("id is not null");
			return (Criteria) this;
		}

		public Criteria andIdEqualTo(Long value) {
			addCriterion("id =", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdNotEqualTo(Long value) {
			addCriterion("id <>", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdGreaterThan(Long value) {
			addCriterion("id >", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdGreaterThanOrEqualTo(Long value) {
			addCriterion("id >=", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdLessThan(Long value) {
			addCriterion("id <", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdLessThanOrEqualTo(Long value) {
			addCriterion("id <=", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdIn(List<Long> values) {
			addCriterion("id in", values, "id");
			return (Criteria) this;
		}

		public Criteria andIdNotIn(List<Long> values) {
			addCriterion("id not in", values, "id");
			return (Criteria) this;
		}

		public Criteria andIdBetween(Long value1, Long value2) {
			addCriterion("id between", value1, value2, "id");
			return (Criteria) this;
		}

		public Criteria andIdNotBetween(Long value1, Long value2) {
			addCriterion("id not between", value1, value2, "id");
			return (Criteria) this;
		}

		public Criteria andTransectionIdIsNull() {
			addCriterion("transection_id is null");
			return (Criteria) this;
		}

		public Criteria andTransectionIdIsNotNull() {
			addCriterion("transection_id is not null");
			return (Criteria) this;
		}

		public Criteria andTransectionIdEqualTo(String value) {
			addCriterion("transection_id =", value, "transectionId");
			return (Criteria) this;
		}

		public Criteria andTransectionIdNotEqualTo(String value) {
			addCriterion("transection_id <>", value, "transectionId");
			return (Criteria) this;
		}

		public Criteria andTransectionIdGreaterThan(String value) {
			addCriterion("transection_id >", value, "transectionId");
			return (Criteria) this;
		}

		public Criteria andTransectionIdGreaterThanOrEqualTo(String value) {
			addCriterion("transection_id >=", value, "transectionId");
			return (Criteria) this;
		}

		public Criteria andTransectionIdLessThan(String value) {
			addCriterion("transection_id <", value, "transectionId");
			return (Criteria) this;
		}

		public Criteria andTransectionIdLessThanOrEqualTo(String value) {
			addCriterion("transection_id <=", value, "transectionId");
			return (Criteria) this;
		}

		public Criteria andTransectionIdLike(String value) {
			addCriterion("transection_id like", value, "transectionId");
			return (Criteria) this;
		}

		public Criteria andTransectionIdNotLike(String value) {
			addCriterion("transection_id not like", value, "transectionId");
			return (Criteria) this;
		}

		public Criteria andTransectionIdIn(List<String> values) {
			addCriterion("transection_id in", values, "transectionId");
			return (Criteria) this;
		}

		public Criteria andTransectionIdNotIn(List<String> values) {
			addCriterion("transection_id not in", values, "transectionId");
			return (Criteria) this;
		}

		public Criteria andTransectionIdBetween(String value1, String value2) {
			addCriterion("transection_id between", value1, value2,
					"transectionId");
			return (Criteria) this;
		}

		public Criteria andTransectionIdNotBetween(String value1, String value2) {
			addCriterion("transection_id not between", value1, value2,
					"transectionId");
			return (Criteria) this;
		}

		public Criteria andAmountIsNull() {
			addCriterion("amount is null");
			return (Criteria) this;
		}

		public Criteria andAmountIsNotNull() {
			addCriterion("amount is not null");
			return (Criteria) this;
		}

		public Criteria andAmountEqualTo(String value) {
			addCriterion("amount =", value, "amount");
			return (Criteria) this;
		}

		public Criteria andAmountNotEqualTo(String value) {
			addCriterion("amount <>", value, "amount");
			return (Criteria) this;
		}

		public Criteria andAmountGreaterThan(String value) {
			addCriterion("amount >", value, "amount");
			return (Criteria) this;
		}

		public Criteria andAmountGreaterThanOrEqualTo(String value) {
			addCriterion("amount >=", value, "amount");
			return (Criteria) this;
		}

		public Criteria andAmountLessThan(String value) {
			addCriterion("amount <", value, "amount");
			return (Criteria) this;
		}

		public Criteria andAmountLessThanOrEqualTo(String value) {
			addCriterion("amount <=", value, "amount");
			return (Criteria) this;
		}

		public Criteria andAmountLike(String value) {
			addCriterion("amount like", value, "amount");
			return (Criteria) this;
		}

		public Criteria andAmountNotLike(String value) {
			addCriterion("amount not like", value, "amount");
			return (Criteria) this;
		}

		public Criteria andAmountIn(List<String> values) {
			addCriterion("amount in", values, "amount");
			return (Criteria) this;
		}

		public Criteria andAmountNotIn(List<String> values) {
			addCriterion("amount not in", values, "amount");
			return (Criteria) this;
		}

		public Criteria andAmountBetween(String value1, String value2) {
			addCriterion("amount between", value1, value2, "amount");
			return (Criteria) this;
		}

		public Criteria andAmountNotBetween(String value1, String value2) {
			addCriterion("amount not between", value1, value2, "amount");
			return (Criteria) this;
		}

		public Criteria andItemNameIsNull() {
			addCriterion("item_name is null");
			return (Criteria) this;
		}

		public Criteria andItemNameIsNotNull() {
			addCriterion("item_name is not null");
			return (Criteria) this;
		}

		public Criteria andItemNameEqualTo(String value) {
			addCriterion("item_name =", value, "itemName");
			return (Criteria) this;
		}

		public Criteria andItemNameNotEqualTo(String value) {
			addCriterion("item_name <>", value, "itemName");
			return (Criteria) this;
		}

		public Criteria andItemNameGreaterThan(String value) {
			addCriterion("item_name >", value, "itemName");
			return (Criteria) this;
		}

		public Criteria andItemNameGreaterThanOrEqualTo(String value) {
			addCriterion("item_name >=", value, "itemName");
			return (Criteria) this;
		}

		public Criteria andItemNameLessThan(String value) {
			addCriterion("item_name <", value, "itemName");
			return (Criteria) this;
		}

		public Criteria andItemNameLessThanOrEqualTo(String value) {
			addCriterion("item_name <=", value, "itemName");
			return (Criteria) this;
		}

		public Criteria andItemNameLike(String value) {
			addCriterion("item_name like", value, "itemName");
			return (Criteria) this;
		}

		public Criteria andItemNameNotLike(String value) {
			addCriterion("item_name not like", value, "itemName");
			return (Criteria) this;
		}

		public Criteria andItemNameIn(List<String> values) {
			addCriterion("item_name in", values, "itemName");
			return (Criteria) this;
		}

		public Criteria andItemNameNotIn(List<String> values) {
			addCriterion("item_name not in", values, "itemName");
			return (Criteria) this;
		}

		public Criteria andItemNameBetween(String value1, String value2) {
			addCriterion("item_name between", value1, value2, "itemName");
			return (Criteria) this;
		}

		public Criteria andItemNameNotBetween(String value1, String value2) {
			addCriterion("item_name not between", value1, value2, "itemName");
			return (Criteria) this;
		}

		public Criteria andItemNumberIsNull() {
			addCriterion("item_number is null");
			return (Criteria) this;
		}

		public Criteria andItemNumberIsNotNull() {
			addCriterion("item_number is not null");
			return (Criteria) this;
		}

		public Criteria andItemNumberEqualTo(String value) {
			addCriterion("item_number =", value, "itemNumber");
			return (Criteria) this;
		}

		public Criteria andItemNumberNotEqualTo(String value) {
			addCriterion("item_number <>", value, "itemNumber");
			return (Criteria) this;
		}

		public Criteria andItemNumberGreaterThan(String value) {
			addCriterion("item_number >", value, "itemNumber");
			return (Criteria) this;
		}

		public Criteria andItemNumberGreaterThanOrEqualTo(String value) {
			addCriterion("item_number >=", value, "itemNumber");
			return (Criteria) this;
		}

		public Criteria andItemNumberLessThan(String value) {
			addCriterion("item_number <", value, "itemNumber");
			return (Criteria) this;
		}

		public Criteria andItemNumberLessThanOrEqualTo(String value) {
			addCriterion("item_number <=", value, "itemNumber");
			return (Criteria) this;
		}

		public Criteria andItemNumberLike(String value) {
			addCriterion("item_number like", value, "itemNumber");
			return (Criteria) this;
		}

		public Criteria andItemNumberNotLike(String value) {
			addCriterion("item_number not like", value, "itemNumber");
			return (Criteria) this;
		}

		public Criteria andItemNumberIn(List<String> values) {
			addCriterion("item_number in", values, "itemNumber");
			return (Criteria) this;
		}

		public Criteria andItemNumberNotIn(List<String> values) {
			addCriterion("item_number not in", values, "itemNumber");
			return (Criteria) this;
		}

		public Criteria andItemNumberBetween(String value1, String value2) {
			addCriterion("item_number between", value1, value2, "itemNumber");
			return (Criteria) this;
		}

		public Criteria andItemNumberNotBetween(String value1, String value2) {
			addCriterion("item_number not between", value1, value2,
					"itemNumber");
			return (Criteria) this;
		}

		public Criteria andFirstNameIsNull() {
			addCriterion("first_name is null");
			return (Criteria) this;
		}

		public Criteria andFirstNameIsNotNull() {
			addCriterion("first_name is not null");
			return (Criteria) this;
		}

		public Criteria andFirstNameEqualTo(String value) {
			addCriterion("first_name =", value, "firstName");
			return (Criteria) this;
		}

		public Criteria andFirstNameNotEqualTo(String value) {
			addCriterion("first_name <>", value, "firstName");
			return (Criteria) this;
		}

		public Criteria andFirstNameGreaterThan(String value) {
			addCriterion("first_name >", value, "firstName");
			return (Criteria) this;
		}

		public Criteria andFirstNameGreaterThanOrEqualTo(String value) {
			addCriterion("first_name >=", value, "firstName");
			return (Criteria) this;
		}

		public Criteria andFirstNameLessThan(String value) {
			addCriterion("first_name <", value, "firstName");
			return (Criteria) this;
		}

		public Criteria andFirstNameLessThanOrEqualTo(String value) {
			addCriterion("first_name <=", value, "firstName");
			return (Criteria) this;
		}

		public Criteria andFirstNameLike(String value) {
			addCriterion("first_name like", value, "firstName");
			return (Criteria) this;
		}

		public Criteria andFirstNameNotLike(String value) {
			addCriterion("first_name not like", value, "firstName");
			return (Criteria) this;
		}

		public Criteria andFirstNameIn(List<String> values) {
			addCriterion("first_name in", values, "firstName");
			return (Criteria) this;
		}

		public Criteria andFirstNameNotIn(List<String> values) {
			addCriterion("first_name not in", values, "firstName");
			return (Criteria) this;
		}

		public Criteria andFirstNameBetween(String value1, String value2) {
			addCriterion("first_name between", value1, value2, "firstName");
			return (Criteria) this;
		}

		public Criteria andFirstNameNotBetween(String value1, String value2) {
			addCriterion("first_name not between", value1, value2, "firstName");
			return (Criteria) this;
		}

		public Criteria andLastNameIsNull() {
			addCriterion("last_name is null");
			return (Criteria) this;
		}

		public Criteria andLastNameIsNotNull() {
			addCriterion("last_name is not null");
			return (Criteria) this;
		}

		public Criteria andLastNameEqualTo(String value) {
			addCriterion("last_name =", value, "lastName");
			return (Criteria) this;
		}

		public Criteria andLastNameNotEqualTo(String value) {
			addCriterion("last_name <>", value, "lastName");
			return (Criteria) this;
		}

		public Criteria andLastNameGreaterThan(String value) {
			addCriterion("last_name >", value, "lastName");
			return (Criteria) this;
		}

		public Criteria andLastNameGreaterThanOrEqualTo(String value) {
			addCriterion("last_name >=", value, "lastName");
			return (Criteria) this;
		}

		public Criteria andLastNameLessThan(String value) {
			addCriterion("last_name <", value, "lastName");
			return (Criteria) this;
		}

		public Criteria andLastNameLessThanOrEqualTo(String value) {
			addCriterion("last_name <=", value, "lastName");
			return (Criteria) this;
		}

		public Criteria andLastNameLike(String value) {
			addCriterion("last_name like", value, "lastName");
			return (Criteria) this;
		}

		public Criteria andLastNameNotLike(String value) {
			addCriterion("last_name not like", value, "lastName");
			return (Criteria) this;
		}

		public Criteria andLastNameIn(List<String> values) {
			addCriterion("last_name in", values, "lastName");
			return (Criteria) this;
		}

		public Criteria andLastNameNotIn(List<String> values) {
			addCriterion("last_name not in", values, "lastName");
			return (Criteria) this;
		}

		public Criteria andLastNameBetween(String value1, String value2) {
			addCriterion("last_name between", value1, value2, "lastName");
			return (Criteria) this;
		}

		public Criteria andLastNameNotBetween(String value1, String value2) {
			addCriterion("last_name not between", value1, value2, "lastName");
			return (Criteria) this;
		}

		public Criteria andPayerEmailIsNull() {
			addCriterion("payer_email is null");
			return (Criteria) this;
		}

		public Criteria andPayerEmailIsNotNull() {
			addCriterion("payer_email is not null");
			return (Criteria) this;
		}

		public Criteria andPayerEmailEqualTo(String value) {
			addCriterion("payer_email =", value, "payerEmail");
			return (Criteria) this;
		}

		public Criteria andPayerEmailNotEqualTo(String value) {
			addCriterion("payer_email <>", value, "payerEmail");
			return (Criteria) this;
		}

		public Criteria andPayerEmailGreaterThan(String value) {
			addCriterion("payer_email >", value, "payerEmail");
			return (Criteria) this;
		}

		public Criteria andPayerEmailGreaterThanOrEqualTo(String value) {
			addCriterion("payer_email >=", value, "payerEmail");
			return (Criteria) this;
		}

		public Criteria andPayerEmailLessThan(String value) {
			addCriterion("payer_email <", value, "payerEmail");
			return (Criteria) this;
		}

		public Criteria andPayerEmailLessThanOrEqualTo(String value) {
			addCriterion("payer_email <=", value, "payerEmail");
			return (Criteria) this;
		}

		public Criteria andPayerEmailLike(String value) {
			addCriterion("payer_email like", value, "payerEmail");
			return (Criteria) this;
		}

		public Criteria andPayerEmailNotLike(String value) {
			addCriterion("payer_email not like", value, "payerEmail");
			return (Criteria) this;
		}

		public Criteria andPayerEmailIn(List<String> values) {
			addCriterion("payer_email in", values, "payerEmail");
			return (Criteria) this;
		}

		public Criteria andPayerEmailNotIn(List<String> values) {
			addCriterion("payer_email not in", values, "payerEmail");
			return (Criteria) this;
		}

		public Criteria andPayerEmailBetween(String value1, String value2) {
			addCriterion("payer_email between", value1, value2, "payerEmail");
			return (Criteria) this;
		}

		public Criteria andPayerEmailNotBetween(String value1, String value2) {
			addCriterion("payer_email not between", value1, value2,
					"payerEmail");
			return (Criteria) this;
		}

		public Criteria andPayerIdIsNull() {
			addCriterion("payer_id is null");
			return (Criteria) this;
		}

		public Criteria andPayerIdIsNotNull() {
			addCriterion("payer_id is not null");
			return (Criteria) this;
		}

		public Criteria andPayerIdEqualTo(String value) {
			addCriterion("payer_id =", value, "payerId");
			return (Criteria) this;
		}

		public Criteria andPayerIdNotEqualTo(String value) {
			addCriterion("payer_id <>", value, "payerId");
			return (Criteria) this;
		}

		public Criteria andPayerIdGreaterThan(String value) {
			addCriterion("payer_id >", value, "payerId");
			return (Criteria) this;
		}

		public Criteria andPayerIdGreaterThanOrEqualTo(String value) {
			addCriterion("payer_id >=", value, "payerId");
			return (Criteria) this;
		}

		public Criteria andPayerIdLessThan(String value) {
			addCriterion("payer_id <", value, "payerId");
			return (Criteria) this;
		}

		public Criteria andPayerIdLessThanOrEqualTo(String value) {
			addCriterion("payer_id <=", value, "payerId");
			return (Criteria) this;
		}

		public Criteria andPayerIdLike(String value) {
			addCriterion("payer_id like", value, "payerId");
			return (Criteria) this;
		}

		public Criteria andPayerIdNotLike(String value) {
			addCriterion("payer_id not like", value, "payerId");
			return (Criteria) this;
		}

		public Criteria andPayerIdIn(List<String> values) {
			addCriterion("payer_id in", values, "payerId");
			return (Criteria) this;
		}

		public Criteria andPayerIdNotIn(List<String> values) {
			addCriterion("payer_id not in", values, "payerId");
			return (Criteria) this;
		}

		public Criteria andPayerIdBetween(String value1, String value2) {
			addCriterion("payer_id between", value1, value2, "payerId");
			return (Criteria) this;
		}

		public Criteria andPayerIdNotBetween(String value1, String value2) {
			addCriterion("payer_id not between", value1, value2, "payerId");
			return (Criteria) this;
		}

		public Criteria andPayerStatusIsNull() {
			addCriterion("payer_status is null");
			return (Criteria) this;
		}

		public Criteria andPayerStatusIsNotNull() {
			addCriterion("payer_status is not null");
			return (Criteria) this;
		}

		public Criteria andPayerStatusEqualTo(String value) {
			addCriterion("payer_status =", value, "payerStatus");
			return (Criteria) this;
		}

		public Criteria andPayerStatusNotEqualTo(String value) {
			addCriterion("payer_status <>", value, "payerStatus");
			return (Criteria) this;
		}

		public Criteria andPayerStatusGreaterThan(String value) {
			addCriterion("payer_status >", value, "payerStatus");
			return (Criteria) this;
		}

		public Criteria andPayerStatusGreaterThanOrEqualTo(String value) {
			addCriterion("payer_status >=", value, "payerStatus");
			return (Criteria) this;
		}

		public Criteria andPayerStatusLessThan(String value) {
			addCriterion("payer_status <", value, "payerStatus");
			return (Criteria) this;
		}

		public Criteria andPayerStatusLessThanOrEqualTo(String value) {
			addCriterion("payer_status <=", value, "payerStatus");
			return (Criteria) this;
		}

		public Criteria andPayerStatusLike(String value) {
			addCriterion("payer_status like", value, "payerStatus");
			return (Criteria) this;
		}

		public Criteria andPayerStatusNotLike(String value) {
			addCriterion("payer_status not like", value, "payerStatus");
			return (Criteria) this;
		}

		public Criteria andPayerStatusIn(List<String> values) {
			addCriterion("payer_status in", values, "payerStatus");
			return (Criteria) this;
		}

		public Criteria andPayerStatusNotIn(List<String> values) {
			addCriterion("payer_status not in", values, "payerStatus");
			return (Criteria) this;
		}

		public Criteria andPayerStatusBetween(String value1, String value2) {
			addCriterion("payer_status between", value1, value2, "payerStatus");
			return (Criteria) this;
		}

		public Criteria andPayerStatusNotBetween(String value1, String value2) {
			addCriterion("payer_status not between", value1, value2,
					"payerStatus");
			return (Criteria) this;
		}

		public Criteria andPeriodIsNull() {
			addCriterion("period is null");
			return (Criteria) this;
		}

		public Criteria andPeriodIsNotNull() {
			addCriterion("period is not null");
			return (Criteria) this;
		}

		public Criteria andPeriodEqualTo(String value) {
			addCriterion("period =", value, "period");
			return (Criteria) this;
		}

		public Criteria andPeriodNotEqualTo(String value) {
			addCriterion("period <>", value, "period");
			return (Criteria) this;
		}

		public Criteria andPeriodGreaterThan(String value) {
			addCriterion("period >", value, "period");
			return (Criteria) this;
		}

		public Criteria andPeriodGreaterThanOrEqualTo(String value) {
			addCriterion("period >=", value, "period");
			return (Criteria) this;
		}

		public Criteria andPeriodLessThan(String value) {
			addCriterion("period <", value, "period");
			return (Criteria) this;
		}

		public Criteria andPeriodLessThanOrEqualTo(String value) {
			addCriterion("period <=", value, "period");
			return (Criteria) this;
		}

		public Criteria andPeriodLike(String value) {
			addCriterion("period like", value, "period");
			return (Criteria) this;
		}

		public Criteria andPeriodNotLike(String value) {
			addCriterion("period not like", value, "period");
			return (Criteria) this;
		}

		public Criteria andPeriodIn(List<String> values) {
			addCriterion("period in", values, "period");
			return (Criteria) this;
		}

		public Criteria andPeriodNotIn(List<String> values) {
			addCriterion("period not in", values, "period");
			return (Criteria) this;
		}

		public Criteria andPeriodBetween(String value1, String value2) {
			addCriterion("period between", value1, value2, "period");
			return (Criteria) this;
		}

		public Criteria andPeriodNotBetween(String value1, String value2) {
			addCriterion("period not between", value1, value2, "period");
			return (Criteria) this;
		}

		public Criteria andSubscrDateIsNull() {
			addCriterion("subscr_date is null");
			return (Criteria) this;
		}

		public Criteria andSubscrDateIsNotNull() {
			addCriterion("subscr_date is not null");
			return (Criteria) this;
		}

		public Criteria andSubscrDateEqualTo(Date value) {
			addCriterion("subscr_date =", value, "subscrDate");
			return (Criteria) this;
		}

		public Criteria andSubscrDateNotEqualTo(Date value) {
			addCriterion("subscr_date <>", value, "subscrDate");
			return (Criteria) this;
		}

		public Criteria andSubscrDateGreaterThan(Date value) {
			addCriterion("subscr_date >", value, "subscrDate");
			return (Criteria) this;
		}

		public Criteria andSubscrDateGreaterThanOrEqualTo(Date value) {
			addCriterion("subscr_date >=", value, "subscrDate");
			return (Criteria) this;
		}

		public Criteria andSubscrDateLessThan(Date value) {
			addCriterion("subscr_date <", value, "subscrDate");
			return (Criteria) this;
		}

		public Criteria andSubscrDateLessThanOrEqualTo(Date value) {
			addCriterion("subscr_date <=", value, "subscrDate");
			return (Criteria) this;
		}

		public Criteria andSubscrDateIn(List<Date> values) {
			addCriterion("subscr_date in", values, "subscrDate");
			return (Criteria) this;
		}

		public Criteria andSubscrDateNotIn(List<Date> values) {
			addCriterion("subscr_date not in", values, "subscrDate");
			return (Criteria) this;
		}

		public Criteria andSubscrDateBetween(Date value1, Date value2) {
			addCriterion("subscr_date between", value1, value2, "subscrDate");
			return (Criteria) this;
		}

		public Criteria andSubscrDateNotBetween(Date value1, Date value2) {
			addCriterion("subscr_date not between", value1, value2,
					"subscrDate");
			return (Criteria) this;
		}

		public Criteria andSubscrIdIsNull() {
			addCriterion("subscr_id is null");
			return (Criteria) this;
		}

		public Criteria andSubscrIdIsNotNull() {
			addCriterion("subscr_id is not null");
			return (Criteria) this;
		}

		public Criteria andSubscrIdEqualTo(String value) {
			addCriterion("subscr_id =", value, "subscrId");
			return (Criteria) this;
		}

		public Criteria andSubscrIdNotEqualTo(String value) {
			addCriterion("subscr_id <>", value, "subscrId");
			return (Criteria) this;
		}

		public Criteria andSubscrIdGreaterThan(String value) {
			addCriterion("subscr_id >", value, "subscrId");
			return (Criteria) this;
		}

		public Criteria andSubscrIdGreaterThanOrEqualTo(String value) {
			addCriterion("subscr_id >=", value, "subscrId");
			return (Criteria) this;
		}

		public Criteria andSubscrIdLessThan(String value) {
			addCriterion("subscr_id <", value, "subscrId");
			return (Criteria) this;
		}

		public Criteria andSubscrIdLessThanOrEqualTo(String value) {
			addCriterion("subscr_id <=", value, "subscrId");
			return (Criteria) this;
		}

		public Criteria andSubscrIdLike(String value) {
			addCriterion("subscr_id like", value, "subscrId");
			return (Criteria) this;
		}

		public Criteria andSubscrIdNotLike(String value) {
			addCriterion("subscr_id not like", value, "subscrId");
			return (Criteria) this;
		}

		public Criteria andSubscrIdIn(List<String> values) {
			addCriterion("subscr_id in", values, "subscrId");
			return (Criteria) this;
		}

		public Criteria andSubscrIdNotIn(List<String> values) {
			addCriterion("subscr_id not in", values, "subscrId");
			return (Criteria) this;
		}

		public Criteria andSubscrIdBetween(String value1, String value2) {
			addCriterion("subscr_id between", value1, value2, "subscrId");
			return (Criteria) this;
		}

		public Criteria andSubscrIdNotBetween(String value1, String value2) {
			addCriterion("subscr_id not between", value1, value2, "subscrId");
			return (Criteria) this;
		}

		public Criteria andTxnTypeIsNull() {
			addCriterion("txn_type is null");
			return (Criteria) this;
		}

		public Criteria andTxnTypeIsNotNull() {
			addCriterion("txn_type is not null");
			return (Criteria) this;
		}

		public Criteria andTxnTypeEqualTo(String value) {
			addCriterion("txn_type =", value, "txnType");
			return (Criteria) this;
		}

		public Criteria andTxnTypeNotEqualTo(String value) {
			addCriterion("txn_type <>", value, "txnType");
			return (Criteria) this;
		}

		public Criteria andTxnTypeGreaterThan(String value) {
			addCriterion("txn_type >", value, "txnType");
			return (Criteria) this;
		}

		public Criteria andTxnTypeGreaterThanOrEqualTo(String value) {
			addCriterion("txn_type >=", value, "txnType");
			return (Criteria) this;
		}

		public Criteria andTxnTypeLessThan(String value) {
			addCriterion("txn_type <", value, "txnType");
			return (Criteria) this;
		}

		public Criteria andTxnTypeLessThanOrEqualTo(String value) {
			addCriterion("txn_type <=", value, "txnType");
			return (Criteria) this;
		}

		public Criteria andTxnTypeLike(String value) {
			addCriterion("txn_type like", value, "txnType");
			return (Criteria) this;
		}

		public Criteria andTxnTypeNotLike(String value) {
			addCriterion("txn_type not like", value, "txnType");
			return (Criteria) this;
		}

		public Criteria andTxnTypeIn(List<String> values) {
			addCriterion("txn_type in", values, "txnType");
			return (Criteria) this;
		}

		public Criteria andTxnTypeNotIn(List<String> values) {
			addCriterion("txn_type not in", values, "txnType");
			return (Criteria) this;
		}

		public Criteria andTxnTypeBetween(String value1, String value2) {
			addCriterion("txn_type between", value1, value2, "txnType");
			return (Criteria) this;
		}

		public Criteria andTxnTypeNotBetween(String value1, String value2) {
			addCriterion("txn_type not between", value1, value2, "txnType");
			return (Criteria) this;
		}

		public Criteria andAuthIsNull() {
			addCriterion("auth is null");
			return (Criteria) this;
		}

		public Criteria andAuthIsNotNull() {
			addCriterion("auth is not null");
			return (Criteria) this;
		}

		public Criteria andAuthEqualTo(String value) {
			addCriterion("auth =", value, "auth");
			return (Criteria) this;
		}

		public Criteria andAuthNotEqualTo(String value) {
			addCriterion("auth <>", value, "auth");
			return (Criteria) this;
		}

		public Criteria andAuthGreaterThan(String value) {
			addCriterion("auth >", value, "auth");
			return (Criteria) this;
		}

		public Criteria andAuthGreaterThanOrEqualTo(String value) {
			addCriterion("auth >=", value, "auth");
			return (Criteria) this;
		}

		public Criteria andAuthLessThan(String value) {
			addCriterion("auth <", value, "auth");
			return (Criteria) this;
		}

		public Criteria andAuthLessThanOrEqualTo(String value) {
			addCriterion("auth <=", value, "auth");
			return (Criteria) this;
		}

		public Criteria andAuthLike(String value) {
			addCriterion("auth like", value, "auth");
			return (Criteria) this;
		}

		public Criteria andAuthNotLike(String value) {
			addCriterion("auth not like", value, "auth");
			return (Criteria) this;
		}

		public Criteria andAuthIn(List<String> values) {
			addCriterion("auth in", values, "auth");
			return (Criteria) this;
		}

		public Criteria andAuthNotIn(List<String> values) {
			addCriterion("auth not in", values, "auth");
			return (Criteria) this;
		}

		public Criteria andAuthBetween(String value1, String value2) {
			addCriterion("auth between", value1, value2, "auth");
			return (Criteria) this;
		}

		public Criteria andAuthNotBetween(String value1, String value2) {
			addCriterion("auth not between", value1, value2, "auth");
			return (Criteria) this;
		}

		public Criteria andGroupIdIsNull() {
			addCriterion("group_id is null");
			return (Criteria) this;
		}

		public Criteria andGroupIdIsNotNull() {
			addCriterion("group_id is not null");
			return (Criteria) this;
		}

		public Criteria andGroupIdEqualTo(Long value) {
			addCriterion("group_id =", value, "groupId");
			return (Criteria) this;
		}

		public Criteria andGroupIdNotEqualTo(Long value) {
			addCriterion("group_id <>", value, "groupId");
			return (Criteria) this;
		}

		public Criteria andGroupIdGreaterThan(Long value) {
			addCriterion("group_id >", value, "groupId");
			return (Criteria) this;
		}

		public Criteria andGroupIdGreaterThanOrEqualTo(Long value) {
			addCriterion("group_id >=", value, "groupId");
			return (Criteria) this;
		}

		public Criteria andGroupIdLessThan(Long value) {
			addCriterion("group_id <", value, "groupId");
			return (Criteria) this;
		}

		public Criteria andGroupIdLessThanOrEqualTo(Long value) {
			addCriterion("group_id <=", value, "groupId");
			return (Criteria) this;
		}

		public Criteria andGroupIdIn(List<Long> values) {
			addCriterion("group_id in", values, "groupId");
			return (Criteria) this;
		}

		public Criteria andGroupIdNotIn(List<Long> values) {
			addCriterion("group_id not in", values, "groupId");
			return (Criteria) this;
		}

		public Criteria andGroupIdBetween(Long value1, Long value2) {
			addCriterion("group_id between", value1, value2, "groupId");
			return (Criteria) this;
		}

		public Criteria andGroupIdNotBetween(Long value1, Long value2) {
			addCriterion("group_id not between", value1, value2, "groupId");
			return (Criteria) this;
		}
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table orders
	 * @mbggenerated  Thu May 30 11:43:05 BST 2013
	 */
	public static class Criterion {
		private String condition;
		private Object value;
		private Object secondValue;
		private boolean noValue;
		private boolean singleValue;
		private boolean betweenValue;
		private boolean listValue;
		private String typeHandler;

		public String getCondition() {
			return condition;
		}

		public Object getValue() {
			return value;
		}

		public Object getSecondValue() {
			return secondValue;
		}

		public boolean isNoValue() {
			return noValue;
		}

		public boolean isSingleValue() {
			return singleValue;
		}

		public boolean isBetweenValue() {
			return betweenValue;
		}

		public boolean isListValue() {
			return listValue;
		}

		public String getTypeHandler() {
			return typeHandler;
		}

		protected Criterion(String condition) {
			super();
			this.condition = condition;
			this.typeHandler = null;
			this.noValue = true;
		}

		protected Criterion(String condition, Object value, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.typeHandler = typeHandler;
			if (value instanceof List<?>) {
				this.listValue = true;
			} else {
				this.singleValue = true;
			}
		}

		protected Criterion(String condition, Object value) {
			this(condition, value, null);
		}

		protected Criterion(String condition, Object value, Object secondValue,
				String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.secondValue = secondValue;
			this.typeHandler = typeHandler;
			this.betweenValue = true;
		}

		protected Criterion(String condition, Object value, Object secondValue) {
			this(condition, value, secondValue, null);
		}
	}

	/**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table orders
     *
     * @mbggenerated do_not_delete_during_merge Tue Mar 12 12:59:39 GMT 2013
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }
}