package com.jemmmedia.organise.mybatis.db.mybatis.model;

public class PackagesPricing extends BaseModel {

	/**
	 * 
	 */
	private static final long serialVersionUID = 8857326694295428841L;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column packages_pricing.package_name
	 * @mbggenerated  Tue Mar 12 14:20:31 GMT 2013
	 */
	private String packageName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column packages_pricing.price
	 * @mbggenerated  Tue Mar 12 14:20:31 GMT 2013
	 */
	private Integer price;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column packages_pricing.users_allowed
	 * @mbggenerated  Tue Mar 12 14:20:31 GMT 2013
	 */
	private Integer usersAllowed;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column packages_pricing.storage_allowed
	 * @mbggenerated  Tue Mar 12 14:20:31 GMT 2013
	 */
	private Integer storageAllowed;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column packages_pricing.support_type
	 * @mbggenerated  Tue Mar 12 14:20:31 GMT 2013
	 */
	private Integer supportType;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column packages_pricing.package_name
	 * @return  the value of packages_pricing.package_name
	 * @mbggenerated  Tue Mar 12 14:20:31 GMT 2013
	 */
	public String getPackageName() {
		return packageName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column packages_pricing.package_name
	 * @param packageName  the value for packages_pricing.package_name
	 * @mbggenerated  Tue Mar 12 14:20:31 GMT 2013
	 */
	public void setPackageName(String packageName) {
		this.packageName = packageName == null ? null : packageName.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column packages_pricing.price
	 * @return  the value of packages_pricing.price
	 * @mbggenerated  Tue Mar 12 14:20:31 GMT 2013
	 */
	public Integer getPrice() {
		return price;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column packages_pricing.price
	 * @param price  the value for packages_pricing.price
	 * @mbggenerated  Tue Mar 12 14:20:31 GMT 2013
	 */
	public void setPrice(Integer price) {
		this.price = price;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column packages_pricing.users_allowed
	 * @return  the value of packages_pricing.users_allowed
	 * @mbggenerated  Tue Mar 12 14:20:31 GMT 2013
	 */
	public Integer getUsersAllowed() {
		return usersAllowed;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column packages_pricing.users_allowed
	 * @param usersAllowed  the value for packages_pricing.users_allowed
	 * @mbggenerated  Tue Mar 12 14:20:31 GMT 2013
	 */
	public void setUsersAllowed(Integer usersAllowed) {
		this.usersAllowed = usersAllowed;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column packages_pricing.storage_allowed
	 * @return  the value of packages_pricing.storage_allowed
	 * @mbggenerated  Tue Mar 12 14:20:31 GMT 2013
	 */
	public Integer getStorageAllowed() {
		return storageAllowed;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column packages_pricing.storage_allowed
	 * @param storageAllowed  the value for packages_pricing.storage_allowed
	 * @mbggenerated  Tue Mar 12 14:20:31 GMT 2013
	 */
	public void setStorageAllowed(Integer storageAllowed) {
		this.storageAllowed = storageAllowed;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column packages_pricing.support_type
	 * @return  the value of packages_pricing.support_type
	 * @mbggenerated  Tue Mar 12 14:20:31 GMT 2013
	 */
	public Integer getSupportType() {
		return supportType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column packages_pricing.support_type
	 * @param supportType  the value for packages_pricing.support_type
	 * @mbggenerated  Tue Mar 12 14:20:31 GMT 2013
	 */
	public void setSupportType(Integer supportType) {
		this.supportType = supportType;
	}
}