package com.jemmmedia.organise.mybatis.db.mybatis.model;

public class PackagesPlatinum extends BaseModel {

	/**
	 * 
	 */
	private static final long serialVersionUID = -5057535720409375877L;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column packages_platinum.group_id
	 * @mbggenerated  Tue Mar 12 14:20:31 GMT 2013
	 */
	private Long groupId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column packages_platinum.users_allowed
	 * @mbggenerated  Tue Mar 12 14:20:31 GMT 2013
	 */
	private Integer usersAllowed;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column packages_platinum.storage_allowed
	 * @mbggenerated  Tue Mar 12 14:20:31 GMT 2013
	 */
	private Integer storageAllowed;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column packages_platinum.support_type
	 * @mbggenerated  Tue Mar 12 14:20:31 GMT 2013
	 */
	private Integer supportType;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column packages_platinum.group_id
	 * @return  the value of packages_platinum.group_id
	 * @mbggenerated  Tue Mar 12 14:20:31 GMT 2013
	 */
	public Long getGroupId() {
		return groupId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column packages_platinum.group_id
	 * @param groupId  the value for packages_platinum.group_id
	 * @mbggenerated  Tue Mar 12 14:20:31 GMT 2013
	 */
	public void setGroupId(Long groupId) {
		this.groupId = groupId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column packages_platinum.users_allowed
	 * @return  the value of packages_platinum.users_allowed
	 * @mbggenerated  Tue Mar 12 14:20:31 GMT 2013
	 */
	public Integer getUsersAllowed() {
		return usersAllowed;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column packages_platinum.users_allowed
	 * @param usersAllowed  the value for packages_platinum.users_allowed
	 * @mbggenerated  Tue Mar 12 14:20:31 GMT 2013
	 */
	public void setUsersAllowed(Integer usersAllowed) {
		this.usersAllowed = usersAllowed;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column packages_platinum.storage_allowed
	 * @return  the value of packages_platinum.storage_allowed
	 * @mbggenerated  Tue Mar 12 14:20:31 GMT 2013
	 */
	public Integer getStorageAllowed() {
		return storageAllowed;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column packages_platinum.storage_allowed
	 * @param storageAllowed  the value for packages_platinum.storage_allowed
	 * @mbggenerated  Tue Mar 12 14:20:31 GMT 2013
	 */
	public void setStorageAllowed(Integer storageAllowed) {
		this.storageAllowed = storageAllowed;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column packages_platinum.support_type
	 * @return  the value of packages_platinum.support_type
	 * @mbggenerated  Tue Mar 12 14:20:31 GMT 2013
	 */
	public Integer getSupportType() {
		return supportType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column packages_platinum.support_type
	 * @param supportType  the value for packages_platinum.support_type
	 * @mbggenerated  Tue Mar 12 14:20:31 GMT 2013
	 */
	public void setSupportType(Integer supportType) {
		this.supportType = supportType;
	}
}