package com.jemmmedia.organise.mybatis.db.mybatis.model;

public class Regions extends BaseModel {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column regions.region_name
	 * @mbggenerated  Fri Jan 25 13:51:48 GMT 2013
	 */
	private String regionName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column regions.group_id
	 * @mbggenerated  Fri Jan 25 13:51:48 GMT 2013
	 */
	private Long groupId;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column regions.region_name
	 * @return  the value of regions.region_name
	 * @mbggenerated  Fri Jan 25 13:51:48 GMT 2013
	 */
	public String getRegionName() {
		return regionName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column regions.region_name
	 * @param regionName  the value for regions.region_name
	 * @mbggenerated  Fri Jan 25 13:51:48 GMT 2013
	 */
	public void setRegionName(String regionName) {
		this.regionName = regionName == null ? null : regionName.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column regions.group_id
	 * @return  the value of regions.group_id
	 * @mbggenerated  Fri Jan 25 13:51:48 GMT 2013
	 */
	public Long getGroupId() {
		return groupId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column regions.group_id
	 * @param groupId  the value for regions.group_id
	 * @mbggenerated  Fri Jan 25 13:51:48 GMT 2013
	 */
	public void setGroupId(Long groupId) {
		this.groupId = groupId;
	}
}