package com.jemmmedia.organise.mybatis.db.mybatis.model;

public class Roles extends BaseModel {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column roles.name
     *
     * @mbggenerated Thu Aug 30 13:12:24 BST 2012
     */
    private String name;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column roles.name
     *
     * @return the value of roles.name
     *
     * @mbggenerated Thu Aug 30 13:12:24 BST 2012
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column roles.name
     *
     * @param name the value for roles.name
     *
     * @mbggenerated Thu Aug 30 13:12:24 BST 2012
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }
}