package com.jemmmedia.organise.mybatis.db.mybatis.model;

import java.util.Date;

public class UsersWithRoles {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column roles_users.user_id
	 * @mbggenerated  Fri Jan 25 12:14:36 GMT 2013
	 */
	private Long userId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column roles_users.role_id
	 * @mbggenerated  Fri Jan 25 12:14:36 GMT 2013
	 */
	private Integer roleId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column roles_users.created_at
	 * @mbggenerated  Fri Jan 25 12:14:36 GMT 2013
	 */
	private Date createdAt;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column roles_users.updated_at
	 * @mbggenerated  Fri Jan 25 12:14:36 GMT 2013
	 */
	private Date updatedAt;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column roles_users.user_id
	 * @return  the value of roles_users.user_id
	 * @mbggenerated  Fri Jan 25 12:14:36 GMT 2013
	 */
	public Long getUserId() {
		return userId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column roles_users.user_id
	 * @param userId  the value for roles_users.user_id
	 * @mbggenerated  Fri Jan 25 12:14:36 GMT 2013
	 */
	public void setUserId(Long userId) {
		this.userId = userId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column roles_users.role_id
	 * @return  the value of roles_users.role_id
	 * @mbggenerated  Fri Jan 25 12:14:36 GMT 2013
	 */
	public Integer getRoleId() {
		return roleId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column roles_users.role_id
	 * @param roleId  the value for roles_users.role_id
	 * @mbggenerated  Fri Jan 25 12:14:36 GMT 2013
	 */
	public void setRoleId(Integer roleId) {
		this.roleId = roleId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column roles_users.created_at
	 * @return  the value of roles_users.created_at
	 * @mbggenerated  Fri Jan 25 12:14:36 GMT 2013
	 */
	public Date getCreatedAt() {
		return createdAt;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column roles_users.created_at
	 * @param createdAt  the value for roles_users.created_at
	 * @mbggenerated  Fri Jan 25 12:14:36 GMT 2013
	 */
	public void setCreatedAt(Date createdAt) {
		this.createdAt = createdAt;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column roles_users.updated_at
	 * @return  the value of roles_users.updated_at
	 * @mbggenerated  Fri Jan 25 12:14:36 GMT 2013
	 */
	public Date getUpdatedAt() {
		return updatedAt;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column roles_users.updated_at
	 * @param updatedAt  the value for roles_users.updated_at
	 * @mbggenerated  Fri Jan 25 12:14:36 GMT 2013
	 */
	public void setUpdatedAt(Date updatedAt) {
		this.updatedAt = updatedAt;
	}
}