package com.jemmmedia.organise.mybatis.db.mybatis.model;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class UserExample {
    /**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table users
	 * @mbggenerated  Thu Apr 04 15:35:42 BST 2013
	 */
	protected String orderByClause;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table users
	 * @mbggenerated  Thu Apr 04 15:35:42 BST 2013
	 */
	protected boolean distinct;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table users
	 * @mbggenerated  Thu Apr 04 15:35:42 BST 2013
	 */
	protected List<Criteria> oredCriteria;

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table users
	 * @mbggenerated  Thu Apr 04 15:35:42 BST 2013
	 */
	public UserExample() {
		oredCriteria = new ArrayList<Criteria>();
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table users
	 * @mbggenerated  Thu Apr 04 15:35:42 BST 2013
	 */
	public void setOrderByClause(String orderByClause) {
		this.orderByClause = orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table users
	 * @mbggenerated  Thu Apr 04 15:35:42 BST 2013
	 */
	public String getOrderByClause() {
		return orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table users
	 * @mbggenerated  Thu Apr 04 15:35:42 BST 2013
	 */
	public void setDistinct(boolean distinct) {
		this.distinct = distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table users
	 * @mbggenerated  Thu Apr 04 15:35:42 BST 2013
	 */
	public boolean isDistinct() {
		return distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table users
	 * @mbggenerated  Thu Apr 04 15:35:42 BST 2013
	 */
	public List<Criteria> getOredCriteria() {
		return oredCriteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table users
	 * @mbggenerated  Thu Apr 04 15:35:42 BST 2013
	 */
	public void or(Criteria criteria) {
		oredCriteria.add(criteria);
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table users
	 * @mbggenerated  Thu Apr 04 15:35:42 BST 2013
	 */
	public Criteria or() {
		Criteria criteria = createCriteriaInternal();
		oredCriteria.add(criteria);
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table users
	 * @mbggenerated  Thu Apr 04 15:35:42 BST 2013
	 */
	public Criteria createCriteria() {
		Criteria criteria = createCriteriaInternal();
		if (oredCriteria.size() == 0) {
			oredCriteria.add(criteria);
		}
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table users
	 * @mbggenerated  Thu Apr 04 15:35:42 BST 2013
	 */
	protected Criteria createCriteriaInternal() {
		Criteria criteria = new Criteria();
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table users
	 * @mbggenerated  Thu Apr 04 15:35:42 BST 2013
	 */
	public void clear() {
		oredCriteria.clear();
		orderByClause = null;
		distinct = false;
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table users
	 * @mbggenerated  Thu Apr 04 15:35:42 BST 2013
	 */
	protected abstract static class GeneratedCriteria {
		protected List<Criterion> criteria;

		protected GeneratedCriteria() {
			super();
			criteria = new ArrayList<Criterion>();
		}

		public boolean isValid() {
			return criteria.size() > 0;
		}

		public List<Criterion> getAllCriteria() {
			return criteria;
		}

		public List<Criterion> getCriteria() {
			return criteria;
		}

		protected void addCriterion(String condition) {
			if (condition == null) {
				throw new RuntimeException("Value for condition cannot be null");
			}
			criteria.add(new Criterion(condition));
		}

		protected void addCriterion(String condition, Object value,
				String property) {
			if (value == null) {
				throw new RuntimeException("Value for " + property
						+ " cannot be null");
			}
			criteria.add(new Criterion(condition, value));
		}

		protected void addCriterion(String condition, Object value1,
				Object value2, String property) {
			if (value1 == null || value2 == null) {
				throw new RuntimeException("Between values for " + property
						+ " cannot be null");
			}
			criteria.add(new Criterion(condition, value1, value2));
		}

		public Criteria andIdIsNull() {
			addCriterion("id is null");
			return (Criteria) this;
		}

		public Criteria andIdIsNotNull() {
			addCriterion("id is not null");
			return (Criteria) this;
		}

		public Criteria andIdEqualTo(Long value) {
			addCriterion("id =", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdNotEqualTo(Long value) {
			addCriterion("id <>", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdGreaterThan(Long value) {
			addCriterion("id >", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdGreaterThanOrEqualTo(Long value) {
			addCriterion("id >=", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdLessThan(Long value) {
			addCriterion("id <", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdLessThanOrEqualTo(Long value) {
			addCriterion("id <=", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdIn(List<Long> values) {
			addCriterion("id in", values, "id");
			return (Criteria) this;
		}

		public Criteria andIdNotIn(List<Long> values) {
			addCriterion("id not in", values, "id");
			return (Criteria) this;
		}

		public Criteria andIdBetween(Long value1, Long value2) {
			addCriterion("id between", value1, value2, "id");
			return (Criteria) this;
		}

		public Criteria andIdNotBetween(Long value1, Long value2) {
			addCriterion("id not between", value1, value2, "id");
			return (Criteria) this;
		}

		public Criteria andUsernameIsNull() {
			addCriterion("username is null");
			return (Criteria) this;
		}

		public Criteria andUsernameIsNotNull() {
			addCriterion("username is not null");
			return (Criteria) this;
		}

		public Criteria andUsernameEqualTo(String value) {
			addCriterion("username =", value, "username");
			return (Criteria) this;
		}

		public Criteria andUsernameNotEqualTo(String value) {
			addCriterion("username <>", value, "username");
			return (Criteria) this;
		}

		public Criteria andUsernameGreaterThan(String value) {
			addCriterion("username >", value, "username");
			return (Criteria) this;
		}

		public Criteria andUsernameGreaterThanOrEqualTo(String value) {
			addCriterion("username >=", value, "username");
			return (Criteria) this;
		}

		public Criteria andUsernameLessThan(String value) {
			addCriterion("username <", value, "username");
			return (Criteria) this;
		}

		public Criteria andUsernameLessThanOrEqualTo(String value) {
			addCriterion("username <=", value, "username");
			return (Criteria) this;
		}

		public Criteria andUsernameLike(String value) {
			addCriterion("username like", value, "username");
			return (Criteria) this;
		}

		public Criteria andUsernameNotLike(String value) {
			addCriterion("username not like", value, "username");
			return (Criteria) this;
		}

		public Criteria andUsernameIn(List<String> values) {
			addCriterion("username in", values, "username");
			return (Criteria) this;
		}

		public Criteria andUsernameNotIn(List<String> values) {
			addCriterion("username not in", values, "username");
			return (Criteria) this;
		}

		public Criteria andUsernameBetween(String value1, String value2) {
			addCriterion("username between", value1, value2, "username");
			return (Criteria) this;
		}

		public Criteria andUsernameNotBetween(String value1, String value2) {
			addCriterion("username not between", value1, value2, "username");
			return (Criteria) this;
		}

		public Criteria andEmailIsNull() {
			addCriterion("email is null");
			return (Criteria) this;
		}

		public Criteria andEmailIsNotNull() {
			addCriterion("email is not null");
			return (Criteria) this;
		}

		public Criteria andEmailEqualTo(String value) {
			addCriterion("email =", value, "email");
			return (Criteria) this;
		}

		public Criteria andEmailNotEqualTo(String value) {
			addCriterion("email <>", value, "email");
			return (Criteria) this;
		}

		public Criteria andEmailGreaterThan(String value) {
			addCriterion("email >", value, "email");
			return (Criteria) this;
		}

		public Criteria andEmailGreaterThanOrEqualTo(String value) {
			addCriterion("email >=", value, "email");
			return (Criteria) this;
		}

		public Criteria andEmailLessThan(String value) {
			addCriterion("email <", value, "email");
			return (Criteria) this;
		}

		public Criteria andEmailLessThanOrEqualTo(String value) {
			addCriterion("email <=", value, "email");
			return (Criteria) this;
		}

		public Criteria andEmailLike(String value) {
			addCriterion("email like", value, "email");
			return (Criteria) this;
		}

		public Criteria andEmailNotLike(String value) {
			addCriterion("email not like", value, "email");
			return (Criteria) this;
		}

		public Criteria andEmailIn(List<String> values) {
			addCriterion("email in", values, "email");
			return (Criteria) this;
		}

		public Criteria andEmailNotIn(List<String> values) {
			addCriterion("email not in", values, "email");
			return (Criteria) this;
		}

		public Criteria andEmailBetween(String value1, String value2) {
			addCriterion("email between", value1, value2, "email");
			return (Criteria) this;
		}

		public Criteria andEmailNotBetween(String value1, String value2) {
			addCriterion("email not between", value1, value2, "email");
			return (Criteria) this;
		}

		public Criteria andProfileimageIsNull() {
			addCriterion("profileImage is null");
			return (Criteria) this;
		}

		public Criteria andProfileimageIsNotNull() {
			addCriterion("profileImage is not null");
			return (Criteria) this;
		}

		public Criteria andProfileimageEqualTo(String value) {
			addCriterion("profileImage =", value, "profileimage");
			return (Criteria) this;
		}

		public Criteria andProfileimageNotEqualTo(String value) {
			addCriterion("profileImage <>", value, "profileimage");
			return (Criteria) this;
		}

		public Criteria andProfileimageGreaterThan(String value) {
			addCriterion("profileImage >", value, "profileimage");
			return (Criteria) this;
		}

		public Criteria andProfileimageGreaterThanOrEqualTo(String value) {
			addCriterion("profileImage >=", value, "profileimage");
			return (Criteria) this;
		}

		public Criteria andProfileimageLessThan(String value) {
			addCriterion("profileImage <", value, "profileimage");
			return (Criteria) this;
		}

		public Criteria andProfileimageLessThanOrEqualTo(String value) {
			addCriterion("profileImage <=", value, "profileimage");
			return (Criteria) this;
		}

		public Criteria andProfileimageLike(String value) {
			addCriterion("profileImage like", value, "profileimage");
			return (Criteria) this;
		}

		public Criteria andProfileimageNotLike(String value) {
			addCriterion("profileImage not like", value, "profileimage");
			return (Criteria) this;
		}

		public Criteria andProfileimageIn(List<String> values) {
			addCriterion("profileImage in", values, "profileimage");
			return (Criteria) this;
		}

		public Criteria andProfileimageNotIn(List<String> values) {
			addCriterion("profileImage not in", values, "profileimage");
			return (Criteria) this;
		}

		public Criteria andProfileimageBetween(String value1, String value2) {
			addCriterion("profileImage between", value1, value2, "profileimage");
			return (Criteria) this;
		}

		public Criteria andProfileimageNotBetween(String value1, String value2) {
			addCriterion("profileImage not between", value1, value2,
					"profileimage");
			return (Criteria) this;
		}

		public Criteria andCryptedPasswordIsNull() {
			addCriterion("crypted_password is null");
			return (Criteria) this;
		}

		public Criteria andCryptedPasswordIsNotNull() {
			addCriterion("crypted_password is not null");
			return (Criteria) this;
		}

		public Criteria andCryptedPasswordEqualTo(String value) {
			addCriterion("crypted_password =", value, "cryptedPassword");
			return (Criteria) this;
		}

		public Criteria andCryptedPasswordNotEqualTo(String value) {
			addCriterion("crypted_password <>", value, "cryptedPassword");
			return (Criteria) this;
		}

		public Criteria andCryptedPasswordGreaterThan(String value) {
			addCriterion("crypted_password >", value, "cryptedPassword");
			return (Criteria) this;
		}

		public Criteria andCryptedPasswordGreaterThanOrEqualTo(String value) {
			addCriterion("crypted_password >=", value, "cryptedPassword");
			return (Criteria) this;
		}

		public Criteria andCryptedPasswordLessThan(String value) {
			addCriterion("crypted_password <", value, "cryptedPassword");
			return (Criteria) this;
		}

		public Criteria andCryptedPasswordLessThanOrEqualTo(String value) {
			addCriterion("crypted_password <=", value, "cryptedPassword");
			return (Criteria) this;
		}

		public Criteria andCryptedPasswordLike(String value) {
			addCriterion("crypted_password like", value, "cryptedPassword");
			return (Criteria) this;
		}

		public Criteria andCryptedPasswordNotLike(String value) {
			addCriterion("crypted_password not like", value, "cryptedPassword");
			return (Criteria) this;
		}

		public Criteria andCryptedPasswordIn(List<String> values) {
			addCriterion("crypted_password in", values, "cryptedPassword");
			return (Criteria) this;
		}

		public Criteria andCryptedPasswordNotIn(List<String> values) {
			addCriterion("crypted_password not in", values, "cryptedPassword");
			return (Criteria) this;
		}

		public Criteria andCryptedPasswordBetween(String value1, String value2) {
			addCriterion("crypted_password between", value1, value2,
					"cryptedPassword");
			return (Criteria) this;
		}

		public Criteria andCryptedPasswordNotBetween(String value1,
				String value2) {
			addCriterion("crypted_password not between", value1, value2,
					"cryptedPassword");
			return (Criteria) this;
		}

		public Criteria andPasswordSaltIsNull() {
			addCriterion("password_salt is null");
			return (Criteria) this;
		}

		public Criteria andPasswordSaltIsNotNull() {
			addCriterion("password_salt is not null");
			return (Criteria) this;
		}

		public Criteria andPasswordSaltEqualTo(String value) {
			addCriterion("password_salt =", value, "passwordSalt");
			return (Criteria) this;
		}

		public Criteria andPasswordSaltNotEqualTo(String value) {
			addCriterion("password_salt <>", value, "passwordSalt");
			return (Criteria) this;
		}

		public Criteria andPasswordSaltGreaterThan(String value) {
			addCriterion("password_salt >", value, "passwordSalt");
			return (Criteria) this;
		}

		public Criteria andPasswordSaltGreaterThanOrEqualTo(String value) {
			addCriterion("password_salt >=", value, "passwordSalt");
			return (Criteria) this;
		}

		public Criteria andPasswordSaltLessThan(String value) {
			addCriterion("password_salt <", value, "passwordSalt");
			return (Criteria) this;
		}

		public Criteria andPasswordSaltLessThanOrEqualTo(String value) {
			addCriterion("password_salt <=", value, "passwordSalt");
			return (Criteria) this;
		}

		public Criteria andPasswordSaltLike(String value) {
			addCriterion("password_salt like", value, "passwordSalt");
			return (Criteria) this;
		}

		public Criteria andPasswordSaltNotLike(String value) {
			addCriterion("password_salt not like", value, "passwordSalt");
			return (Criteria) this;
		}

		public Criteria andPasswordSaltIn(List<String> values) {
			addCriterion("password_salt in", values, "passwordSalt");
			return (Criteria) this;
		}

		public Criteria andPasswordSaltNotIn(List<String> values) {
			addCriterion("password_salt not in", values, "passwordSalt");
			return (Criteria) this;
		}

		public Criteria andPasswordSaltBetween(String value1, String value2) {
			addCriterion("password_salt between", value1, value2,
					"passwordSalt");
			return (Criteria) this;
		}

		public Criteria andPasswordSaltNotBetween(String value1, String value2) {
			addCriterion("password_salt not between", value1, value2,
					"passwordSalt");
			return (Criteria) this;
		}

		public Criteria andPersistenceTokenIsNull() {
			addCriterion("persistence_token is null");
			return (Criteria) this;
		}

		public Criteria andPersistenceTokenIsNotNull() {
			addCriterion("persistence_token is not null");
			return (Criteria) this;
		}

		public Criteria andPersistenceTokenEqualTo(String value) {
			addCriterion("persistence_token =", value, "persistenceToken");
			return (Criteria) this;
		}

		public Criteria andPersistenceTokenNotEqualTo(String value) {
			addCriterion("persistence_token <>", value, "persistenceToken");
			return (Criteria) this;
		}

		public Criteria andPersistenceTokenGreaterThan(String value) {
			addCriterion("persistence_token >", value, "persistenceToken");
			return (Criteria) this;
		}

		public Criteria andPersistenceTokenGreaterThanOrEqualTo(String value) {
			addCriterion("persistence_token >=", value, "persistenceToken");
			return (Criteria) this;
		}

		public Criteria andPersistenceTokenLessThan(String value) {
			addCriterion("persistence_token <", value, "persistenceToken");
			return (Criteria) this;
		}

		public Criteria andPersistenceTokenLessThanOrEqualTo(String value) {
			addCriterion("persistence_token <=", value, "persistenceToken");
			return (Criteria) this;
		}

		public Criteria andPersistenceTokenLike(String value) {
			addCriterion("persistence_token like", value, "persistenceToken");
			return (Criteria) this;
		}

		public Criteria andPersistenceTokenNotLike(String value) {
			addCriterion("persistence_token not like", value,
					"persistenceToken");
			return (Criteria) this;
		}

		public Criteria andPersistenceTokenIn(List<String> values) {
			addCriterion("persistence_token in", values, "persistenceToken");
			return (Criteria) this;
		}

		public Criteria andPersistenceTokenNotIn(List<String> values) {
			addCriterion("persistence_token not in", values, "persistenceToken");
			return (Criteria) this;
		}

		public Criteria andPersistenceTokenBetween(String value1, String value2) {
			addCriterion("persistence_token between", value1, value2,
					"persistenceToken");
			return (Criteria) this;
		}

		public Criteria andPersistenceTokenNotBetween(String value1,
				String value2) {
			addCriterion("persistence_token not between", value1, value2,
					"persistenceToken");
			return (Criteria) this;
		}

		public Criteria andRegionIdIsNull() {
			addCriterion("region_id is null");
			return (Criteria) this;
		}

		public Criteria andRegionIdIsNotNull() {
			addCriterion("region_id is not null");
			return (Criteria) this;
		}

		public Criteria andRegionIdEqualTo(Long value) {
			addCriterion("region_id =", value, "regionId");
			return (Criteria) this;
		}

		public Criteria andRegionIdNotEqualTo(Long value) {
			addCriterion("region_id <>", value, "regionId");
			return (Criteria) this;
		}

		public Criteria andRegionIdGreaterThan(Long value) {
			addCriterion("region_id >", value, "regionId");
			return (Criteria) this;
		}

		public Criteria andRegionIdGreaterThanOrEqualTo(Long value) {
			addCriterion("region_id >=", value, "regionId");
			return (Criteria) this;
		}

		public Criteria andRegionIdLessThan(Long value) {
			addCriterion("region_id <", value, "regionId");
			return (Criteria) this;
		}

		public Criteria andRegionIdLessThanOrEqualTo(Long value) {
			addCriterion("region_id <=", value, "regionId");
			return (Criteria) this;
		}

		public Criteria andRegionIdIn(List<Long> values) {
			addCriterion("region_id in", values, "regionId");
			return (Criteria) this;
		}

		public Criteria andRegionIdNotIn(List<Long> values) {
			addCriterion("region_id not in", values, "regionId");
			return (Criteria) this;
		}

		public Criteria andRegionIdBetween(Long value1, Long value2) {
			addCriterion("region_id between", value1, value2, "regionId");
			return (Criteria) this;
		}

		public Criteria andRegionIdNotBetween(Long value1, Long value2) {
			addCriterion("region_id not between", value1, value2, "regionId");
			return (Criteria) this;
		}

		public Criteria andJobTitleIsNull() {
			addCriterion("job_title is null");
			return (Criteria) this;
		}

		public Criteria andJobTitleIsNotNull() {
			addCriterion("job_title is not null");
			return (Criteria) this;
		}

		public Criteria andJobTitleEqualTo(String value) {
			addCriterion("job_title =", value, "jobTitle");
			return (Criteria) this;
		}

		public Criteria andJobTitleNotEqualTo(String value) {
			addCriterion("job_title <>", value, "jobTitle");
			return (Criteria) this;
		}

		public Criteria andJobTitleGreaterThan(String value) {
			addCriterion("job_title >", value, "jobTitle");
			return (Criteria) this;
		}

		public Criteria andJobTitleGreaterThanOrEqualTo(String value) {
			addCriterion("job_title >=", value, "jobTitle");
			return (Criteria) this;
		}

		public Criteria andJobTitleLessThan(String value) {
			addCriterion("job_title <", value, "jobTitle");
			return (Criteria) this;
		}

		public Criteria andJobTitleLessThanOrEqualTo(String value) {
			addCriterion("job_title <=", value, "jobTitle");
			return (Criteria) this;
		}

		public Criteria andJobTitleLike(String value) {
			addCriterion("job_title like", value, "jobTitle");
			return (Criteria) this;
		}

		public Criteria andJobTitleNotLike(String value) {
			addCriterion("job_title not like", value, "jobTitle");
			return (Criteria) this;
		}

		public Criteria andJobTitleIn(List<String> values) {
			addCriterion("job_title in", values, "jobTitle");
			return (Criteria) this;
		}

		public Criteria andJobTitleNotIn(List<String> values) {
			addCriterion("job_title not in", values, "jobTitle");
			return (Criteria) this;
		}

		public Criteria andJobTitleBetween(String value1, String value2) {
			addCriterion("job_title between", value1, value2, "jobTitle");
			return (Criteria) this;
		}

		public Criteria andJobTitleNotBetween(String value1, String value2) {
			addCriterion("job_title not between", value1, value2, "jobTitle");
			return (Criteria) this;
		}

		public Criteria andLoginCountIsNull() {
			addCriterion("login_count is null");
			return (Criteria) this;
		}

		public Criteria andLoginCountIsNotNull() {
			addCriterion("login_count is not null");
			return (Criteria) this;
		}

		public Criteria andLoginCountEqualTo(Integer value) {
			addCriterion("login_count =", value, "loginCount");
			return (Criteria) this;
		}

		public Criteria andLoginCountNotEqualTo(Integer value) {
			addCriterion("login_count <>", value, "loginCount");
			return (Criteria) this;
		}

		public Criteria andLoginCountGreaterThan(Integer value) {
			addCriterion("login_count >", value, "loginCount");
			return (Criteria) this;
		}

		public Criteria andLoginCountGreaterThanOrEqualTo(Integer value) {
			addCriterion("login_count >=", value, "loginCount");
			return (Criteria) this;
		}

		public Criteria andLoginCountLessThan(Integer value) {
			addCriterion("login_count <", value, "loginCount");
			return (Criteria) this;
		}

		public Criteria andLoginCountLessThanOrEqualTo(Integer value) {
			addCriterion("login_count <=", value, "loginCount");
			return (Criteria) this;
		}

		public Criteria andLoginCountIn(List<Integer> values) {
			addCriterion("login_count in", values, "loginCount");
			return (Criteria) this;
		}

		public Criteria andLoginCountNotIn(List<Integer> values) {
			addCriterion("login_count not in", values, "loginCount");
			return (Criteria) this;
		}

		public Criteria andLoginCountBetween(Integer value1, Integer value2) {
			addCriterion("login_count between", value1, value2, "loginCount");
			return (Criteria) this;
		}

		public Criteria andLoginCountNotBetween(Integer value1, Integer value2) {
			addCriterion("login_count not between", value1, value2,
					"loginCount");
			return (Criteria) this;
		}

		public Criteria andFailedLoginCountIsNull() {
			addCriterion("failed_login_count is null");
			return (Criteria) this;
		}

		public Criteria andFailedLoginCountIsNotNull() {
			addCriterion("failed_login_count is not null");
			return (Criteria) this;
		}

		public Criteria andFailedLoginCountEqualTo(Integer value) {
			addCriterion("failed_login_count =", value, "failedLoginCount");
			return (Criteria) this;
		}

		public Criteria andFailedLoginCountNotEqualTo(Integer value) {
			addCriterion("failed_login_count <>", value, "failedLoginCount");
			return (Criteria) this;
		}

		public Criteria andFailedLoginCountGreaterThan(Integer value) {
			addCriterion("failed_login_count >", value, "failedLoginCount");
			return (Criteria) this;
		}

		public Criteria andFailedLoginCountGreaterThanOrEqualTo(Integer value) {
			addCriterion("failed_login_count >=", value, "failedLoginCount");
			return (Criteria) this;
		}

		public Criteria andFailedLoginCountLessThan(Integer value) {
			addCriterion("failed_login_count <", value, "failedLoginCount");
			return (Criteria) this;
		}

		public Criteria andFailedLoginCountLessThanOrEqualTo(Integer value) {
			addCriterion("failed_login_count <=", value, "failedLoginCount");
			return (Criteria) this;
		}

		public Criteria andFailedLoginCountIn(List<Integer> values) {
			addCriterion("failed_login_count in", values, "failedLoginCount");
			return (Criteria) this;
		}

		public Criteria andFailedLoginCountNotIn(List<Integer> values) {
			addCriterion("failed_login_count not in", values,
					"failedLoginCount");
			return (Criteria) this;
		}

		public Criteria andFailedLoginCountBetween(Integer value1,
				Integer value2) {
			addCriterion("failed_login_count between", value1, value2,
					"failedLoginCount");
			return (Criteria) this;
		}

		public Criteria andFailedLoginCountNotBetween(Integer value1,
				Integer value2) {
			addCriterion("failed_login_count not between", value1, value2,
					"failedLoginCount");
			return (Criteria) this;
		}

		public Criteria andLastRequestAtIsNull() {
			addCriterion("last_request_at is null");
			return (Criteria) this;
		}

		public Criteria andLastRequestAtIsNotNull() {
			addCriterion("last_request_at is not null");
			return (Criteria) this;
		}

		public Criteria andLastRequestAtEqualTo(Date value) {
			addCriterion("last_request_at =", value, "lastRequestAt");
			return (Criteria) this;
		}

		public Criteria andLastRequestAtNotEqualTo(Date value) {
			addCriterion("last_request_at <>", value, "lastRequestAt");
			return (Criteria) this;
		}

		public Criteria andLastRequestAtGreaterThan(Date value) {
			addCriterion("last_request_at >", value, "lastRequestAt");
			return (Criteria) this;
		}

		public Criteria andLastRequestAtGreaterThanOrEqualTo(Date value) {
			addCriterion("last_request_at >=", value, "lastRequestAt");
			return (Criteria) this;
		}

		public Criteria andLastRequestAtLessThan(Date value) {
			addCriterion("last_request_at <", value, "lastRequestAt");
			return (Criteria) this;
		}

		public Criteria andLastRequestAtLessThanOrEqualTo(Date value) {
			addCriterion("last_request_at <=", value, "lastRequestAt");
			return (Criteria) this;
		}

		public Criteria andLastRequestAtIn(List<Date> values) {
			addCriterion("last_request_at in", values, "lastRequestAt");
			return (Criteria) this;
		}

		public Criteria andLastRequestAtNotIn(List<Date> values) {
			addCriterion("last_request_at not in", values, "lastRequestAt");
			return (Criteria) this;
		}

		public Criteria andLastRequestAtBetween(Date value1, Date value2) {
			addCriterion("last_request_at between", value1, value2,
					"lastRequestAt");
			return (Criteria) this;
		}

		public Criteria andLastRequestAtNotBetween(Date value1, Date value2) {
			addCriterion("last_request_at not between", value1, value2,
					"lastRequestAt");
			return (Criteria) this;
		}

		public Criteria andCurrentLoginAtIsNull() {
			addCriterion("current_login_at is null");
			return (Criteria) this;
		}

		public Criteria andCurrentLoginAtIsNotNull() {
			addCriterion("current_login_at is not null");
			return (Criteria) this;
		}

		public Criteria andCurrentLoginAtEqualTo(Date value) {
			addCriterion("current_login_at =", value, "currentLoginAt");
			return (Criteria) this;
		}

		public Criteria andCurrentLoginAtNotEqualTo(Date value) {
			addCriterion("current_login_at <>", value, "currentLoginAt");
			return (Criteria) this;
		}

		public Criteria andCurrentLoginAtGreaterThan(Date value) {
			addCriterion("current_login_at >", value, "currentLoginAt");
			return (Criteria) this;
		}

		public Criteria andCurrentLoginAtGreaterThanOrEqualTo(Date value) {
			addCriterion("current_login_at >=", value, "currentLoginAt");
			return (Criteria) this;
		}

		public Criteria andCurrentLoginAtLessThan(Date value) {
			addCriterion("current_login_at <", value, "currentLoginAt");
			return (Criteria) this;
		}

		public Criteria andCurrentLoginAtLessThanOrEqualTo(Date value) {
			addCriterion("current_login_at <=", value, "currentLoginAt");
			return (Criteria) this;
		}

		public Criteria andCurrentLoginAtIn(List<Date> values) {
			addCriterion("current_login_at in", values, "currentLoginAt");
			return (Criteria) this;
		}

		public Criteria andCurrentLoginAtNotIn(List<Date> values) {
			addCriterion("current_login_at not in", values, "currentLoginAt");
			return (Criteria) this;
		}

		public Criteria andCurrentLoginAtBetween(Date value1, Date value2) {
			addCriterion("current_login_at between", value1, value2,
					"currentLoginAt");
			return (Criteria) this;
		}

		public Criteria andCurrentLoginAtNotBetween(Date value1, Date value2) {
			addCriterion("current_login_at not between", value1, value2,
					"currentLoginAt");
			return (Criteria) this;
		}

		public Criteria andLastLoginAtIsNull() {
			addCriterion("last_login_at is null");
			return (Criteria) this;
		}

		public Criteria andLastLoginAtIsNotNull() {
			addCriterion("last_login_at is not null");
			return (Criteria) this;
		}

		public Criteria andLastLoginAtEqualTo(Date value) {
			addCriterion("last_login_at =", value, "lastLoginAt");
			return (Criteria) this;
		}

		public Criteria andLastLoginAtNotEqualTo(Date value) {
			addCriterion("last_login_at <>", value, "lastLoginAt");
			return (Criteria) this;
		}

		public Criteria andLastLoginAtGreaterThan(Date value) {
			addCriterion("last_login_at >", value, "lastLoginAt");
			return (Criteria) this;
		}

		public Criteria andLastLoginAtGreaterThanOrEqualTo(Date value) {
			addCriterion("last_login_at >=", value, "lastLoginAt");
			return (Criteria) this;
		}

		public Criteria andLastLoginAtLessThan(Date value) {
			addCriterion("last_login_at <", value, "lastLoginAt");
			return (Criteria) this;
		}

		public Criteria andLastLoginAtLessThanOrEqualTo(Date value) {
			addCriterion("last_login_at <=", value, "lastLoginAt");
			return (Criteria) this;
		}

		public Criteria andLastLoginAtIn(List<Date> values) {
			addCriterion("last_login_at in", values, "lastLoginAt");
			return (Criteria) this;
		}

		public Criteria andLastLoginAtNotIn(List<Date> values) {
			addCriterion("last_login_at not in", values, "lastLoginAt");
			return (Criteria) this;
		}

		public Criteria andLastLoginAtBetween(Date value1, Date value2) {
			addCriterion("last_login_at between", value1, value2, "lastLoginAt");
			return (Criteria) this;
		}

		public Criteria andLastLoginAtNotBetween(Date value1, Date value2) {
			addCriterion("last_login_at not between", value1, value2,
					"lastLoginAt");
			return (Criteria) this;
		}

		public Criteria andCurrentLoginIpIsNull() {
			addCriterion("current_login_ip is null");
			return (Criteria) this;
		}

		public Criteria andCurrentLoginIpIsNotNull() {
			addCriterion("current_login_ip is not null");
			return (Criteria) this;
		}

		public Criteria andCurrentLoginIpEqualTo(String value) {
			addCriterion("current_login_ip =", value, "currentLoginIp");
			return (Criteria) this;
		}

		public Criteria andCurrentLoginIpNotEqualTo(String value) {
			addCriterion("current_login_ip <>", value, "currentLoginIp");
			return (Criteria) this;
		}

		public Criteria andCurrentLoginIpGreaterThan(String value) {
			addCriterion("current_login_ip >", value, "currentLoginIp");
			return (Criteria) this;
		}

		public Criteria andCurrentLoginIpGreaterThanOrEqualTo(String value) {
			addCriterion("current_login_ip >=", value, "currentLoginIp");
			return (Criteria) this;
		}

		public Criteria andCurrentLoginIpLessThan(String value) {
			addCriterion("current_login_ip <", value, "currentLoginIp");
			return (Criteria) this;
		}

		public Criteria andCurrentLoginIpLessThanOrEqualTo(String value) {
			addCriterion("current_login_ip <=", value, "currentLoginIp");
			return (Criteria) this;
		}

		public Criteria andCurrentLoginIpLike(String value) {
			addCriterion("current_login_ip like", value, "currentLoginIp");
			return (Criteria) this;
		}

		public Criteria andCurrentLoginIpNotLike(String value) {
			addCriterion("current_login_ip not like", value, "currentLoginIp");
			return (Criteria) this;
		}

		public Criteria andCurrentLoginIpIn(List<String> values) {
			addCriterion("current_login_ip in", values, "currentLoginIp");
			return (Criteria) this;
		}

		public Criteria andCurrentLoginIpNotIn(List<String> values) {
			addCriterion("current_login_ip not in", values, "currentLoginIp");
			return (Criteria) this;
		}

		public Criteria andCurrentLoginIpBetween(String value1, String value2) {
			addCriterion("current_login_ip between", value1, value2,
					"currentLoginIp");
			return (Criteria) this;
		}

		public Criteria andCurrentLoginIpNotBetween(String value1, String value2) {
			addCriterion("current_login_ip not between", value1, value2,
					"currentLoginIp");
			return (Criteria) this;
		}

		public Criteria andLastLoginIpIsNull() {
			addCriterion("last_login_ip is null");
			return (Criteria) this;
		}

		public Criteria andLastLoginIpIsNotNull() {
			addCriterion("last_login_ip is not null");
			return (Criteria) this;
		}

		public Criteria andLastLoginIpEqualTo(String value) {
			addCriterion("last_login_ip =", value, "lastLoginIp");
			return (Criteria) this;
		}

		public Criteria andLastLoginIpNotEqualTo(String value) {
			addCriterion("last_login_ip <>", value, "lastLoginIp");
			return (Criteria) this;
		}

		public Criteria andLastLoginIpGreaterThan(String value) {
			addCriterion("last_login_ip >", value, "lastLoginIp");
			return (Criteria) this;
		}

		public Criteria andLastLoginIpGreaterThanOrEqualTo(String value) {
			addCriterion("last_login_ip >=", value, "lastLoginIp");
			return (Criteria) this;
		}

		public Criteria andLastLoginIpLessThan(String value) {
			addCriterion("last_login_ip <", value, "lastLoginIp");
			return (Criteria) this;
		}

		public Criteria andLastLoginIpLessThanOrEqualTo(String value) {
			addCriterion("last_login_ip <=", value, "lastLoginIp");
			return (Criteria) this;
		}

		public Criteria andLastLoginIpLike(String value) {
			addCriterion("last_login_ip like", value, "lastLoginIp");
			return (Criteria) this;
		}

		public Criteria andLastLoginIpNotLike(String value) {
			addCriterion("last_login_ip not like", value, "lastLoginIp");
			return (Criteria) this;
		}

		public Criteria andLastLoginIpIn(List<String> values) {
			addCriterion("last_login_ip in", values, "lastLoginIp");
			return (Criteria) this;
		}

		public Criteria andLastLoginIpNotIn(List<String> values) {
			addCriterion("last_login_ip not in", values, "lastLoginIp");
			return (Criteria) this;
		}

		public Criteria andLastLoginIpBetween(String value1, String value2) {
			addCriterion("last_login_ip between", value1, value2, "lastLoginIp");
			return (Criteria) this;
		}

		public Criteria andLastLoginIpNotBetween(String value1, String value2) {
			addCriterion("last_login_ip not between", value1, value2,
					"lastLoginIp");
			return (Criteria) this;
		}

		public Criteria andCreatedAtIsNull() {
			addCriterion("created_at is null");
			return (Criteria) this;
		}

		public Criteria andCreatedAtIsNotNull() {
			addCriterion("created_at is not null");
			return (Criteria) this;
		}

		public Criteria andCreatedAtEqualTo(Date value) {
			addCriterion("created_at =", value, "createdAt");
			return (Criteria) this;
		}

		public Criteria andCreatedAtNotEqualTo(Date value) {
			addCriterion("created_at <>", value, "createdAt");
			return (Criteria) this;
		}

		public Criteria andCreatedAtGreaterThan(Date value) {
			addCriterion("created_at >", value, "createdAt");
			return (Criteria) this;
		}

		public Criteria andCreatedAtGreaterThanOrEqualTo(Date value) {
			addCriterion("created_at >=", value, "createdAt");
			return (Criteria) this;
		}

		public Criteria andCreatedAtLessThan(Date value) {
			addCriterion("created_at <", value, "createdAt");
			return (Criteria) this;
		}

		public Criteria andCreatedAtLessThanOrEqualTo(Date value) {
			addCriterion("created_at <=", value, "createdAt");
			return (Criteria) this;
		}

		public Criteria andCreatedAtIn(List<Date> values) {
			addCriterion("created_at in", values, "createdAt");
			return (Criteria) this;
		}

		public Criteria andCreatedAtNotIn(List<Date> values) {
			addCriterion("created_at not in", values, "createdAt");
			return (Criteria) this;
		}

		public Criteria andCreatedAtBetween(Date value1, Date value2) {
			addCriterion("created_at between", value1, value2, "createdAt");
			return (Criteria) this;
		}

		public Criteria andCreatedAtNotBetween(Date value1, Date value2) {
			addCriterion("created_at not between", value1, value2, "createdAt");
			return (Criteria) this;
		}

		public Criteria andUpdatedAtIsNull() {
			addCriterion("updated_at is null");
			return (Criteria) this;
		}

		public Criteria andUpdatedAtIsNotNull() {
			addCriterion("updated_at is not null");
			return (Criteria) this;
		}

		public Criteria andUpdatedAtEqualTo(Date value) {
			addCriterion("updated_at =", value, "updatedAt");
			return (Criteria) this;
		}

		public Criteria andUpdatedAtNotEqualTo(Date value) {
			addCriterion("updated_at <>", value, "updatedAt");
			return (Criteria) this;
		}

		public Criteria andUpdatedAtGreaterThan(Date value) {
			addCriterion("updated_at >", value, "updatedAt");
			return (Criteria) this;
		}

		public Criteria andUpdatedAtGreaterThanOrEqualTo(Date value) {
			addCriterion("updated_at >=", value, "updatedAt");
			return (Criteria) this;
		}

		public Criteria andUpdatedAtLessThan(Date value) {
			addCriterion("updated_at <", value, "updatedAt");
			return (Criteria) this;
		}

		public Criteria andUpdatedAtLessThanOrEqualTo(Date value) {
			addCriterion("updated_at <=", value, "updatedAt");
			return (Criteria) this;
		}

		public Criteria andUpdatedAtIn(List<Date> values) {
			addCriterion("updated_at in", values, "updatedAt");
			return (Criteria) this;
		}

		public Criteria andUpdatedAtNotIn(List<Date> values) {
			addCriterion("updated_at not in", values, "updatedAt");
			return (Criteria) this;
		}

		public Criteria andUpdatedAtBetween(Date value1, Date value2) {
			addCriterion("updated_at between", value1, value2, "updatedAt");
			return (Criteria) this;
		}

		public Criteria andUpdatedAtNotBetween(Date value1, Date value2) {
			addCriterion("updated_at not between", value1, value2, "updatedAt");
			return (Criteria) this;
		}

		public Criteria andCreatorIdIsNull() {
			addCriterion("creator_id is null");
			return (Criteria) this;
		}

		public Criteria andCreatorIdIsNotNull() {
			addCriterion("creator_id is not null");
			return (Criteria) this;
		}

		public Criteria andCreatorIdEqualTo(Integer value) {
			addCriterion("creator_id =", value, "creatorId");
			return (Criteria) this;
		}

		public Criteria andCreatorIdNotEqualTo(Integer value) {
			addCriterion("creator_id <>", value, "creatorId");
			return (Criteria) this;
		}

		public Criteria andCreatorIdGreaterThan(Integer value) {
			addCriterion("creator_id >", value, "creatorId");
			return (Criteria) this;
		}

		public Criteria andCreatorIdGreaterThanOrEqualTo(Integer value) {
			addCriterion("creator_id >=", value, "creatorId");
			return (Criteria) this;
		}

		public Criteria andCreatorIdLessThan(Integer value) {
			addCriterion("creator_id <", value, "creatorId");
			return (Criteria) this;
		}

		public Criteria andCreatorIdLessThanOrEqualTo(Integer value) {
			addCriterion("creator_id <=", value, "creatorId");
			return (Criteria) this;
		}

		public Criteria andCreatorIdIn(List<Integer> values) {
			addCriterion("creator_id in", values, "creatorId");
			return (Criteria) this;
		}

		public Criteria andCreatorIdNotIn(List<Integer> values) {
			addCriterion("creator_id not in", values, "creatorId");
			return (Criteria) this;
		}

		public Criteria andCreatorIdBetween(Integer value1, Integer value2) {
			addCriterion("creator_id between", value1, value2, "creatorId");
			return (Criteria) this;
		}

		public Criteria andCreatorIdNotBetween(Integer value1, Integer value2) {
			addCriterion("creator_id not between", value1, value2, "creatorId");
			return (Criteria) this;
		}

		public Criteria andUpdaterIdIsNull() {
			addCriterion("updater_id is null");
			return (Criteria) this;
		}

		public Criteria andUpdaterIdIsNotNull() {
			addCriterion("updater_id is not null");
			return (Criteria) this;
		}

		public Criteria andUpdaterIdEqualTo(Integer value) {
			addCriterion("updater_id =", value, "updaterId");
			return (Criteria) this;
		}

		public Criteria andUpdaterIdNotEqualTo(Integer value) {
			addCriterion("updater_id <>", value, "updaterId");
			return (Criteria) this;
		}

		public Criteria andUpdaterIdGreaterThan(Integer value) {
			addCriterion("updater_id >", value, "updaterId");
			return (Criteria) this;
		}

		public Criteria andUpdaterIdGreaterThanOrEqualTo(Integer value) {
			addCriterion("updater_id >=", value, "updaterId");
			return (Criteria) this;
		}

		public Criteria andUpdaterIdLessThan(Integer value) {
			addCriterion("updater_id <", value, "updaterId");
			return (Criteria) this;
		}

		public Criteria andUpdaterIdLessThanOrEqualTo(Integer value) {
			addCriterion("updater_id <=", value, "updaterId");
			return (Criteria) this;
		}

		public Criteria andUpdaterIdIn(List<Integer> values) {
			addCriterion("updater_id in", values, "updaterId");
			return (Criteria) this;
		}

		public Criteria andUpdaterIdNotIn(List<Integer> values) {
			addCriterion("updater_id not in", values, "updaterId");
			return (Criteria) this;
		}

		public Criteria andUpdaterIdBetween(Integer value1, Integer value2) {
			addCriterion("updater_id between", value1, value2, "updaterId");
			return (Criteria) this;
		}

		public Criteria andUpdaterIdNotBetween(Integer value1, Integer value2) {
			addCriterion("updater_id not between", value1, value2, "updaterId");
			return (Criteria) this;
		}

		public Criteria andFirstNameIsNull() {
			addCriterion("first_name is null");
			return (Criteria) this;
		}

		public Criteria andFirstNameIsNotNull() {
			addCriterion("first_name is not null");
			return (Criteria) this;
		}

		public Criteria andFirstNameEqualTo(String value) {
			addCriterion("first_name =", value, "firstName");
			return (Criteria) this;
		}

		public Criteria andFirstNameNotEqualTo(String value) {
			addCriterion("first_name <>", value, "firstName");
			return (Criteria) this;
		}

		public Criteria andFirstNameGreaterThan(String value) {
			addCriterion("first_name >", value, "firstName");
			return (Criteria) this;
		}

		public Criteria andFirstNameGreaterThanOrEqualTo(String value) {
			addCriterion("first_name >=", value, "firstName");
			return (Criteria) this;
		}

		public Criteria andFirstNameLessThan(String value) {
			addCriterion("first_name <", value, "firstName");
			return (Criteria) this;
		}

		public Criteria andFirstNameLessThanOrEqualTo(String value) {
			addCriterion("first_name <=", value, "firstName");
			return (Criteria) this;
		}

		public Criteria andFirstNameLike(String value) {
			addCriterion("first_name like", value, "firstName");
			return (Criteria) this;
		}

		public Criteria andFirstNameNotLike(String value) {
			addCriterion("first_name not like", value, "firstName");
			return (Criteria) this;
		}

		public Criteria andFirstNameIn(List<String> values) {
			addCriterion("first_name in", values, "firstName");
			return (Criteria) this;
		}

		public Criteria andFirstNameNotIn(List<String> values) {
			addCriterion("first_name not in", values, "firstName");
			return (Criteria) this;
		}

		public Criteria andFirstNameBetween(String value1, String value2) {
			addCriterion("first_name between", value1, value2, "firstName");
			return (Criteria) this;
		}

		public Criteria andFirstNameNotBetween(String value1, String value2) {
			addCriterion("first_name not between", value1, value2, "firstName");
			return (Criteria) this;
		}

		public Criteria andLastNameIsNull() {
			addCriterion("last_name is null");
			return (Criteria) this;
		}

		public Criteria andLastNameIsNotNull() {
			addCriterion("last_name is not null");
			return (Criteria) this;
		}

		public Criteria andLastNameEqualTo(String value) {
			addCriterion("last_name =", value, "lastName");
			return (Criteria) this;
		}

		public Criteria andLastNameNotEqualTo(String value) {
			addCriterion("last_name <>", value, "lastName");
			return (Criteria) this;
		}

		public Criteria andLastNameGreaterThan(String value) {
			addCriterion("last_name >", value, "lastName");
			return (Criteria) this;
		}

		public Criteria andLastNameGreaterThanOrEqualTo(String value) {
			addCriterion("last_name >=", value, "lastName");
			return (Criteria) this;
		}

		public Criteria andLastNameLessThan(String value) {
			addCriterion("last_name <", value, "lastName");
			return (Criteria) this;
		}

		public Criteria andLastNameLessThanOrEqualTo(String value) {
			addCriterion("last_name <=", value, "lastName");
			return (Criteria) this;
		}

		public Criteria andLastNameLike(String value) {
			addCriterion("last_name like", value, "lastName");
			return (Criteria) this;
		}

		public Criteria andLastNameNotLike(String value) {
			addCriterion("last_name not like", value, "lastName");
			return (Criteria) this;
		}

		public Criteria andLastNameIn(List<String> values) {
			addCriterion("last_name in", values, "lastName");
			return (Criteria) this;
		}

		public Criteria andLastNameNotIn(List<String> values) {
			addCriterion("last_name not in", values, "lastName");
			return (Criteria) this;
		}

		public Criteria andLastNameBetween(String value1, String value2) {
			addCriterion("last_name between", value1, value2, "lastName");
			return (Criteria) this;
		}

		public Criteria andLastNameNotBetween(String value1, String value2) {
			addCriterion("last_name not between", value1, value2, "lastName");
			return (Criteria) this;
		}

		public Criteria andUserLoggedInIsNull() {
			addCriterion("user_logged_in is null");
			return (Criteria) this;
		}

		public Criteria andUserLoggedInIsNotNull() {
			addCriterion("user_logged_in is not null");
			return (Criteria) this;
		}

		public Criteria andUserLoggedInEqualTo(Byte value) {
			addCriterion("user_logged_in =", value, "userLoggedIn");
			return (Criteria) this;
		}

		public Criteria andUserLoggedInNotEqualTo(Byte value) {
			addCriterion("user_logged_in <>", value, "userLoggedIn");
			return (Criteria) this;
		}

		public Criteria andUserLoggedInGreaterThan(Byte value) {
			addCriterion("user_logged_in >", value, "userLoggedIn");
			return (Criteria) this;
		}

		public Criteria andUserLoggedInGreaterThanOrEqualTo(Byte value) {
			addCriterion("user_logged_in >=", value, "userLoggedIn");
			return (Criteria) this;
		}

		public Criteria andUserLoggedInLessThan(Byte value) {
			addCriterion("user_logged_in <", value, "userLoggedIn");
			return (Criteria) this;
		}

		public Criteria andUserLoggedInLessThanOrEqualTo(Byte value) {
			addCriterion("user_logged_in <=", value, "userLoggedIn");
			return (Criteria) this;
		}

		public Criteria andUserLoggedInIn(List<Byte> values) {
			addCriterion("user_logged_in in", values, "userLoggedIn");
			return (Criteria) this;
		}

		public Criteria andUserLoggedInNotIn(List<Byte> values) {
			addCriterion("user_logged_in not in", values, "userLoggedIn");
			return (Criteria) this;
		}

		public Criteria andUserLoggedInBetween(Byte value1, Byte value2) {
			addCriterion("user_logged_in between", value1, value2,
					"userLoggedIn");
			return (Criteria) this;
		}

		public Criteria andUserLoggedInNotBetween(Byte value1, Byte value2) {
			addCriterion("user_logged_in not between", value1, value2,
					"userLoggedIn");
			return (Criteria) this;
		}

		public Criteria andUserTypeIsNull() {
			addCriterion("user_type is null");
			return (Criteria) this;
		}

		public Criteria andUserTypeIsNotNull() {
			addCriterion("user_type is not null");
			return (Criteria) this;
		}

		public Criteria andUserTypeEqualTo(Long value) {
			addCriterion("user_type =", value, "userType");
			return (Criteria) this;
		}

		public Criteria andUserTypeNotEqualTo(Long value) {
			addCriterion("user_type <>", value, "userType");
			return (Criteria) this;
		}

		public Criteria andUserTypeGreaterThan(Long value) {
			addCriterion("user_type >", value, "userType");
			return (Criteria) this;
		}

		public Criteria andUserTypeGreaterThanOrEqualTo(Long value) {
			addCriterion("user_type >=", value, "userType");
			return (Criteria) this;
		}

		public Criteria andUserTypeLessThan(Long value) {
			addCriterion("user_type <", value, "userType");
			return (Criteria) this;
		}

		public Criteria andUserTypeLessThanOrEqualTo(Long value) {
			addCriterion("user_type <=", value, "userType");
			return (Criteria) this;
		}

		public Criteria andUserTypeIn(List<Long> values) {
			addCriterion("user_type in", values, "userType");
			return (Criteria) this;
		}

		public Criteria andUserTypeNotIn(List<Long> values) {
			addCriterion("user_type not in", values, "userType");
			return (Criteria) this;
		}

		public Criteria andUserTypeBetween(Long value1, Long value2) {
			addCriterion("user_type between", value1, value2, "userType");
			return (Criteria) this;
		}

		public Criteria andUserTypeNotBetween(Long value1, Long value2) {
			addCriterion("user_type not between", value1, value2, "userType");
			return (Criteria) this;
		}

		public Criteria andGroupIdIsNull() {
			addCriterion("group_id is null");
			return (Criteria) this;
		}

		public Criteria andGroupIdIsNotNull() {
			addCriterion("group_id is not null");
			return (Criteria) this;
		}

		public Criteria andGroupIdEqualTo(Long value) {
			addCriterion("group_id =", value, "groupId");
			return (Criteria) this;
		}

		public Criteria andGroupIdNotEqualTo(Long value) {
			addCriterion("group_id <>", value, "groupId");
			return (Criteria) this;
		}

		public Criteria andGroupIdGreaterThan(Long value) {
			addCriterion("group_id >", value, "groupId");
			return (Criteria) this;
		}

		public Criteria andGroupIdGreaterThanOrEqualTo(Long value) {
			addCriterion("group_id >=", value, "groupId");
			return (Criteria) this;
		}

		public Criteria andGroupIdLessThan(Long value) {
			addCriterion("group_id <", value, "groupId");
			return (Criteria) this;
		}

		public Criteria andGroupIdLessThanOrEqualTo(Long value) {
			addCriterion("group_id <=", value, "groupId");
			return (Criteria) this;
		}

		public Criteria andGroupIdIn(List<Long> values) {
			addCriterion("group_id in", values, "groupId");
			return (Criteria) this;
		}

		public Criteria andGroupIdNotIn(List<Long> values) {
			addCriterion("group_id not in", values, "groupId");
			return (Criteria) this;
		}

		public Criteria andGroupIdBetween(Long value1, Long value2) {
			addCriterion("group_id between", value1, value2, "groupId");
			return (Criteria) this;
		}

		public Criteria andGroupIdNotBetween(Long value1, Long value2) {
			addCriterion("group_id not between", value1, value2, "groupId");
			return (Criteria) this;
		}

		public Criteria andTaskAddEmailIsNull() {
			addCriterion("task_add_email is null");
			return (Criteria) this;
		}

		public Criteria andTaskAddEmailIsNotNull() {
			addCriterion("task_add_email is not null");
			return (Criteria) this;
		}

		public Criteria andTaskAddEmailEqualTo(Boolean value) {
			addCriterion("task_add_email =", value, "taskAddEmail");
			return (Criteria) this;
		}

		public Criteria andTaskAddEmailNotEqualTo(Boolean value) {
			addCriterion("task_add_email <>", value, "taskAddEmail");
			return (Criteria) this;
		}

		public Criteria andTaskAddEmailGreaterThan(Boolean value) {
			addCriterion("task_add_email >", value, "taskAddEmail");
			return (Criteria) this;
		}

		public Criteria andTaskAddEmailGreaterThanOrEqualTo(Boolean value) {
			addCriterion("task_add_email >=", value, "taskAddEmail");
			return (Criteria) this;
		}

		public Criteria andTaskAddEmailLessThan(Boolean value) {
			addCriterion("task_add_email <", value, "taskAddEmail");
			return (Criteria) this;
		}

		public Criteria andTaskAddEmailLessThanOrEqualTo(Boolean value) {
			addCriterion("task_add_email <=", value, "taskAddEmail");
			return (Criteria) this;
		}

		public Criteria andTaskAddEmailIn(List<Boolean> values) {
			addCriterion("task_add_email in", values, "taskAddEmail");
			return (Criteria) this;
		}

		public Criteria andTaskAddEmailNotIn(List<Boolean> values) {
			addCriterion("task_add_email not in", values, "taskAddEmail");
			return (Criteria) this;
		}

		public Criteria andTaskAddEmailBetween(Boolean value1, Boolean value2) {
			addCriterion("task_add_email between", value1, value2,
					"taskAddEmail");
			return (Criteria) this;
		}

		public Criteria andTaskAddEmailNotBetween(Boolean value1, Boolean value2) {
			addCriterion("task_add_email not between", value1, value2,
					"taskAddEmail");
			return (Criteria) this;
		}

		public Criteria andTaskUpdateEmailIsNull() {
			addCriterion("task_update_email is null");
			return (Criteria) this;
		}

		public Criteria andTaskUpdateEmailIsNotNull() {
			addCriterion("task_update_email is not null");
			return (Criteria) this;
		}

		public Criteria andTaskUpdateEmailEqualTo(Boolean value) {
			addCriterion("task_update_email =", value, "taskUpdateEmail");
			return (Criteria) this;
		}

		public Criteria andTaskUpdateEmailNotEqualTo(Boolean value) {
			addCriterion("task_update_email <>", value, "taskUpdateEmail");
			return (Criteria) this;
		}

		public Criteria andTaskUpdateEmailGreaterThan(Boolean value) {
			addCriterion("task_update_email >", value, "taskUpdateEmail");
			return (Criteria) this;
		}

		public Criteria andTaskUpdateEmailGreaterThanOrEqualTo(Boolean value) {
			addCriterion("task_update_email >=", value, "taskUpdateEmail");
			return (Criteria) this;
		}

		public Criteria andTaskUpdateEmailLessThan(Boolean value) {
			addCriterion("task_update_email <", value, "taskUpdateEmail");
			return (Criteria) this;
		}

		public Criteria andTaskUpdateEmailLessThanOrEqualTo(Boolean value) {
			addCriterion("task_update_email <=", value, "taskUpdateEmail");
			return (Criteria) this;
		}

		public Criteria andTaskUpdateEmailIn(List<Boolean> values) {
			addCriterion("task_update_email in", values, "taskUpdateEmail");
			return (Criteria) this;
		}

		public Criteria andTaskUpdateEmailNotIn(List<Boolean> values) {
			addCriterion("task_update_email not in", values, "taskUpdateEmail");
			return (Criteria) this;
		}

		public Criteria andTaskUpdateEmailBetween(Boolean value1, Boolean value2) {
			addCriterion("task_update_email between", value1, value2,
					"taskUpdateEmail");
			return (Criteria) this;
		}

		public Criteria andTaskUpdateEmailNotBetween(Boolean value1,
				Boolean value2) {
			addCriterion("task_update_email not between", value1, value2,
					"taskUpdateEmail");
			return (Criteria) this;
		}
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table users
	 * @mbggenerated  Thu Apr 04 15:35:42 BST 2013
	 */
	public static class Criterion {
		private String condition;
		private Object value;
		private Object secondValue;
		private boolean noValue;
		private boolean singleValue;
		private boolean betweenValue;
		private boolean listValue;
		private String typeHandler;

		public String getCondition() {
			return condition;
		}

		public Object getValue() {
			return value;
		}

		public Object getSecondValue() {
			return secondValue;
		}

		public boolean isNoValue() {
			return noValue;
		}

		public boolean isSingleValue() {
			return singleValue;
		}

		public boolean isBetweenValue() {
			return betweenValue;
		}

		public boolean isListValue() {
			return listValue;
		}

		public String getTypeHandler() {
			return typeHandler;
		}

		protected Criterion(String condition) {
			super();
			this.condition = condition;
			this.typeHandler = null;
			this.noValue = true;
		}

		protected Criterion(String condition, Object value, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.typeHandler = typeHandler;
			if (value instanceof List<?>) {
				this.listValue = true;
			} else {
				this.singleValue = true;
			}
		}

		protected Criterion(String condition, Object value) {
			this(condition, value, null);
		}

		protected Criterion(String condition, Object value, Object secondValue,
				String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.secondValue = secondValue;
			this.typeHandler = typeHandler;
			this.betweenValue = true;
		}

		protected Criterion(String condition, Object value, Object secondValue) {
			this(condition, value, secondValue, null);
		}
	}

	/**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table users
     *
     * @mbggenerated do_not_delete_during_merge Mon Aug 06 10:08:53 BST 2012
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }
}