package com.jemmmedia.organise.mybatis.db.mybatis.model;

import java.util.Date;

public class User extends BaseModel {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column users.username
	 * @mbggenerated  Thu Apr 04 15:35:42 BST 2013
	 */
	private String username;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column users.email
	 * @mbggenerated  Thu Apr 04 15:35:42 BST 2013
	 */
	private String email;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column users.profileImage
	 * @mbggenerated  Thu Apr 04 15:35:42 BST 2013
	 */
	private String profileimage;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column users.crypted_password
	 * @mbggenerated  Thu Apr 04 15:35:42 BST 2013
	 */
	private String cryptedPassword;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column users.password_salt
	 * @mbggenerated  Thu Apr 04 15:35:42 BST 2013
	 */
	private String passwordSalt;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column users.persistence_token
	 * @mbggenerated  Thu Apr 04 15:35:42 BST 2013
	 */
	private String persistenceToken;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column users.region_id
	 * @mbggenerated  Thu Apr 04 15:35:42 BST 2013
	 */
	private Long regionId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column users.job_title
	 * @mbggenerated  Thu Apr 04 15:35:42 BST 2013
	 */
	private String jobTitle;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column users.login_count
	 * @mbggenerated  Thu Apr 04 15:35:42 BST 2013
	 */
	private Integer loginCount;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column users.failed_login_count
	 * @mbggenerated  Thu Apr 04 15:35:42 BST 2013
	 */
	private Integer failedLoginCount;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column users.last_request_at
	 * @mbggenerated  Thu Apr 04 15:35:42 BST 2013
	 */
	private Date lastRequestAt;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column users.current_login_at
	 * @mbggenerated  Thu Apr 04 15:35:42 BST 2013
	 */
	private Date currentLoginAt;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column users.last_login_at
	 * @mbggenerated  Thu Apr 04 15:35:42 BST 2013
	 */
	private Date lastLoginAt;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column users.current_login_ip
	 * @mbggenerated  Thu Apr 04 15:35:42 BST 2013
	 */
	private String currentLoginIp;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column users.last_login_ip
	 * @mbggenerated  Thu Apr 04 15:35:42 BST 2013
	 */
	private String lastLoginIp;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column users.creator_id
	 * @mbggenerated  Thu Apr 04 15:35:42 BST 2013
	 */
	private Integer creatorId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column users.updater_id
	 * @mbggenerated  Thu Apr 04 15:35:42 BST 2013
	 */
	private Integer updaterId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column users.first_name
	 * @mbggenerated  Thu Apr 04 15:35:42 BST 2013
	 */
	private String firstName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column users.last_name
	 * @mbggenerated  Thu Apr 04 15:35:42 BST 2013
	 */
	private String lastName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column users.user_logged_in
	 * @mbggenerated  Thu Apr 04 15:35:42 BST 2013
	 */
	private Byte userLoggedIn;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column users.user_type
	 * @mbggenerated  Thu Apr 04 15:35:42 BST 2013
	 */
	private Long userType;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column users.group_id
	 * @mbggenerated  Thu Apr 04 15:35:42 BST 2013
	 */
	private Long groupId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column users.task_add_email
	 * @mbggenerated  Thu Apr 04 15:35:42 BST 2013
	 */
	private Boolean taskAddEmail;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column users.task_update_email
	 * @mbggenerated  Thu Apr 04 15:35:42 BST 2013
	 */
	private Boolean taskUpdateEmail;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column users.username
	 * @return  the value of users.username
	 * @mbggenerated  Thu Apr 04 15:35:42 BST 2013
	 */
	public String getUsername() {
		return username;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column users.username
	 * @param username  the value for users.username
	 * @mbggenerated  Thu Apr 04 15:35:42 BST 2013
	 */
	public void setUsername(String username) {
		this.username = username == null ? null : username.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column users.email
	 * @return  the value of users.email
	 * @mbggenerated  Thu Apr 04 15:35:42 BST 2013
	 */
	public String getEmail() {
		return email;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column users.email
	 * @param email  the value for users.email
	 * @mbggenerated  Thu Apr 04 15:35:42 BST 2013
	 */
	public void setEmail(String email) {
		this.email = email == null ? null : email.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column users.profileImage
	 * @return  the value of users.profileImage
	 * @mbggenerated  Thu Apr 04 15:35:42 BST 2013
	 */
	public String getProfileimage() {
		return profileimage;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column users.profileImage
	 * @param profileimage  the value for users.profileImage
	 * @mbggenerated  Thu Apr 04 15:35:42 BST 2013
	 */
	public void setProfileimage(String profileimage) {
		this.profileimage = profileimage == null ? null : profileimage.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column users.crypted_password
	 * @return  the value of users.crypted_password
	 * @mbggenerated  Thu Apr 04 15:35:42 BST 2013
	 */
	public String getCryptedPassword() {
		return cryptedPassword;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column users.crypted_password
	 * @param cryptedPassword  the value for users.crypted_password
	 * @mbggenerated  Thu Apr 04 15:35:42 BST 2013
	 */
	public void setCryptedPassword(String cryptedPassword) {
		this.cryptedPassword = cryptedPassword == null ? null : cryptedPassword
				.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column users.password_salt
	 * @return  the value of users.password_salt
	 * @mbggenerated  Thu Apr 04 15:35:42 BST 2013
	 */
	public String getPasswordSalt() {
		return passwordSalt;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column users.password_salt
	 * @param passwordSalt  the value for users.password_salt
	 * @mbggenerated  Thu Apr 04 15:35:42 BST 2013
	 */
	public void setPasswordSalt(String passwordSalt) {
		this.passwordSalt = passwordSalt == null ? null : passwordSalt.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column users.persistence_token
	 * @return  the value of users.persistence_token
	 * @mbggenerated  Thu Apr 04 15:35:42 BST 2013
	 */
	public String getPersistenceToken() {
		return persistenceToken;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column users.persistence_token
	 * @param persistenceToken  the value for users.persistence_token
	 * @mbggenerated  Thu Apr 04 15:35:42 BST 2013
	 */
	public void setPersistenceToken(String persistenceToken) {
		this.persistenceToken = persistenceToken == null ? null
				: persistenceToken.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column users.region_id
	 * @return  the value of users.region_id
	 * @mbggenerated  Thu Apr 04 15:35:42 BST 2013
	 */
	public Long getRegionId() {
		return regionId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column users.region_id
	 * @param regionId  the value for users.region_id
	 * @mbggenerated  Thu Apr 04 15:35:42 BST 2013
	 */
	public void setRegionId(Long regionId) {
		this.regionId = regionId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column users.job_title
	 * @return  the value of users.job_title
	 * @mbggenerated  Thu Apr 04 15:35:42 BST 2013
	 */
	public String getJobTitle() {
		return jobTitle;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column users.job_title
	 * @param jobTitle  the value for users.job_title
	 * @mbggenerated  Thu Apr 04 15:35:42 BST 2013
	 */
	public void setJobTitle(String jobTitle) {
		this.jobTitle = jobTitle == null ? null : jobTitle.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column users.login_count
	 * @return  the value of users.login_count
	 * @mbggenerated  Thu Apr 04 15:35:42 BST 2013
	 */
	public Integer getLoginCount() {
		return loginCount;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column users.login_count
	 * @param loginCount  the value for users.login_count
	 * @mbggenerated  Thu Apr 04 15:35:42 BST 2013
	 */
	public void setLoginCount(Integer loginCount) {
		this.loginCount = loginCount;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column users.failed_login_count
	 * @return  the value of users.failed_login_count
	 * @mbggenerated  Thu Apr 04 15:35:42 BST 2013
	 */
	public Integer getFailedLoginCount() {
		return failedLoginCount;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column users.failed_login_count
	 * @param failedLoginCount  the value for users.failed_login_count
	 * @mbggenerated  Thu Apr 04 15:35:42 BST 2013
	 */
	public void setFailedLoginCount(Integer failedLoginCount) {
		this.failedLoginCount = failedLoginCount;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column users.last_request_at
	 * @return  the value of users.last_request_at
	 * @mbggenerated  Thu Apr 04 15:35:42 BST 2013
	 */
	public Date getLastRequestAt() {
		return lastRequestAt;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column users.last_request_at
	 * @param lastRequestAt  the value for users.last_request_at
	 * @mbggenerated  Thu Apr 04 15:35:42 BST 2013
	 */
	public void setLastRequestAt(Date lastRequestAt) {
		this.lastRequestAt = lastRequestAt;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column users.current_login_at
	 * @return  the value of users.current_login_at
	 * @mbggenerated  Thu Apr 04 15:35:42 BST 2013
	 */
	public Date getCurrentLoginAt() {
		return currentLoginAt;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column users.current_login_at
	 * @param currentLoginAt  the value for users.current_login_at
	 * @mbggenerated  Thu Apr 04 15:35:42 BST 2013
	 */
	public void setCurrentLoginAt(Date currentLoginAt) {
		this.currentLoginAt = currentLoginAt;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column users.last_login_at
	 * @return  the value of users.last_login_at
	 * @mbggenerated  Thu Apr 04 15:35:42 BST 2013
	 */
	public Date getLastLoginAt() {
		return lastLoginAt;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column users.last_login_at
	 * @param lastLoginAt  the value for users.last_login_at
	 * @mbggenerated  Thu Apr 04 15:35:42 BST 2013
	 */
	public void setLastLoginAt(Date lastLoginAt) {
		this.lastLoginAt = lastLoginAt;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column users.current_login_ip
	 * @return  the value of users.current_login_ip
	 * @mbggenerated  Thu Apr 04 15:35:42 BST 2013
	 */
	public String getCurrentLoginIp() {
		return currentLoginIp;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column users.current_login_ip
	 * @param currentLoginIp  the value for users.current_login_ip
	 * @mbggenerated  Thu Apr 04 15:35:42 BST 2013
	 */
	public void setCurrentLoginIp(String currentLoginIp) {
		this.currentLoginIp = currentLoginIp == null ? null : currentLoginIp
				.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column users.last_login_ip
	 * @return  the value of users.last_login_ip
	 * @mbggenerated  Thu Apr 04 15:35:42 BST 2013
	 */
	public String getLastLoginIp() {
		return lastLoginIp;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column users.last_login_ip
	 * @param lastLoginIp  the value for users.last_login_ip
	 * @mbggenerated  Thu Apr 04 15:35:42 BST 2013
	 */
	public void setLastLoginIp(String lastLoginIp) {
		this.lastLoginIp = lastLoginIp == null ? null : lastLoginIp.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column users.creator_id
	 * @return  the value of users.creator_id
	 * @mbggenerated  Thu Apr 04 15:35:42 BST 2013
	 */
	public Integer getCreatorId() {
		return creatorId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column users.creator_id
	 * @param creatorId  the value for users.creator_id
	 * @mbggenerated  Thu Apr 04 15:35:42 BST 2013
	 */
	public void setCreatorId(Integer creatorId) {
		this.creatorId = creatorId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column users.updater_id
	 * @return  the value of users.updater_id
	 * @mbggenerated  Thu Apr 04 15:35:42 BST 2013
	 */
	public Integer getUpdaterId() {
		return updaterId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column users.updater_id
	 * @param updaterId  the value for users.updater_id
	 * @mbggenerated  Thu Apr 04 15:35:42 BST 2013
	 */
	public void setUpdaterId(Integer updaterId) {
		this.updaterId = updaterId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column users.first_name
	 * @return  the value of users.first_name
	 * @mbggenerated  Thu Apr 04 15:35:42 BST 2013
	 */
	public String getFirstName() {
		return firstName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column users.first_name
	 * @param firstName  the value for users.first_name
	 * @mbggenerated  Thu Apr 04 15:35:42 BST 2013
	 */
	public void setFirstName(String firstName) {
		this.firstName = firstName == null ? null : firstName.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column users.last_name
	 * @return  the value of users.last_name
	 * @mbggenerated  Thu Apr 04 15:35:42 BST 2013
	 */
	public String getLastName() {
		return lastName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column users.last_name
	 * @param lastName  the value for users.last_name
	 * @mbggenerated  Thu Apr 04 15:35:42 BST 2013
	 */
	public void setLastName(String lastName) {
		this.lastName = lastName == null ? null : lastName.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column users.user_logged_in
	 * @return  the value of users.user_logged_in
	 * @mbggenerated  Thu Apr 04 15:35:42 BST 2013
	 */
	public Byte getUserLoggedIn() {
		return userLoggedIn;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column users.user_logged_in
	 * @param userLoggedIn  the value for users.user_logged_in
	 * @mbggenerated  Thu Apr 04 15:35:42 BST 2013
	 */
	public void setUserLoggedIn(Byte userLoggedIn) {
		this.userLoggedIn = userLoggedIn;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column users.user_type
	 * @return  the value of users.user_type
	 * @mbggenerated  Thu Apr 04 15:35:42 BST 2013
	 */
	public Long getUserType() {
		return userType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column users.user_type
	 * @param userType  the value for users.user_type
	 * @mbggenerated  Thu Apr 04 15:35:42 BST 2013
	 */
	public void setUserType(Long userType) {
		this.userType = userType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column users.group_id
	 * @return  the value of users.group_id
	 * @mbggenerated  Thu Apr 04 15:35:42 BST 2013
	 */
	public Long getGroupId() {
		return groupId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column users.group_id
	 * @param groupId  the value for users.group_id
	 * @mbggenerated  Thu Apr 04 15:35:42 BST 2013
	 */
	public void setGroupId(Long groupId) {
		this.groupId = groupId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column users.task_add_email
	 * @return  the value of users.task_add_email
	 * @mbggenerated  Thu Apr 04 15:35:42 BST 2013
	 */
	public Boolean getTaskAddEmail() {
		return taskAddEmail;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column users.task_add_email
	 * @param taskAddEmail  the value for users.task_add_email
	 * @mbggenerated  Thu Apr 04 15:35:42 BST 2013
	 */
	public void setTaskAddEmail(Boolean taskAddEmail) {
		this.taskAddEmail = taskAddEmail;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column users.task_update_email
	 * @return  the value of users.task_update_email
	 * @mbggenerated  Thu Apr 04 15:35:42 BST 2013
	 */
	public Boolean getTaskUpdateEmail() {
		return taskUpdateEmail;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column users.task_update_email
	 * @param taskUpdateEmail  the value for users.task_update_email
	 * @mbggenerated  Thu Apr 04 15:35:42 BST 2013
	 */
	public void setTaskUpdateEmail(Boolean taskUpdateEmail) {
		this.taskUpdateEmail = taskUpdateEmail;
	}
	
}