package com.jemmmedia.organise.mybatis.db.mybatis.model;

import java.util.Date;

public class ViewType {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column view_type.user_id
     *
     * @mbggenerated Mon Jul 29 15:10:25 BST 2013
     */
    private Long userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column view_type.view_type
     *
     * @mbggenerated Mon Jul 29 15:10:25 BST 2013
     */
    private Byte viewType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column view_type.created_at
     *
     * @mbggenerated Mon Jul 29 15:10:25 BST 2013
     */
    private Date createdAt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column view_type.updated_at
     *
     * @mbggenerated Mon Jul 29 15:10:25 BST 2013
     */
    private Date updatedAt;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column view_type.user_id
     *
     * @return the value of view_type.user_id
     *
     * @mbggenerated Mon Jul 29 15:10:25 BST 2013
     */
    public Long getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column view_type.user_id
     *
     * @param userId the value for view_type.user_id
     *
     * @mbggenerated Mon Jul 29 15:10:25 BST 2013
     */
    public void setUserId(Long userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column view_type.view_type
     *
     * @return the value of view_type.view_type
     *
     * @mbggenerated Mon Jul 29 15:10:25 BST 2013
     */
    public Byte getViewType() {
        return viewType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column view_type.view_type
     *
     * @param viewType the value for view_type.view_type
     *
     * @mbggenerated Mon Jul 29 15:10:25 BST 2013
     */
    public void setViewType(Byte viewType) {
        this.viewType = viewType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column view_type.created_at
     *
     * @return the value of view_type.created_at
     *
     * @mbggenerated Mon Jul 29 15:10:25 BST 2013
     */
    public Date getCreatedAt() {
        return createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column view_type.created_at
     *
     * @param createdAt the value for view_type.created_at
     *
     * @mbggenerated Mon Jul 29 15:10:25 BST 2013
     */
    public void setCreatedAt(Date createdAt) {
        this.createdAt = createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column view_type.updated_at
     *
     * @return the value of view_type.updated_at
     *
     * @mbggenerated Mon Jul 29 15:10:25 BST 2013
     */
    public Date getUpdatedAt() {
        return updatedAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column view_type.updated_at
     *
     * @param updatedAt the value for view_type.updated_at
     *
     * @mbggenerated Mon Jul 29 15:10:25 BST 2013
     */
    public void setUpdatedAt(Date updatedAt) {
        this.updatedAt = updatedAt;
    }
}