package com.jemmmedia.organise.mybatis.db.mybatis.dao;


import java.util.List;

import org.apache.ibatis.annotations.Param;

import com.jemmmedia.organise.mybatis.db.mybatis.model.Annoucement;
import com.jemmmedia.organise.mybatis.db.mybatis.model.AnnoucementExample;

public interface AnnoucementMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table announcements
     *
     * @mbggenerated Mon Aug 06 10:08:53 BST 2012
     */
    int countByExample(Annoucement example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table announcements
     *
     * @mbggenerated Mon Aug 06 10:08:53 BST 2012
     */
    int deleteByExample(Annoucement example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table announcements
     *
     * @mbggenerated Mon Aug 06 10:08:53 BST 2012
     */
    int insert(Annoucement record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table announcements
     *
     * @mbggenerated Mon Aug 06 10:08:53 BST 2012
     */
    int insertSelective(Annoucement record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table announcements
     *
     * @mbggenerated Mon Aug 06 10:08:53 BST 2012
     */
    List<Annoucement> selectByExampleWithBLOBs(AnnoucementExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table announcements
     *
     * @mbggenerated Mon Aug 06 10:08:53 BST 2012
     */
    List<Annoucement> selectByExample(AnnoucementExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table announcements
     *
     * @mbggenerated Mon Aug 06 10:08:53 BST 2012
     */
    int updateByExampleSelective(@Param("record") Annoucement record, @Param("example") AnnoucementExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table announcements
     *
     * @mbggenerated Mon Aug 06 10:08:53 BST 2012
     */
    int updateByExampleWithBLOBs(@Param("record") Annoucement record, @Param("example") AnnoucementExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table announcements
     *
     * @mbggenerated Mon Aug 06 10:08:53 BST 2012
     */
    int updateByExample(@Param("record") Annoucement record, @Param("example") AnnoucementExample example);
}