package com.jemmmedia.organise.mybatis.db.mybatis.dao;


import java.util.List;
import org.apache.ibatis.annotations.Param;

import com.jemmmedia.organise.mybatis.db.mybatis.model.Announcements;
import com.jemmmedia.organise.mybatis.db.mybatis.model.AnnouncementsExample;

public interface AnnouncementsMapper {
    /**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table announcements
	 * @mbggenerated  Mon Mar 25 13:45:28 GMT 2013
	 */
	int countByExample(AnnouncementsExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table announcements
	 * @mbggenerated  Mon Mar 25 13:45:28 GMT 2013
	 */
	int deleteByExample(AnnouncementsExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table announcements
	 * @mbggenerated  Mon Mar 25 13:45:28 GMT 2013
	 */
	int deleteByPrimaryKey(Long id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table announcements
	 * @mbggenerated  Mon Mar 25 13:45:28 GMT 2013
	 */
	int insert(Announcements record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table announcements
	 * @mbggenerated  Mon Mar 25 13:45:28 GMT 2013
	 */
	int insertSelective(Announcements record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table announcements
	 * @mbggenerated  Mon Mar 25 13:45:28 GMT 2013
	 */
	List<Announcements> selectByExampleWithBLOBs(AnnouncementsExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table announcements
	 * @mbggenerated  Mon Mar 25 13:45:28 GMT 2013
	 */
	List<Announcements> selectByExample(AnnouncementsExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table announcements
	 * @mbggenerated  Mon Mar 25 13:45:28 GMT 2013
	 */
	Announcements selectByPrimaryKey(Long id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table announcements
	 * @mbggenerated  Mon Mar 25 13:45:28 GMT 2013
	 */
	int updateByExampleSelective(@Param("record") Announcements record,
			@Param("example") AnnouncementsExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table announcements
	 * @mbggenerated  Mon Mar 25 13:45:28 GMT 2013
	 */
	int updateByExampleWithBLOBs(@Param("record") Announcements record,
			@Param("example") AnnouncementsExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table announcements
	 * @mbggenerated  Mon Mar 25 13:45:28 GMT 2013
	 */
	int updateByExample(@Param("record") Announcements record,
			@Param("example") AnnouncementsExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table announcements
	 * @mbggenerated  Mon Mar 25 13:45:28 GMT 2013
	 */
	int updateByPrimaryKeySelective(Announcements record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table announcements
	 * @mbggenerated  Mon Mar 25 13:45:28 GMT 2013
	 */
	int updateByPrimaryKeyWithBLOBs(Announcements record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table announcements
	 * @mbggenerated  Mon Mar 25 13:45:28 GMT 2013
	 */
	int updateByPrimaryKey(Announcements record);

	List<Announcements> selectAnnouncementsBetweenDates(@Param("groupId")long groupId, @Param("regionId")long regionId);
}