package com.jemmmedia.organise.mybatis.db.mybatis.dao;

import java.util.List;

import org.apache.ibatis.annotations.Param;

import com.jemmmedia.organise.mybatis.db.mybatis.model.Dept;
import com.jemmmedia.organise.mybatis.db.mybatis.model.DeptExample;



public interface DeptMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table dept
	 * @mbggenerated  Fri Aug 23 12:49:25 BST 2013
	 */
	int countByExample(DeptExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table dept
	 * @mbggenerated  Fri Aug 23 12:49:25 BST 2013
	 */
	int deleteByExample(DeptExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table dept
	 * @mbggenerated  Fri Aug 23 12:49:25 BST 2013
	 */
	int deleteByPrimaryKey(Long id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table dept
	 * @mbggenerated  Fri Aug 23 12:49:25 BST 2013
	 */
	int insert(Dept record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table dept
	 * @mbggenerated  Fri Aug 23 12:49:25 BST 2013
	 */
	int insertSelective(Dept record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table dept
	 * @mbggenerated  Fri Aug 23 12:49:25 BST 2013
	 */
	List<Dept> selectByExample(DeptExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table dept
	 * @mbggenerated  Fri Aug 23 12:49:25 BST 2013
	 */
	Dept selectByPrimaryKey(Long id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table dept
	 * @mbggenerated  Fri Aug 23 12:49:25 BST 2013
	 */
	int updateByExampleSelective(@Param("record") Dept record,
			@Param("example") DeptExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table dept
	 * @mbggenerated  Fri Aug 23 12:49:25 BST 2013
	 */
	int updateByExample(@Param("record") Dept record,
			@Param("example") DeptExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table dept
	 * @mbggenerated  Fri Aug 23 12:49:25 BST 2013
	 */
	int updateByPrimaryKeySelective(Dept record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table dept
	 * @mbggenerated  Fri Aug 23 12:49:25 BST 2013
	 */
	int updateByPrimaryKey(Dept record);

	List<Dept> selectAllDepts(long groupId);
	
	List<Dept> selectAllUsersInDepts(long groupId);
	
	List<String> selectUsersEmailInDept(long deptId);
}