package com.jemmmedia.organise.mybatis.db.mybatis.dao;


import java.util.List;

import org.apache.ibatis.annotations.Param;

import com.jemmmedia.organise.mybatis.db.mybatis.model.DeptUsers;
import com.jemmmedia.organise.mybatis.db.mybatis.model.DeptUsersExample;
import com.jemmmedia.organise.mybatis.db.mybatis.model.DeptUsersKey;

public interface DeptUsersMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dept_users
     *
     * @mbggenerated Wed Aug 21 17:48:42 BST 2013
     */
    int countByExample(DeptUsersExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dept_users
     *
     * @mbggenerated Wed Aug 21 17:48:42 BST 2013
     */
    int deleteByExample(DeptUsersExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dept_users
     *
     * @mbggenerated Wed Aug 21 17:48:42 BST 2013
     */
    int deleteByPrimaryKey(DeptUsersKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dept_users
     *
     * @mbggenerated Wed Aug 21 17:48:42 BST 2013
     */
    int insert(DeptUsers record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dept_users
     *
     * @mbggenerated Wed Aug 21 17:48:42 BST 2013
     */
    int insertSelective(DeptUsers record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dept_users
     *
     * @mbggenerated Wed Aug 21 17:48:42 BST 2013
     */
    List<DeptUsers> selectByExample(DeptUsersExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dept_users
     *
     * @mbggenerated Wed Aug 21 17:48:42 BST 2013
     */
    DeptUsers selectByPrimaryKey(DeptUsersKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dept_users
     *
     * @mbggenerated Wed Aug 21 17:48:42 BST 2013
     */
    int updateByExampleSelective(@Param("record") DeptUsers record, @Param("example") DeptUsersExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dept_users
     *
     * @mbggenerated Wed Aug 21 17:48:42 BST 2013
     */
    int updateByExample(@Param("record") DeptUsers record, @Param("example") DeptUsersExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dept_users
     *
     * @mbggenerated Wed Aug 21 17:48:42 BST 2013
     */
    int updateByPrimaryKeySelective(DeptUsers record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dept_users
     *
     * @mbggenerated Wed Aug 21 17:48:42 BST 2013
     */
    int updateByPrimaryKey(DeptUsers record);
    
    
    void deleteAllUserDept(long userId);
}