package com.jemmmedia.organise.mybatis.db.mybatis.dao;

import java.util.Date;
import java.util.List;

import org.apache.ibatis.annotations.Param;

import com.jemmmedia.organise.mybatis.db.mybatis.model.Dept;
import com.jemmmedia.organise.mybatis.db.mybatis.model.FeedEntry;
import com.jemmmedia.organise.mybatis.db.mybatis.model.FeedEntryBean;
import com.jemmmedia.organise.mybatis.db.mybatis.model.FeedEntryExample;



public interface FeedEntryMapper {
    /**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table feed_entries
	 * @mbggenerated  Tue Oct 29 13:42:10 GMT 2013
	 */
	int countByExample(FeedEntryExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table feed_entries
	 * @mbggenerated  Tue Oct 29 13:42:10 GMT 2013
	 */
	int deleteByExample(FeedEntryExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table feed_entries
	 * @mbggenerated  Tue Oct 29 13:42:10 GMT 2013
	 */
	int deleteByPrimaryKey(Long id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table feed_entries
	 * @mbggenerated  Tue Oct 29 13:42:10 GMT 2013
	 */
	int insert(FeedEntry record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table feed_entries
	 * @mbggenerated  Tue Oct 29 13:42:10 GMT 2013
	 */
	int insertSelective(FeedEntry record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table feed_entries
	 * @mbggenerated  Tue Oct 29 13:42:10 GMT 2013
	 */
	List<FeedEntry> selectByExampleWithBLOBs(FeedEntryExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table feed_entries
	 * @mbggenerated  Tue Oct 29 13:42:10 GMT 2013
	 */
	List<FeedEntry> selectByExample(FeedEntryExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table feed_entries
	 * @mbggenerated  Tue Oct 29 13:42:10 GMT 2013
	 */
	FeedEntry selectByPrimaryKey(Long id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table feed_entries
	 * @mbggenerated  Tue Oct 29 13:42:10 GMT 2013
	 */
	int updateByExampleSelective(@Param("record") FeedEntry record,
			@Param("example") FeedEntryExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table feed_entries
	 * @mbggenerated  Tue Oct 29 13:42:10 GMT 2013
	 */
	int updateByExampleWithBLOBs(@Param("record") FeedEntry record,
			@Param("example") FeedEntryExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table feed_entries
	 * @mbggenerated  Tue Oct 29 13:42:10 GMT 2013
	 */
	int updateByExample(@Param("record") FeedEntry record,
			@Param("example") FeedEntryExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table feed_entries
	 * @mbggenerated  Tue Oct 29 13:42:10 GMT 2013
	 */
	int updateByPrimaryKeySelective(FeedEntry record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table feed_entries
	 * @mbggenerated  Tue Oct 29 13:42:10 GMT 2013
	 */
	int updateByPrimaryKeyWithBLOBs(FeedEntry record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table feed_entries
	 * @mbggenerated  Tue Oct 29 13:42:10 GMT 2013
	 */
	int updateByPrimaryKey(FeedEntry record);

	List<FeedEntryBean> selectFeeds(@Param ("start") int start,@Param("userId") long userId);
	
	List<FeedEntryBean> searchFeeds(@Param ("start") int start, @Param("searchText") String searchText,@Param("userId") long userId);	
	
	List<FeedEntryBean> selectChildFeeds(long id);
	
	List<FeedEntryBean> filterFeeds(FeedEntryBean feedEntryBean);
	
	List<FeedEntryBean> selectFollowingTasks(@Param ("start") int start, @Param("followerId") long followerId, @Param("feedSourceId") long feedSourceId);
	
	List<FeedEntryBean>multiSourceFilterFeeds(@Param("userId") int userId, @Param("pageStart") int pageStart);
	
	List<FeedEntryBean> selectRecentlyViewed(@Param("viewerId") long viewerId, @Param("id") long id);
	
	List<FeedEntryBean> selectAssignedTask(@Param("assignTo") long viewerId, @Param("id") long id);
	
	List<FeedEntryBean> selectReplyDetail(long id);
	
	byte checkUpdates(long id);
	
	int updateRemaining(@Param("feedSourceId") Long feedSourceId, @Param("assignTo") Long assignTo);
	
	int filterFeedsCount(FeedEntryBean feedEntryBean);
	
	int feedsCount();
	
	void updateMainStatus(@Param("status")int status,
						  @Param("parentId")long parentId,
						  @Param("updatedAt") Date updateAt,
						  @Param("updatedBy") long updatedBy, 
						  @Param("urgentStatus")boolean urgentStatus,
						  @Param("assignTo") Long assignTo,
						  @Param("assignToDept") Long assignToDept);
	
	int updateFollow(@Param("fId")int fId,@Param("id")long id);
	
	int updateRecentlyViewed(@Param("viewerId")long viewerId, @Param("id") long id);
	
	List<FeedEntryBean> selectlastViewedDate(long userId);
	
	List<FeedEntryBean> displayTodaysTasksPending(@Param ("start") int start,@Param("userId")long userId);
	
	int todaysTasksPending(long userId);
	
	List<FeedEntryBean> displayOldTasksPending(@Param ("start") int start,@Param("userId")long userId);
	
	int oldTasksPending(long userId);
	
	List<FeedEntryBean> displayUrgentTasks(@Param ("start") int start,@Param("userId")long userId);
	
	int urgentTasks(long userId);
	
	int tasksCompleted(long groupId);
	
	int tasksOpen(long groupId);
	
	int tasksPending(long groupId);
	
	int commentsCount(long groupId);
	
	List<FeedEntryBean> displayTodaysDueTasks(@Param ("start") int start,@Param("userId")long userId);
	
	List<FeedEntryBean> displayAllMyTasks(@Param ("start") int start,
										  @Param("userId")long userId, 
										  @Param("orderBy")int orderBy,
										  @Param("feedSourceId") long feedSourceId,
										  @Param("deptIds") List<Dept> deptIds);
	
	int todaysDueTasks(long userId);
	
	List<String> selectTasksCount(long userId);
	
	List<FeedEntryBean> selectTaskCreatedByUsers(@Param("value") int value,@Param("groupId")long groupId);
	
	List<FeedEntryBean> selectTaskCompletedByUsers(@Param("value")int value,@Param("groupId")long groupId);
	
	List<FeedEntryBean> selectTaskAssignedToUsers(@Param("value")int value,@Param("groupId")long groupId);
	
}