package com.jemmmedia.organise.mybatis.db.mybatis.dao;


import java.util.List;

import org.apache.ibatis.annotations.Param;

import com.jemmmedia.organise.mybatis.db.mybatis.model.Feeds;
import com.jemmmedia.organise.mybatis.db.mybatis.model.FeedsExample;

public interface FeedsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table feeds
     *
     * @mbggenerated Fri Sep 21 12:03:33 BST 2012
     */
    int countByExample(FeedsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table feeds
     *
     * @mbggenerated Fri Sep 21 12:03:33 BST 2012
     */
    int deleteByExample(FeedsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table feeds
     *
     * @mbggenerated Fri Sep 21 12:03:33 BST 2012
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table feeds
     *
     * @mbggenerated Fri Sep 21 12:03:33 BST 2012
     */
    int insert(Feeds record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table feeds
     *
     * @mbggenerated Fri Sep 21 12:03:33 BST 2012
     */
    int insertSelective(Feeds record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table feeds
     *
     * @mbggenerated Fri Sep 21 12:03:33 BST 2012
     */
    List<Feeds> selectByExample(FeedsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table feeds
     *
     * @mbggenerated Fri Sep 21 12:03:33 BST 2012
     */
    Feeds selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table feeds
     *
     * @mbggenerated Fri Sep 21 12:03:33 BST 2012
     */
    int updateByExampleSelective(@Param("record") Feeds record, @Param("example") FeedsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table feeds
     *
     * @mbggenerated Fri Sep 21 12:03:33 BST 2012
     */
    int updateByExample(@Param("record") Feeds record, @Param("example") FeedsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table feeds
     *
     * @mbggenerated Fri Sep 21 12:03:33 BST 2012
     */
    int updateByPrimaryKeySelective(Feeds record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table feeds
     *
     * @mbggenerated Fri Sep 21 12:03:33 BST 2012
     */
    int updateByPrimaryKey(Feeds record);
}