package com.jemmmedia.organise.mybatis.db.mybatis.dao;

import java.util.List;
import java.util.Map;

import org.apache.ibatis.annotations.MapKey;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.Select;

import com.jemmmedia.organise.mybatis.db.mybatis.model.FeedSource;
import com.jemmmedia.organise.mybatis.db.mybatis.model.FeedSourceExample;
import com.jemmmedia.organise.mybatis.db.mybatis.model.FeedSourceExtBean;

public interface FeedSourceMapper {
    /**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table feed_sources
	 * @mbggenerated  Mon Feb 18 22:13:09 GMT 2013
	 */
	int countByExample(FeedSourceExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table feed_sources
	 * @mbggenerated  Mon Feb 18 22:13:09 GMT 2013
	 */
	int deleteByExample(FeedSourceExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table feed_sources
	 * @mbggenerated  Mon Feb 18 22:13:09 GMT 2013
	 */
	int deleteByPrimaryKey(Long id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table feed_sources
	 * @mbggenerated  Mon Feb 18 22:13:09 GMT 2013
	 */
	int insert(FeedSource record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table feed_sources
	 * @mbggenerated  Mon Feb 18 22:13:09 GMT 2013
	 */
	int insertSelective(FeedSource record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table feed_sources
	 * @mbggenerated  Mon Feb 18 22:13:09 GMT 2013
	 */
	List<FeedSource> selectByExample(FeedSourceExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table feed_sources
	 * @mbggenerated  Mon Feb 18 22:13:09 GMT 2013
	 */
	FeedSource selectByPrimaryKey(Long id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table feed_sources
	 * @mbggenerated  Mon Feb 18 22:13:09 GMT 2013
	 */
	int updateByExampleSelective(@Param("record") FeedSource record,
			@Param("example") FeedSourceExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table feed_sources
	 * @mbggenerated  Mon Feb 18 22:13:09 GMT 2013
	 */
	int updateByExample(@Param("record") FeedSource record,
			@Param("example") FeedSourceExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table feed_sources
	 * @mbggenerated  Mon Feb 18 22:13:09 GMT 2013
	 */
	int updateByPrimaryKeySelective(FeedSource record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table feed_sources
	 * @mbggenerated  Mon Feb 18 22:13:09 GMT 2013
	 */
	int updateByPrimaryKey(FeedSource record);

	@Select("SELECT id, name, colour FROM feed_sources")
    @MapKey("id")
    Map<Integer,FeedSource> getAllSources();
    
    List<FeedSourceExtBean> selectFeedSources();
    
    List<FeedSourceExtBean> selectUsersFeedSources(long userId);
    
    List<FeedSourceExtBean> selectAllSources(long groupId);
    
    List<FeedSource> selectFollowCat(long followerId);
    
    FeedSourceExtBean selectFeedSourceForEdit(long id);
    
    void deleteSource(long id);
    
    void deleteSubSource(long id);
    
    int topicsCount(long groupId);
    
    List<FeedSourceExtBean> selectSubTopics(long parentId);
    
    
}