package com.jemmmedia.organise.mybatis.db.mybatis.dao;

import java.util.List;
import java.util.Map;

import org.apache.ibatis.annotations.MapKey;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.Select;

import com.jemmmedia.organise.mybatis.db.mybatis.model.FeedTypes;
import com.jemmmedia.organise.mybatis.db.mybatis.model.FeedTypesExample;



public interface FeedTypesMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table feed_types
     *
     * @mbggenerated Fri Sep 21 12:06:28 BST 2012
     */
    int countByExample(FeedTypesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table feed_types
     *
     * @mbggenerated Fri Sep 21 12:06:28 BST 2012
     */
    int deleteByExample(FeedTypesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table feed_types
     *
     * @mbggenerated Fri Sep 21 12:06:28 BST 2012
     */
    int deleteByPrimaryKey(Byte id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table feed_types
     *
     * @mbggenerated Fri Sep 21 12:06:28 BST 2012
     */
    int insert(FeedTypes record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table feed_types
     *
     * @mbggenerated Fri Sep 21 12:06:28 BST 2012
     */
    int insertSelective(FeedTypes record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table feed_types
     *
     * @mbggenerated Fri Sep 21 12:06:28 BST 2012
     */
    List<FeedTypes> selectByExample(FeedTypesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table feed_types
     *
     * @mbggenerated Fri Sep 21 12:06:28 BST 2012
     */
    FeedTypes selectByPrimaryKey(Byte id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table feed_types
     *
     * @mbggenerated Fri Sep 21 12:06:28 BST 2012
     */
    int updateByExampleSelective(@Param("record") FeedTypes record, @Param("example") FeedTypesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table feed_types
     *
     * @mbggenerated Fri Sep 21 12:06:28 BST 2012
     */
    int updateByExample(@Param("record") FeedTypes record, @Param("example") FeedTypesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table feed_types
     *
     * @mbggenerated Fri Sep 21 12:06:28 BST 2012
     */
    int updateByPrimaryKeySelective(FeedTypes record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table feed_types
     *
     * @mbggenerated Fri Sep 21 12:06:28 BST 2012
     */
    int updateByPrimaryKey(FeedTypes record);
    
    @Select("SELECT id, name FROM feed_types")
    @MapKey("id")
    Map<Integer,FeedTypes> getAllFeedTypes();
}