package com.jemmmedia.organise.mybatis.db.mybatis.dao;

import java.util.List;

import org.apache.ibatis.annotations.Param;

import com.jemmmedia.organise.mybatis.db.mybatis.model.FeedEntryWithChild;
import com.jemmmedia.organise.mybatis.db.mybatis.model.FeedEntryWithChildExample;

public interface FeedEntryWithChildMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table feed_entry_child
     *
     * @mbggenerated Mon Aug 27 07:55:02 BST 2012
     */
    int countByExample(FeedEntryWithChildExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table feed_entry_child
     *
     * @mbggenerated Mon Aug 27 07:55:02 BST 2012
     */
    int deleteByExample(FeedEntryWithChildExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table feed_entry_child
     *
     * @mbggenerated Mon Aug 27 07:55:02 BST 2012
     */
    int insert(FeedEntryWithChild record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table feed_entry_child
     *
     * @mbggenerated Mon Aug 27 07:55:02 BST 2012
     */
    int insertSelective(FeedEntryWithChild record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table feed_entry_child
     *
     * @mbggenerated Mon Aug 27 07:55:02 BST 2012
     */
    List<FeedEntryWithChild> selectByExample(FeedEntryWithChildExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table feed_entry_child
     *
     * @mbggenerated Mon Aug 27 07:55:02 BST 2012
     */
    int updateByExampleSelective(@Param("record") FeedEntryWithChild record, @Param("example") FeedEntryWithChildExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table feed_entry_child
     *
     * @mbggenerated Mon Aug 27 07:55:02 BST 2012
     */
    int updateByExample(@Param("record") FeedEntryWithChild record, @Param("example") FeedEntryWithChildExample example);
    
    List<FeedEntryWithChild>selectChildFeedIds(Long id);
    
    void deleteFeedEntryChild(Long id);
}