package com.jemmmedia.organise.mybatis.db.mybatis.dao;

import java.util.List;

import org.apache.ibatis.annotations.Param;

import com.jemmmedia.organise.mybatis.db.mybatis.model.FeedEntriesAttachments;
import com.jemmmedia.organise.mybatis.db.mybatis.model.FeedEntriesAttachmentsExample;

public interface FeedEntriesAttachmentsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table feed_entries_attachments
     *
     * @mbggenerated Wed Aug 22 22:11:02 BST 2012
     */
    int countByExample(FeedEntriesAttachmentsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table feed_entries_attachments
     *
     * @mbggenerated Wed Aug 22 22:11:02 BST 2012
     */
    int deleteByExample(FeedEntriesAttachmentsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table feed_entries_attachments
     *
     * @mbggenerated Wed Aug 22 22:11:02 BST 2012
     */
    int insert(FeedEntriesAttachments record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table feed_entries_attachments
     *
     * @mbggenerated Wed Aug 22 22:11:02 BST 2012
     */
    int insertSelective(FeedEntriesAttachments record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table feed_entries_attachments
     *
     * @mbggenerated Wed Aug 22 22:11:02 BST 2012
     */
    List<FeedEntriesAttachments> selectByExample(FeedEntriesAttachmentsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table feed_entries_attachments
     *
     * @mbggenerated Wed Aug 22 22:11:02 BST 2012
     */
    int updateByExampleSelective(@Param("record") FeedEntriesAttachments record, @Param("example") FeedEntriesAttachmentsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table feed_entries_attachments
     *
     * @mbggenerated Wed Aug 22 22:11:02 BST 2012
     */
    int updateByExample(@Param("record") FeedEntriesAttachments record, @Param("example") FeedEntriesAttachmentsExample example);
    
    List<Long> selectById(Long id);
    
    void deleteById(Long id);
    
}