package com.jemmmedia.organise.mybatis.db.mybatis.dao;


import java.util.List;

import org.apache.ibatis.annotations.Param;

import com.jemmmedia.organise.mybatis.db.mybatis.model.FileAttachment;
import com.jemmmedia.organise.mybatis.db.mybatis.model.FileAttachmentExample;

public interface FileAttachmentMapper {
    /**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table file_attachments
	 * @mbggenerated  Fri Sep 14 06:32:16 BST 2012
	 */
	int countByExample(FileAttachmentExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table file_attachments
	 * @mbggenerated  Fri Sep 14 06:32:16 BST 2012
	 */
	int deleteByExample(FileAttachmentExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table file_attachments
	 * @mbggenerated  Fri Sep 14 06:32:16 BST 2012
	 */
	int deleteByPrimaryKey(Long id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table file_attachments
	 * @mbggenerated  Fri Sep 14 06:32:16 BST 2012
	 */
	int insert(FileAttachment record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table file_attachments
	 * @mbggenerated  Fri Sep 14 06:32:16 BST 2012
	 */
	int insertSelective(FileAttachment record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table file_attachments
	 * @mbggenerated  Fri Sep 14 06:32:16 BST 2012
	 */
	List<FileAttachment> selectByExample(FileAttachmentExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table file_attachments
	 * @mbggenerated  Fri Sep 14 06:32:16 BST 2012
	 */
	FileAttachment selectByPrimaryKey(Long id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table file_attachments
	 * @mbggenerated  Fri Sep 14 06:32:16 BST 2012
	 */
	int updateByExampleSelective(@Param("record") FileAttachment record,
			@Param("example") FileAttachmentExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table file_attachments
	 * @mbggenerated  Fri Sep 14 06:32:16 BST 2012
	 */
	int updateByExample(@Param("record") FileAttachment record,
			@Param("example") FileAttachmentExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table file_attachments
	 * @mbggenerated  Fri Sep 14 06:32:16 BST 2012
	 */
	int updateByPrimaryKeySelective(FileAttachment record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table file_attachments
	 * @mbggenerated  Fri Sep 14 06:32:16 BST 2012
	 */
	int updateByPrimaryKey(FileAttachment record);

	List<FileAttachment> getFeedAttachments(Long id);
}