package com.jemmmedia.organise.mybatis.db.mybatis.dao;

import java.util.List;

import org.apache.ibatis.annotations.Param;

import com.jemmmedia.organise.mybatis.db.mybatis.model.Groups;
import com.jemmmedia.organise.mybatis.db.mybatis.model.GroupsExample;

public interface GroupsMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table groups
	 * @mbggenerated  Tue Mar 12 14:20:31 GMT 2013
	 */
	int countByExample(GroupsExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table groups
	 * @mbggenerated  Tue Mar 12 14:20:31 GMT 2013
	 */
	int deleteByExample(GroupsExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table groups
	 * @mbggenerated  Tue Mar 12 14:20:31 GMT 2013
	 */
	int deleteByPrimaryKey(Long id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table groups
	 * @mbggenerated  Tue Mar 12 14:20:31 GMT 2013
	 */
	int insert(Groups record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table groups
	 * @mbggenerated  Tue Mar 12 14:20:31 GMT 2013
	 */
	int insertSelective(Groups record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table groups
	 * @mbggenerated  Tue Mar 12 14:20:31 GMT 2013
	 */
	List<Groups> selectByExample(GroupsExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table groups
	 * @mbggenerated  Tue Mar 12 14:20:31 GMT 2013
	 */
	Groups selectByPrimaryKey(Long id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table groups
	 * @mbggenerated  Tue Mar 12 14:20:31 GMT 2013
	 */
	int updateByExampleSelective(@Param("record") Groups record,
			@Param("example") GroupsExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table groups
	 * @mbggenerated  Tue Mar 12 14:20:31 GMT 2013
	 */
	int updateByExample(@Param("record") Groups record,
			@Param("example") GroupsExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table groups
	 * @mbggenerated  Tue Mar 12 14:20:31 GMT 2013
	 */
	int updateByPrimaryKeySelective(Groups record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table groups
	 * @mbggenerated  Tue Mar 12 14:20:31 GMT 2013
	 */
	int updateByPrimaryKey(Groups record);
	
	String selectGroupPackage(long groupid);
	
	String selectEmailsForRemiders();
	
	List<Groups> selectAllGroups();
	
}