package com.jemmmedia.organise.mybatis.db.mybatis.dao;

import java.util.List;

import org.apache.ibatis.annotations.Param;

import com.jemmmedia.organise.mybatis.db.mybatis.model.HighriseParty;
import com.jemmmedia.organise.mybatis.db.mybatis.model.HighrisePartyExample;

public interface HighrisePartyMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table highrise_party
	 * @mbggenerated  Tue Oct 29 13:42:10 GMT 2013
	 */
	int countByExample(HighrisePartyExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table highrise_party
	 * @mbggenerated  Tue Oct 29 13:42:10 GMT 2013
	 */
	int deleteByExample(HighrisePartyExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table highrise_party
	 * @mbggenerated  Tue Oct 29 13:42:10 GMT 2013
	 */
	int deleteByPrimaryKey(Long id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table highrise_party
	 * @mbggenerated  Tue Oct 29 13:42:10 GMT 2013
	 */
	int insert(HighriseParty record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table highrise_party
	 * @mbggenerated  Tue Oct 29 13:42:10 GMT 2013
	 */
	int insertSelective(HighriseParty record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table highrise_party
	 * @mbggenerated  Tue Oct 29 13:42:10 GMT 2013
	 */
	List<HighriseParty> selectByExampleWithBLOBs(HighrisePartyExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table highrise_party
	 * @mbggenerated  Tue Oct 29 13:42:10 GMT 2013
	 */
	List<HighriseParty> selectByExample(HighrisePartyExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table highrise_party
	 * @mbggenerated  Tue Oct 29 13:42:10 GMT 2013
	 */
	HighriseParty selectByPrimaryKey(Long id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table highrise_party
	 * @mbggenerated  Tue Oct 29 13:42:10 GMT 2013
	 */
	int updateByExampleSelective(@Param("record") HighriseParty record,
			@Param("example") HighrisePartyExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table highrise_party
	 * @mbggenerated  Tue Oct 29 13:42:10 GMT 2013
	 */
	int updateByExampleWithBLOBs(@Param("record") HighriseParty record,
			@Param("example") HighrisePartyExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table highrise_party
	 * @mbggenerated  Tue Oct 29 13:42:10 GMT 2013
	 */
	int updateByExample(@Param("record") HighriseParty record,
			@Param("example") HighrisePartyExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table highrise_party
	 * @mbggenerated  Tue Oct 29 13:42:10 GMT 2013
	 */
	int updateByPrimaryKeySelective(HighriseParty record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table highrise_party
	 * @mbggenerated  Tue Oct 29 13:42:10 GMT 2013
	 */
	int updateByPrimaryKeyWithBLOBs(HighriseParty record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table highrise_party
	 * @mbggenerated  Tue Oct 29 13:42:10 GMT 2013
	 */
	int updateByPrimaryKey(HighriseParty record);
}