package com.jemmmedia.organise.mybatis.db.mybatis.dao;

import java.util.List;

import org.apache.ibatis.annotations.Param;

import com.jemmmedia.organise.mybatis.db.mybatis.model.HighriseUsers;
import com.jemmmedia.organise.mybatis.db.mybatis.model.HighriseUsersExample;

public interface HighriseUsersMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table highrise_users
	 * @mbggenerated  Tue Oct 29 13:42:10 GMT 2013
	 */
	int countByExample(HighriseUsersExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table highrise_users
	 * @mbggenerated  Tue Oct 29 13:42:10 GMT 2013
	 */
	int deleteByExample(HighriseUsersExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table highrise_users
	 * @mbggenerated  Tue Oct 29 13:42:10 GMT 2013
	 */
	int deleteByPrimaryKey(Long id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table highrise_users
	 * @mbggenerated  Tue Oct 29 13:42:10 GMT 2013
	 */
	int insert(HighriseUsers record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table highrise_users
	 * @mbggenerated  Tue Oct 29 13:42:10 GMT 2013
	 */
	int insertSelective(HighriseUsers record);
	
	

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table highrise_users
	 * @mbggenerated  Tue Oct 29 13:42:10 GMT 2013
	 */
	List<HighriseUsers> selectByExample(HighriseUsersExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table highrise_users
	 * @mbggenerated  Tue Oct 29 13:42:10 GMT 2013
	 */
	HighriseUsers selectByPrimaryKey(Long id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table highrise_users
	 * @mbggenerated  Tue Oct 29 13:42:10 GMT 2013
	 */
	int updateByExampleSelective(@Param("record") HighriseUsers record,
			@Param("example") HighriseUsersExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table highrise_users
	 * @mbggenerated  Tue Oct 29 13:42:10 GMT 2013
	 */
	int updateByExample(@Param("record") HighriseUsers record,
			@Param("example") HighriseUsersExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table highrise_users
	 * @mbggenerated  Tue Oct 29 13:42:10 GMT 2013
	 */
	int updateByPrimaryKeySelective(HighriseUsers record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table highrise_users
	 * @mbggenerated  Tue Oct 29 13:42:10 GMT 2013
	 */
	int updateByPrimaryKey(HighriseUsers record);
	
	
	int insertOrReplaceUsers(HighriseUsers record);
}