package com.jemmmedia.organise.mybatis.db.mybatis.dao;

import java.util.List;

import org.apache.ibatis.annotations.Param;

import com.jemmmedia.organise.mybatis.db.mybatis.model.HighriseDeals;
import com.jemmmedia.organise.mybatis.db.mybatis.model.HighriseDealsExample;

public interface HighriseDealsMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table highrise_deals
	 * @mbggenerated  Tue Oct 29 13:42:10 GMT 2013
	 */
	int countByExample(HighriseDealsExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table highrise_deals
	 * @mbggenerated  Tue Oct 29 13:42:10 GMT 2013
	 */
	int deleteByExample(HighriseDealsExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table highrise_deals
	 * @mbggenerated  Tue Oct 29 13:42:10 GMT 2013
	 */
	int deleteByPrimaryKey(Long id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table highrise_deals
	 * @mbggenerated  Tue Oct 29 13:42:10 GMT 2013
	 */
	int insert(HighriseDeals record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table highrise_deals
	 * @mbggenerated  Tue Oct 29 13:42:10 GMT 2013
	 */
	int insertSelective(HighriseDeals record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table highrise_deals
	 * @mbggenerated  Tue Oct 29 13:42:10 GMT 2013
	 */
	List<HighriseDeals> selectByExampleWithBLOBs(HighriseDealsExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table highrise_deals
	 * @mbggenerated  Tue Oct 29 13:42:10 GMT 2013
	 */
	List<HighriseDeals> selectByExample(HighriseDealsExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table highrise_deals
	 * @mbggenerated  Tue Oct 29 13:42:10 GMT 2013
	 */
	HighriseDeals selectByPrimaryKey(Long id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table highrise_deals
	 * @mbggenerated  Tue Oct 29 13:42:10 GMT 2013
	 */
	int updateByExampleSelective(@Param("record") HighriseDeals record,
			@Param("example") HighriseDealsExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table highrise_deals
	 * @mbggenerated  Tue Oct 29 13:42:10 GMT 2013
	 */
	int updateByExampleWithBLOBs(@Param("record") HighriseDeals record,
			@Param("example") HighriseDealsExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table highrise_deals
	 * @mbggenerated  Tue Oct 29 13:42:10 GMT 2013
	 */
	int updateByExample(@Param("record") HighriseDeals record,
			@Param("example") HighriseDealsExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table highrise_deals
	 * @mbggenerated  Tue Oct 29 13:42:10 GMT 2013
	 */
	int updateByPrimaryKeySelective(HighriseDeals record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table highrise_deals
	 * @mbggenerated  Tue Oct 29 13:42:10 GMT 2013
	 */
	int updateByPrimaryKeyWithBLOBs(HighriseDeals record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table highrise_deals
	 * @mbggenerated  Tue Oct 29 13:42:10 GMT 2013
	 */
	int updateByPrimaryKey(HighriseDeals record);
	
	List<Long> selectDealIds();
	
	int updateByDealIdSelective(HighriseDeals record);
}