package com.jemmmedia.organise.mybatis.db.mybatis.dao;

import java.util.List;

import org.apache.ibatis.annotations.Param;

import com.jemmmedia.organise.mybatis.db.mybatis.model.Orders;
import com.jemmmedia.organise.mybatis.db.mybatis.model.OrdersExample;

public interface OrdersMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table orders
	 * @mbggenerated  Thu May 30 11:43:05 BST 2013
	 */
	int countByExample(OrdersExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table orders
	 * @mbggenerated  Thu May 30 11:43:05 BST 2013
	 */
	int deleteByExample(OrdersExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table orders
	 * @mbggenerated  Thu May 30 11:43:05 BST 2013
	 */
	int deleteByPrimaryKey(Long id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table orders
	 * @mbggenerated  Thu May 30 11:43:05 BST 2013
	 */
	int insert(Orders record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table orders
	 * @mbggenerated  Thu May 30 11:43:05 BST 2013
	 */
	int insertSelective(Orders record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table orders
	 * @mbggenerated  Thu May 30 11:43:05 BST 2013
	 */
	List<Orders> selectByExample(OrdersExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table orders
	 * @mbggenerated  Thu May 30 11:43:05 BST 2013
	 */
	Orders selectByPrimaryKey(Long id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table orders
	 * @mbggenerated  Thu May 30 11:43:05 BST 2013
	 */
	int updateByExampleSelective(@Param("record") Orders record,
			@Param("example") OrdersExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table orders
	 * @mbggenerated  Thu May 30 11:43:05 BST 2013
	 */
	int updateByExample(@Param("record") Orders record,
			@Param("example") OrdersExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table orders
	 * @mbggenerated  Thu May 30 11:43:05 BST 2013
	 */
	int updateByPrimaryKeySelective(Orders record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table orders
	 * @mbggenerated  Thu May 30 11:43:05 BST 2013
	 */
	int updateByPrimaryKey(Orders record);
}