package com.jemmmedia.organise.mybatis.db.mybatis.dao;

import java.util.List;

import org.apache.ibatis.annotations.Param;

import com.jemmmedia.organise.mybatis.db.mybatis.model.PackagesSupport;
import com.jemmmedia.organise.mybatis.db.mybatis.model.PackagesSupportExample;

public interface PackagesSupportMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table packages_support
	 * @mbggenerated  Tue Mar 12 14:20:31 GMT 2013
	 */
	int countByExample(PackagesSupportExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table packages_support
	 * @mbggenerated  Tue Mar 12 14:20:31 GMT 2013
	 */
	int deleteByExample(PackagesSupportExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table packages_support
	 * @mbggenerated  Tue Mar 12 14:20:31 GMT 2013
	 */
	int deleteByPrimaryKey(Long id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table packages_support
	 * @mbggenerated  Tue Mar 12 14:20:31 GMT 2013
	 */
	int insert(PackagesSupport record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table packages_support
	 * @mbggenerated  Tue Mar 12 14:20:31 GMT 2013
	 */
	int insertSelective(PackagesSupport record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table packages_support
	 * @mbggenerated  Tue Mar 12 14:20:31 GMT 2013
	 */
	List<PackagesSupport> selectByExample(PackagesSupportExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table packages_support
	 * @mbggenerated  Tue Mar 12 14:20:31 GMT 2013
	 */
	PackagesSupport selectByPrimaryKey(Long id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table packages_support
	 * @mbggenerated  Tue Mar 12 14:20:31 GMT 2013
	 */
	int updateByExampleSelective(@Param("record") PackagesSupport record,
			@Param("example") PackagesSupportExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table packages_support
	 * @mbggenerated  Tue Mar 12 14:20:31 GMT 2013
	 */
	int updateByExample(@Param("record") PackagesSupport record,
			@Param("example") PackagesSupportExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table packages_support
	 * @mbggenerated  Tue Mar 12 14:20:31 GMT 2013
	 */
	int updateByPrimaryKeySelective(PackagesSupport record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table packages_support
	 * @mbggenerated  Tue Mar 12 14:20:31 GMT 2013
	 */
	int updateByPrimaryKey(PackagesSupport record);
}