package com.jemmmedia.organise.mybatis.db.mybatis.dao;

import java.util.List;

import org.apache.ibatis.annotations.Param;

import com.jemmmedia.organise.mybatis.db.mybatis.model.PackagesPricing;
import com.jemmmedia.organise.mybatis.db.mybatis.model.PackagesPricingExample;

public interface PackagesPricingMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table packages_pricing
	 * @mbggenerated  Tue Mar 12 14:20:31 GMT 2013
	 */
	int countByExample(PackagesPricingExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table packages_pricing
	 * @mbggenerated  Tue Mar 12 14:20:31 GMT 2013
	 */
	int deleteByExample(PackagesPricingExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table packages_pricing
	 * @mbggenerated  Tue Mar 12 14:20:31 GMT 2013
	 */
	int deleteByPrimaryKey(Long id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table packages_pricing
	 * @mbggenerated  Tue Mar 12 14:20:31 GMT 2013
	 */
	int insert(PackagesPricing record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table packages_pricing
	 * @mbggenerated  Tue Mar 12 14:20:31 GMT 2013
	 */
	int insertSelective(PackagesPricing record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table packages_pricing
	 * @mbggenerated  Tue Mar 12 14:20:31 GMT 2013
	 */
	List<PackagesPricing> selectByExample(PackagesPricingExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table packages_pricing
	 * @mbggenerated  Tue Mar 12 14:20:31 GMT 2013
	 */
	PackagesPricing selectByPrimaryKey(Long id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table packages_pricing
	 * @mbggenerated  Tue Mar 12 14:20:31 GMT 2013
	 */
	int updateByExampleSelective(@Param("record") PackagesPricing record,
			@Param("example") PackagesPricingExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table packages_pricing
	 * @mbggenerated  Tue Mar 12 14:20:31 GMT 2013
	 */
	int updateByExample(@Param("record") PackagesPricing record,
			@Param("example") PackagesPricingExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table packages_pricing
	 * @mbggenerated  Tue Mar 12 14:20:31 GMT 2013
	 */
	int updateByPrimaryKeySelective(PackagesPricing record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table packages_pricing
	 * @mbggenerated  Tue Mar 12 14:20:31 GMT 2013
	 */
	int updateByPrimaryKey(PackagesPricing record);
}