package com.jemmmedia.organise.mybatis.db.mybatis.dao;

import java.util.List;

import org.apache.ibatis.annotations.Param;

import com.jemmmedia.organise.mybatis.db.mybatis.model.PackagesPlatinum;
import com.jemmmedia.organise.mybatis.db.mybatis.model.PackagesPlatinumExample;

public interface PackagesPlatinumMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table packages_platinum
	 * @mbggenerated  Tue Mar 12 14:20:31 GMT 2013
	 */
	int countByExample(PackagesPlatinumExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table packages_platinum
	 * @mbggenerated  Tue Mar 12 14:20:31 GMT 2013
	 */
	int deleteByExample(PackagesPlatinumExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table packages_platinum
	 * @mbggenerated  Tue Mar 12 14:20:31 GMT 2013
	 */
	int deleteByPrimaryKey(Long id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table packages_platinum
	 * @mbggenerated  Tue Mar 12 14:20:31 GMT 2013
	 */
	int insert(PackagesPlatinum record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table packages_platinum
	 * @mbggenerated  Tue Mar 12 14:20:31 GMT 2013
	 */
	int insertSelective(PackagesPlatinum record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table packages_platinum
	 * @mbggenerated  Tue Mar 12 14:20:31 GMT 2013
	 */
	List<PackagesPlatinum> selectByExample(PackagesPlatinumExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table packages_platinum
	 * @mbggenerated  Tue Mar 12 14:20:31 GMT 2013
	 */
	PackagesPlatinum selectByPrimaryKey(Long id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table packages_platinum
	 * @mbggenerated  Tue Mar 12 14:20:31 GMT 2013
	 */
	int updateByExampleSelective(@Param("record") PackagesPlatinum record,
			@Param("example") PackagesPlatinumExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table packages_platinum
	 * @mbggenerated  Tue Mar 12 14:20:31 GMT 2013
	 */
	int updateByExample(@Param("record") PackagesPlatinum record,
			@Param("example") PackagesPlatinumExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table packages_platinum
	 * @mbggenerated  Tue Mar 12 14:20:31 GMT 2013
	 */
	int updateByPrimaryKeySelective(PackagesPlatinum record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table packages_platinum
	 * @mbggenerated  Tue Mar 12 14:20:31 GMT 2013
	 */
	int updateByPrimaryKey(PackagesPlatinum record);
}