package com.jemmmedia.organise.mybatis.db.mybatis.dao;

import java.util.List;

import org.apache.ibatis.annotations.Param;

import com.jemmmedia.organise.mybatis.db.mybatis.model.RegionsAnnouncementsExample;
import com.jemmmedia.organise.mybatis.db.mybatis.model.RegionsAnnouncementsKey;

public interface RegionsAnnouncementsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table regions_announcements
     *
     * @mbggenerated Mon Mar 25 14:20:14 GMT 2013
     */
    int countByExample(RegionsAnnouncementsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table regions_announcements
     *
     * @mbggenerated Mon Mar 25 14:20:14 GMT 2013
     */
    int deleteByExample(RegionsAnnouncementsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table regions_announcements
     *
     * @mbggenerated Mon Mar 25 14:20:14 GMT 2013
     */
    int deleteByPrimaryKey(RegionsAnnouncementsKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table regions_announcements
     *
     * @mbggenerated Mon Mar 25 14:20:14 GMT 2013
     */
    int insert(RegionsAnnouncementsKey record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table regions_announcements
     *
     * @mbggenerated Mon Mar 25 14:20:14 GMT 2013
     */
    int insertSelective(RegionsAnnouncementsKey record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table regions_announcements
     *
     * @mbggenerated Mon Mar 25 14:20:14 GMT 2013
     */
    List<RegionsAnnouncementsKey> selectByExample(RegionsAnnouncementsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table regions_announcements
     *
     * @mbggenerated Mon Mar 25 14:20:14 GMT 2013
     */
    int updateByExampleSelective(@Param("record") RegionsAnnouncementsKey record, @Param("example") RegionsAnnouncementsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table regions_announcements
     *
     * @mbggenerated Mon Mar 25 14:20:14 GMT 2013
     */
    int updateByExample(@Param("record") RegionsAnnouncementsKey record, @Param("example") RegionsAnnouncementsExample example);
    
    int insertOrUpdateSelective(RegionsAnnouncementsKey record);
}