package com.jemmmedia.organise.mybatis.db.mybatis.dao;

import java.util.List;

import org.apache.ibatis.annotations.Param;

import com.jemmmedia.organise.mybatis.db.mybatis.model.UsersWithRoles;
import com.jemmmedia.organise.mybatis.db.mybatis.model.UsersWithRolesExample;

public interface UsersWithRolesMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table roles_users
	 * @mbggenerated  Fri Jan 25 12:14:36 GMT 2013
	 */
	int countByExample(UsersWithRolesExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table roles_users
	 * @mbggenerated  Fri Jan 25 12:14:36 GMT 2013
	 */
	int deleteByExample(UsersWithRolesExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table roles_users
	 * @mbggenerated  Fri Jan 25 12:14:36 GMT 2013
	 */
	int deleteByPrimaryKey(Long userId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table roles_users
	 * @mbggenerated  Fri Jan 25 12:14:36 GMT 2013
	 */
	int insert(UsersWithRoles record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table roles_users
	 * @mbggenerated  Fri Jan 25 12:14:36 GMT 2013
	 */
	int insertSelective(UsersWithRoles record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table roles_users
	 * @mbggenerated  Fri Jan 25 12:14:36 GMT 2013
	 */
	List<UsersWithRoles> selectByExample(UsersWithRolesExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table roles_users
	 * @mbggenerated  Fri Jan 25 12:14:36 GMT 2013
	 */
	UsersWithRoles selectByPrimaryKey(Long userId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table roles_users
	 * @mbggenerated  Fri Jan 25 12:14:36 GMT 2013
	 */
	int updateByExampleSelective(@Param("record") UsersWithRoles record,
			@Param("example") UsersWithRolesExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table roles_users
	 * @mbggenerated  Fri Jan 25 12:14:36 GMT 2013
	 */
	int updateByExample(@Param("record") UsersWithRoles record,
			@Param("example") UsersWithRolesExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table roles_users
	 * @mbggenerated  Fri Jan 25 12:14:36 GMT 2013
	 */
	int updateByPrimaryKeySelective(UsersWithRoles record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table roles_users
	 * @mbggenerated  Fri Jan 25 12:14:36 GMT 2013
	 */
	int updateByPrimaryKey(UsersWithRoles record);
}