package com.jemmmedia.organise.mybatis.db.mybatis.dao;

import java.util.List;

import org.apache.ibatis.annotations.Param;

import com.jemmmedia.organise.mybatis.db.mybatis.model.User;
import com.jemmmedia.organise.mybatis.db.mybatis.model.UserDetailedBean;
import com.jemmmedia.organise.mybatis.db.mybatis.model.UserExample;

public interface UserMapper {
    /**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table users
	 * @mbggenerated  Thu Apr 04 15:35:42 BST 2013
	 */
	int countByExample(UserExample example);


	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table users
	 * @mbggenerated  Thu Apr 04 15:35:42 BST 2013
	 */
	int deleteByExample(UserExample example);


	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table users
	 * @mbggenerated  Thu Apr 04 15:35:42 BST 2013
	 */
	int deleteByPrimaryKey(Long id);


	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table users
	 * @mbggenerated  Thu Apr 04 15:35:42 BST 2013
	 */
	int insert(User record);


	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table users
	 * @mbggenerated  Thu Apr 04 15:35:42 BST 2013
	 */
	int insertSelective(User record);


	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table users
	 * @mbggenerated  Thu Apr 04 15:35:42 BST 2013
	 */
	List<User> selectByExample(UserExample example);


	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table users
	 * @mbggenerated  Thu Apr 04 15:35:42 BST 2013
	 */
	User selectByPrimaryKey(Long id);


	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table users
	 * @mbggenerated  Thu Apr 04 15:35:42 BST 2013
	 */
	int updateByExampleSelective(@Param("record") User record,
			@Param("example") UserExample example);


	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table users
	 * @mbggenerated  Thu Apr 04 15:35:42 BST 2013
	 */
	int updateByExample(@Param("record") User record,
			@Param("example") UserExample example);


	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table users
	 * @mbggenerated  Thu Apr 04 15:35:42 BST 2013
	 */
	int updateByPrimaryKeySelective(User record);


	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table users
	 * @mbggenerated  Thu Apr 04 15:35:42 BST 2013
	 */
	int updateByPrimaryKey(User record);


	List<UserDetailedBean> selectAllUsersDetail(@Param("groupId")long groupId, @Param("ids") List<Long> ids);
	
	List<UserDetailedBean> filterUsers(@Param("groupId")long groupId, @Param("searchStr") String searchStr);
	

	// Get User Detail
    UserDetailedBean getUser(String username);
    
   /* @Select("SELECT id, username FROM users where user_type = 0 order by username")
    @MapKey("id")*/
    List<User>getAllUsers(@Param("groupId")long groupId, @Param("ids") List<Long> ids); 
    
    List<User> selectCheckedUsers(String usersId);
    
    List<User> selectUnCheckedUsers(@Param("groupId")long groupId, @Param("usersId") List<String> usersId);
    
    int checkUserExist(String email);
    
    int selectUsersInRegion(long regionId);
    
    int countByGroup(long groupId);
    
    UserDetailedBean getUserPackage(long groupId);
    
    void taskAssignedEmail(@Param("taskAddEmail")boolean taskAddEmail, @Param("id") long Id);
    
    void postTaskEmail(@Param("taskUpdateEmail")boolean taskAddEmail, @Param("id") long Id);
    
    List<User>selectAllGroups(); 
    
    String selectSuperUersEmail(long groupId);
    
    List<User> selectUsersInTask(@Param("id")long id, @Param("ids") List<Long> ids);
}